### ISSUE TITLE
new query filters

### ISSUE THREAD

**Issue by oscargare** [weDevsOfficial/dokan#1]
Hi, your plugin is great! 
I need some new query filters for dokan_author_total_sales and dokan_get_seller_balance to apply exchange rates in multicurrency stores.
Is it possible to add filters for these two functions?

**Comment by sabbir1991** [comment]
Resolved

**Comment by oscargare** [comment]
Hi, thank you for add the filters. It would better if you added the params **seller_id** and _formatted_ to the _apply_filters_ function.
