### ISSUE TITLE
Withdrawal Option 

### ISSUE THREAD

**Issue by techlance** [weDevsOfficial/dokan#1003]
I have a client who installed dokan pro plugin, I cannot update the withdrawal option to bank transfer or any other withdrawal method

**Comment by nurul-umbhiya** [comment]
This is a known issue and will be fixed in the next release tomorrow.

**Comment by techlance** [comment]
> This is a known issue and will be fixed in the next release tomorrow.

When will the next update gonna rollout for this bug?
