### ISSUE TITLE
Order status change notification to vendor

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#1055]
**Description:**
If the admin change status of an order from the wp-admin area, the vendor does not get any email notification about the change.

**How to reproduce:**
1. Navigate to wp-admin > WooCommerce > Orders
2. Change any order status of any vendor's orders
3. The customer gets the notification about the changes but the vendor does not

**Expected behavior:**
The vendor should get an email notification when his order status is updated by the admin. 

**Versions:**
Dokan Lite - 3.1.2
WC - 4.8.0

**Comment by kapilpaul** [comment]
Could not reproduce the issue.

screenshot: https://prnt.sc/x4a6qf

Please let me know if the issue still exists.

**Comment by vasudevz** [comment]
One needs to create a seller id, process an order and then when the order is placed, the seller does not receive an email. One cant reproduce not receiving a email to seller without being a seller.
