### ISSUE TITLE
Show admin store on store listing page

### ISSUE THREAD

**Issue by Mohaiminulislam1989** [weDevsOfficial/dokan#1065]
When the admin creates a store and sells products, then dokan should show the admin's store on the store listing page and also show the admin's store name on the cart page.
https://imgur.com/tx7OVet
https://imgur.com/gxaDCag

**Comment by alamgircsebd** [comment]
Can't reproduce the issue, please make the admin have enabled seller option

**Comment by Mohaiminulislam1989** [comment]
Not an issue. Settings was not set properly.
