### ISSUE TITLE
Admin Setup Wizard : Combine commission field is missing on setup wizard

### ISSUE THREAD

**Issue by shanjidah** [weDevsOfficial/dokan#1074]
**Title**: When admin activates dokan pro then activate dokan-lite combine commission field missing.
**How to reproduce:**
1.Login As admin.
2.activate dokan pro then activate dokan-lite
3.set wizard.

**Actual Result**: combine commission field missing.
**Here is the screenshot:**
https://prnt.sc/xoxqou

**Comment by FaraziF** [comment]
When added combine commission in the setup wizards then fixed-rate not save in the selling options.
[Reference Image](https://prnt.sc/105avk2)
