### ISSUE TITLE
Style conflict, between MapBox and Dokan Store-listing CSS

### ISSUE THREAD

**Issue by o-Chamie-o** [weDevsOfficial/dokan#1084]
**Describe the bug**
Zoom-in and out buttons not showing

**To Reproduce**
1. Setup MabBox for store listing
2. On the page the zooms buttons are not showing on the maps.

**Expected behavior**
The zoom button shoudl be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/16864366/107115314-0d126c80-686c-11eb-9971-b4d8a683339a.png)

**Environment (please complete the following information):**
 - Dokan Version: [e.g. v3.1.2]
 - Dokan Pro Version: [e.g. v3.1.2]
 - WooCommerce Version: [e.g. v4.9.2]
 - Current Theme: [e.g. Store Front]

**Additional context**
This is due to this big unset in CSS for the store listing page here : https://github.com/weDevsOfficial/dokan/blob/38a514041c017135e0c0bf75c641bdd71763ae2c/assets/css/style.css#L4802

https://github.com/weDevsOfficial/dokan/blob/38a514041c017135e0c0bf75c641bdd71763ae2c/assets/css/style.css#L4817

**Comment by alamgircsebd** [comment]
Resolved on dokan pro, hope next release have this fix - https://github.com/weDevsOfficial/dokan-pro/pull/1082

**Comment by o-Chamie-o** [comment]
Hum, can't we have a fix in dokan-lite side?

This could touch also other plugins no?

**Comment by alamgircsebd** [comment]
> Hum, can't we have a fix in dokan-lite side?
> 
> This could touch also other plugins no?

Hello @o-Chamie-o 

You can use the below codes on your theme style or custom css area, hope it will be work perfectly. 

`.mapboxgl-ctrl-group > button {
    width: 30px !important;
    display: block !important;
}
.mapboxgl-ctrl-icon.mapboxgl-ctrl-compass > .mapboxgl-ctrl-compass-arrow {
    width: 20px !important;
    display: inline-block !important;
} `

**Comment by o-Chamie-o** [comment]
Yeah this is what I did. :(

This is pretty dirty tho...

**Comment by alamgircsebd** [comment]
Until our next release you can use this

**Comment by nurul-umbhiya** [comment]
@alamgircsebd is this issue fixed? if so kindly close this.

**Comment by nurul-umbhiya** [comment]
@alamgircsebd can you please update about this issue?

**Comment by alamgircsebd** [comment]
Resolved and have on released version v3.2.6
