### ISSUE TITLE
Unable to update product vai REST API

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#1092]
**Describe the bug**
It is not possible to update a product using REST API when authenticated **as a vendor**. It gives this error message -

`{
    "code": "dokan_rest_product_invalid_id",
    "message": "Sorry, you have no permission to do this. Since it's not your product.",
    "data": {
        "status": 400
    }
}`

**To Reproduce**
1. Authenticate as a vendor account
2. Use the REST request from here - https://wedevsofficial.github.io/dokan/#update-a-product
2. Update a product parameter and send the request
3. The error message will show

**Expected behavior**
A vendor who is authenticated should be able to update product parameters with REST API request.

**Screenshots**
https://prnt.sc/zqkaul

**Environment (please complete the following information):**
 - Dokan Version: 3.2.1
 - Dokan Pro Version: 3.2.0
 - WooCommerce Version: 4.9.2

**Additional context**
Reported here - https://wordpress.org/support/topic/problem-in-update-product-in-rest-api/

**Suggestions**
Error seems to be coming from here - 
path: wp-content\plugins\dokan-lite\includes\REST\ProductController.php
Line: 351 and 325 for Delete Product

**Comment by baochungit** [comment]
I confirm facing this issue as well.

The issue is from the different type between $store_id and $product_author. One is int and one is string.
