### ISSUE TITLE
code rest_forbidden status 401  for /wp-json/dokan/v1/orders

### ISSUE THREAD

**Issue by julio3266** [weDevsOfficial/dokan#1096]
Good afternoon, I'm trying to get the products and orders from a seller, but I'm getting this error.
The error occurs for almost everything except for / stores.
I'm already using basic auth.

[https://i.imgur.com/ByV4cOz.png](url)
[https://i.imgur.com/SxOOgGW.png](url)

**Comment by alamgircsebd** [comment]
This API perfectly working for us, make you have set correct permission. Here have one permission check requested user must have access `dokan_view_order_menu`
