### ISSUE TITLE
Duplicate function values returnd in my_test plugin traced to Dokan-lite.

### ISSUE THREAD

**Issue by ecottles** [weDevsOfficial/dokan#110]
Please remove this issue.  I apologize for the miss-information. Had a long day when I posted this.

Your assistance is much appreciated....

LJC

*****************************************************************************************************
I have a simple my_tests plugin.  The plugin has a single action and  function as follows;
```php
add_action( 'save_post', array($this,'my_tests' ) );

 function my_tests($post_id) {
  if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
            if( ! ( wp_is_post_revision( $post_id) || wp_is_post_autosave( $post_id ) ) ) {  
     $current_user = wp_get_current_user();
     $roles = $current_user->roles;
    
       write_log($current_user->roles);
 }
}
```

Which returns;

```2018/01/03 23:29:13 [error] 1575#0: *60468 FastCGI sent in stderr: "PHP message: Array
(
    [0] => administrator
)

PHP message: Array
(
    [0] => administrator
)" while reading response header from upstream, client: 104.186.231.205, server: cottleweb.com................
```

As you can see the object is returned 2 times.

I have traced it to dokan plugin.
Specifically, 
1.  plugins/dokan-lite/includes/admin-functions.php(608):
2.  plugins/dokan-lite/includes/admin-functions.php(626):

If I comment out line (608)   //dokan_override_product_author( $product, $seller_id );
The function my_tests plugin returns only 1 instance of the object as it should.
This only occurs  using the product editor.

This I came upon while performing optimization tests. I am trying to keep processing to a minimum.

Attached is the my_tests plugin. The error log is Wordpress error log.

Your input and any help is much appreciated. 
[my-tests.zip](https://github.com/weDevsOfficial/dokan/files/1602125/my-tests.zip)

**Comment by saimonh3** [comment]
@ecottles Never mind for the delay. We have fixed the issue. Thanks for reporting the bug.
