### ISSUE TITLE
Store List: Clickable the whole single seller box

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1101]
**Description:**
Currently, only the Store name and the right arrow icon are clickable to visit a store from the store list page.

But it would great if the whole single store box can be clickable to visit a store.

**_Screenshot:_** https://snipboard.io/wYNP3c.jpg

**Comment by alamgircsebd** [comment]
This will be not good full box linked with store page, now we added store url on store name, image and view store button here PR https://github.com/weDevsOfficial/dokan/pull/1136

**Comment by alamgircsebd** [comment]
Resolved and have on released version v3.2.6
