### ISSUE TITLE
Vendor Dashboard: Tracking Number is not being added in the Order Details page

### ISSUE THREAD

**Issue by nawaz0705** [weDevsOfficial/dokan#1111]
**Description of the Bug**

The Tracking Number is not being added on the,
**Vendor Dashboard > Orders > Order Details > Notes Section** and
**Customer Dashboard > Orders > Order Details > Order Updates**

**How to Reproduce:**

1. **Log in** as a Vendor
2. Navigate to the **Orders > Order Details**.
3. Click on the **Tracking Number**.
4. Add the details and click on the **Add Tracking Details** button. 
5. Nothing will happen.

**Expected Behavior**

**Screenshots**
The Tracking ID and details should appear on the Order Details page of the Vendor Dashboard [as shown in this screenshot](https://prnt.sc/10a5ttu). 
It should also appear on the Order Details page of the Customer Dashboard [as shown in this screenshot](https://prnt.sc/10a5v12). 

**System Status:**
 - Dokan Version: v3.2.1
 - Dokan Pro Version: v3.2.0
 - WooCommerce Version: v5.0.0

**Comment by nurul-umbhiya** [comment]
Already fixed.. will be released in next version of dokan lite

**Comment by shohag121** [comment]
Fixed with PR #1102
