### ISSUE TITLE
Static Code Analysis Tool

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1120]
Taking into consideration that Dokan is critical software for e-commerce (entire shops are built on it) and with the abundance of functionality it offers, we need to be 100% sure that no loopholes appear in the code.
In order to prevent this, I suggest that you guys add [CODACY](https://www.codacy.com/) to this repository, as it's free for open source and helps in developing clean code by pointing out issues that can be missed by developers.
It analyzes pretty much everything (PHP, JS, CSS etc.) and offers solutions and suggestions to the detected issues.

**Comment by nurul-umbhiya** [comment]
phpcs is already included via composer, does the same thing actually.
