### ISSUE TITLE
AZERTY keyboard restrict registraion 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#1129]
The AZERTY type keyboard does not allow the user to fill the phone field and the vendors cannot register if they have the AZERTY keyboard : 
https://www.i-sticker.fr/1119-thickbox_default/sticker-conversion-azerty-vers-qwerty-macbook-pro-et-air.jpg

The solution we provide : 

 navigate through WP content > Plugins > Dokan lite > Assets > js > vendor-registration.js, number 75. You need to add the keys here. You need to remove them from line number 87.

On the other hand, you can remove line 11, in the same directory as above, to solve the issue.

**Comment by quentinbc** [comment]
Hello,

You can replace the function "**ensurePhoneNumber**" in vendor-registration.js by this one

```
ensurePhoneNumber: function (e) {
        var validList = [46, 8, 9, 27, 13, 91, 107, 109, 110, 187, 189, 190];
        // Fix Mac Book Pro issue
        validList = navigator.platform.toUpperCase().indexOf('MAC') >= 0 ? validList.concat([48, 49, 50, 51, 52, 53, 54, 55, 56, 57]) : validList;

        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, validList) !== -1 ||

            // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) ||

            // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
        }

        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    },
```
