### ISSUE TITLE
Store opening time/closing time widget

### ISSUE THREAD

**Issue by sabbir1991** [weDevsOfficial/dokan#113]

**Comment by ManigandanRaamanathan** [comment]
How do we access this feature? How do the vendor set the opening and closing time?

**Comment by ManigandanRaamanathan** [comment]
@sabbir1991  @saimonh3  why was this commit removed in the recent release?

**Comment by saimonh3** [comment]
@ManigandanRaamanathan  This feature will be added in the next release. Thanks

**Comment by ManigandanRaamanathan** [comment]
@saimonh3  may i know when you will release new version?

**Comment by ManigandanRaamanathan** [comment]
@saimonh3 will you please add the timing details field within the rest api as well?
