### ISSUE TITLE
Vendor > Add Product: display hierarchical categories in autocomplete (child)

### ISSUE THREAD

**Issue by GuitarKingPaolo** [weDevsOfficial/dokan#1130]
Hi,

the category selection in the vendor dashboard is not very clear..
for example if i have:

Man
-clothing
—-hoodie
Woman
-clothing
—-hoodie
Girl
-clothing
—-hoodie
Boy
-clothing
—-hoodie

if search hoodie in the selection of category it display “clothing-hoodie”.. it is not possible to display the category with all parents ? so the selection for the vednor is more clear.

For example is not possible, when the vendor search by term “hoodie” to show the cateogories like this:

Man->clothing->hoodie
Woman->clothing->hoodie
Girl->Clothing->hoodie
Boy->Clothing->hoodie

**Comment by nurul-umbhiya** [comment]
Already implemented on Dokan Lite
