### ISSUE TITLE
Store listing geolocation, map is not center on location search

### ISSUE THREAD

**Issue by o-Chamie-o** [weDevsOfficial/dokan#1141]
**Describe the bug**
On store listing with géolocation module ON, the location entered in filter area is not the center of the map.

If no store are found, the map wil center not in the address asked in the query, but on the default map setting for all the site.

**To Reproduce**
1. Go to store listing page
2. Search store in a place with no store
3. No store found OK
4. Map is not center on the place in the search

**Expected behavior**
The map should be center accordingly to the search query.

**Screenshots**
![image](https://user-images.githubusercontent.com/16864366/112484091-ec4d9a00-8d79-11eb-935a-748eb70245cf.png)

**Environment:**
 - Dokan Version: v3.2.3
 - Dokan Pro Version: v3.2.1
 - WooCommerce Version: v5.1.0
 - Browser: Brave
 - Current Theme: Divi

**Comment by alamgircsebd** [comment]
We have checked this issue and it working perfectly
![Screenshot (14)](https://user-images.githubusercontent.com/25417335/113088707-0408a080-9208-11eb-848f-2b0a6445b16b.png)

**Comment by o-Chamie-o** [comment]
Thanks for your reply.

Can you please explain why my map center on store default location instead of search location?

I'll double check,

**Comment by o-Chamie-o** [comment]
Oh it's working with google map (according to your screenshot)

We are using MapBox, can you confirm this is the same behavior with MapBox, please?

**Comment by o-Chamie-o** [comment]
@alamgircsebd bump

**Comment by alamgircsebd** [comment]
we working on it, when done you will get notification

**Comment by o-Chamie-o** [comment]
@alamgircsebd any news by chance?

**Comment by o-Chamie-o** [comment]
> we working on it, when done you will get notification

Can you re-open this issue? or should I create a new one ?

**Comment by o-Chamie-o** [comment]
bump. :)

**Comment by o-Chamie-o** [comment]
Bump
