### ISSUE TITLE
Get Support Button

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1144]
Please note that the **Get Support** button is missing from the actual order details page.
This is the perfect spot to add it, as it will be easy for the customer to ask for help in case he has any issues with his order and also the order ID/details are in front of him.

![support](https://user-images.githubusercontent.com/3336728/112684181-500bbc00-8e7b-11eb-956d-843f06586e64.png)

**Comment by alamgircsebd** [comment]
Have pr on dokan pro https://github.com/weDevsOfficial/dokan-pro/pull/1192
