### ISSUE TITLE
Hide Customer Info

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1146]
In the **Selling Options** Dokan has a setting `Hide customer information from order details of vendors`.
This is nice, however it should be a little more modular, in the sense that the Phone Number and the Name are needed sometimes when the vendor needs to verify the order details with the customer.
![info](https://user-images.githubusercontent.com/3336728/112760593-3ba4fc00-9000-11eb-8ebf-2eefb740669e.png)

I'll give you an example from my recent experience. 
I have a store on a popular marketplace in my country and a rival seller, in an attempt to destroy our company, made 76 COD orders in 48 hours, with fake accounts and using names and phone numbers found online.
We've managed to find out by actually calling some of the numbers and by Googling them.

My point is that the only truly private information is the **email** and the **IP**.
The name and phone number can be displayed for verification and separate/external invoicing purposes (in case the vendor generates an invoice using external software).

**Comment by alamgircsebd** [comment]
Dokan have already like this option, go here WP Admin Dokan->Selling Options tab and search `Hide customer information from order details of vendors` and enabled it. Now vendors can't see any customer info on order details page also can't see from order new emails. 
![Screenshot (15)](https://user-images.githubusercontent.com/25417335/113089440-7a59d280-9209-11eb-829e-5b48375b75d1.png)
![Screenshot (16)](https://user-images.githubusercontent.com/25417335/113089491-91002980-9209-11eb-8f61-739a1a376842.png)
