### ISSUE TITLE
Fatal Error in Tickets

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1147]
I've noticed that when opening this ticket on your demo, it returns an error: https://dokan.wedevsdemos.com/my-account/support-tickets/1829/

![error](https://user-images.githubusercontent.com/3336728/112761025-d94cfb00-9001-11eb-8efa-b624694d7cef.png)

It should be investigated as there might be something more serious behind it.

**Comment by alamgircsebd** [comment]
This issues already resolved, please update your dokan pro plugin with latest version v3.2.1

**Comment by alamgircsebd** [comment]
We have fixed this issue on our demo location
