### ISSUE TITLE
Sub order currency not change  when parent order currency changed. 

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#1152]
Hi, I am using [WOOCS ](https://currency-switcher.com/) with Dokan. A customer placed an order in Euro but when I changed the parent order currency to  USD it did not reflect on suborders. 

Our Base currency is GBP.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place an order in any currency other than the base currency from multiple vendors. 
2. Change the currency from the backend
3. Parent currency changed but sub order currency not chnaged.

**Expected behaviour**
Suborder currency should also change. 

**Screenshots**
http://prntscr.com/110lggp

**Comment by alamgircsebd** [comment]
Currently dokan not supporting with WOOCS plugin, please follow this gist https://gist.github.com/alamgircsebd/3d721ee96020f39a8818c552016f3ac6
