### ISSUE TITLE
Limit number of orders by IP

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1153]
Many marketplaces get hit frequently by bots and bad users, that place fake orders with the intent of creating bad business for Vendors and Admins.

While searching online for a solution to this issue, I found a nice piece of code that limits the number of orders that can be placed in 24 hours from the same IP - https://stackoverflow.com/questions/53852696/limit-woocommerce-orders-by-ip/53859074#53859074
It would be nice if in **Dokan > Settings > Selling Options**  we could have a setting where the admin can enable this feature and add the number of orders he allows to be placed from the same IP address.

Thanks!

**Comment by shohag121** [comment]
We will not include this under Dokan core as no one else requested for this. The example you've provided will work perfectly for your mentioned use case. Kindly manually add this code snippet in your (child) themes functions.php file.
