### ISSUE TITLE
Suggestion regarding attribute selection

### ISSUE THREAD

**Issue by shawon786** [weDevsOfficial/dokan#116]
Hello,
Imagine that my store will have a preset list of colors and sizes that the vendors can pick from. I'm concerned that when the vendor selects a custom attribute, dokan displays all available attributes and then the vendor has to remove the options they do not want. There could be 30 colors automatically selected but the vendor only needed 2 colors. It creates extra work and wastes the time of the vendors. 

I understand it is difficult to make the front end experience work but I think this is bad usability. The vendor should see a drop down with all the available options and be able to select the options (colors) they want just like it works in the backend product editor.

**Comment by sabbir1991** [comment]
It's done already
