### ISSUE TITLE
Show-Sort Vendors by IP Address

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1160]
Please note that right now, Dokan is missing an important feature for protecting the marketplace from bad/spammy vendors.
The logic behind this, is that a vendor could register multiple accounts in order to create a monopoly on the marketplace.
He will then start having [Anti-competitive practices](https://en.wikipedia.org/wiki/Anti-competitive_practices) against the other sellers.

One easy way to protect against this, is to store the vendor IP each time he interacts with the website, then output it in the Dokan Vendors list for the admin to see.
Also, the Admin should be able to search/sort the vendors using the IP address also (when he clicks on the IP address, all vendors with that IP should show up).

![vendor_ip](https://user-images.githubusercontent.com/3336728/113413533-94d7ab80-93c3-11eb-96e6-6faabca1adce.png)

**Comment by Tangol** [comment]
This works hand-in-hand with https://github.com/weDevsOfficial/dokan/issues/1153 , both making Dokan a safer place for vendors and customers.

**Comment by MercanoG** [comment]
Nice one! Hope it gets implemented.

**Comment by nurul-umbhiya** [comment]
To verify a vendor, you can get help from the Seller Verification module, besides, we are including the company verification feature for the Seller Verification module. I'm closing this issue for now.

**Comment by Tangol** [comment]
@nurul-umbhiya I'm working for a major European Marketplace, and we have vendors that create 2-3 different companies, register with them, and list the same products on **Single Product Multiple Vendor** in order to manipulate the prices and take down other legit sellers (companies).
This is illegal and without sorting/viewing the **IP**, we can't filter the bad ones.
