### ISSUE TITLE
Vendor Dashboard - Company Verification

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1166]
Please note that currently, Dokan doesn't provide any method of verifying business users/vendors.
We just have **ID Verification**, **Address Verification** and **Social Profiles** which are all related to personal information.

![company](https://user-images.githubusercontent.com/3336728/113853855-d5aa3880-97a6-11eb-81b5-5141563e1893.png)

We need another field here for **Company Verification** where the the vendor can upload his Company ID, VAT Declaration and Bank IBAN. These 3 are mandatory.
The upload form should accept both JPG and PDF files.
This is very important in EU countries, as the marketplace needs to sign a contract with the Vendor.

Thanks!

**Comment by nurul-umbhiya** [comment]
@xaviranik kindly take care of this issue if you are free.
