### ISSUE TITLE
dokan_get_store_url is returning a malformed URL if home_url is filtered and adds a query parameter

### ISSUE THREAD

**Issue by strategio** [weDevsOfficial/dokan#1170]
**Describe the bug**
This is issue is reproducing with WPML using the "Language URL format" set as "Language name added as a parameter".
In that context, WPML is adding a query parameter to the home URL.

e.g.
default lang => https://example.com
secondary lang => https://example.com/?lang=fr

In the function `dokan_get_store_url`, the concatenation does not allow full compatibility.

**To Reproduce** (simplified steps to show the concept)
1. Add the following filter:
```php
add_filter( 'home_url', function( $url ) {
    return add_query_arg( 'foo', 'bar', $url );
};
```
2. Visit the stores list
=> The store links are malformed, like https://example.com/store?foo=bar/doe-goods/

**Expected behavior**
We should get https://example.com/store/doe-goods?foo=bar instead.

**Environment (please complete the following information):**
 - Dokan Version: 3.2.4

**Additional context**
I found this issue while I was fixing https://github.com/weDevsOfficial/dokan-wpml/pull/14.

**Comment by strategio** [comment]
Hi, please check my fix suggestion in https://github.com/weDevsOfficial/dokan/pull/1171.

**Comment by nurul-umbhiya** [comment]
Merged
