### ISSUE TITLE
dokan_get_navigation_url is returning a malformed URL if 'page_link' is filtered and adds a query parameter

### ISSUE THREAD

**Issue by strategio** [weDevsOfficial/dokan#1172]
**Describe the bug**
This is issue is reproducing with WPML using the "Language URL format" set as "Language name added as a parameter".
In that context, WPML is adding a query parameter to the home URL.

e.g.
default lang => https://example.com
secondary lang => https://example.com/?lang=fr

In the function `dokan_get_navigation_url`, the concatenation does not allow full compatibility.

**To Reproduce** (simplified steps to show the concept)
1. Add the following filter:
```php
add_filter( 'page_link', function( $url ) {
	return add_query_arg( 'foo', 'bar', $url );
} );
```
2. Visit the vendor dashboard
=> The "products" link in the left sidebar is malformed, like https://example.com/dashboard/?foo=barproducts/

**Expected behavior**
We should get https://example.com/dashboard/products/?foo=bar instead.

**Environment (please complete the following information):**
 - Dokan Version: 3.2.4

**Additional context**
I found this issue while I was checking https://github.com/weDevsOfficial/dokan-wpml/issues/11.

**Comment by strategio** [comment]
Please check my fix suggestion in https://github.com/weDevsOfficial/dokan/pull/1173.

**Comment by nurul-umbhiya** [comment]
Merged
