### ISSUE TITLE
Dokan Vendor Completed Order email template can not be overridden

### ISSUE THREAD

**Issue by nawaz0705** [weDevsOfficial/dokan#1181]
**Description of the Bug:**
The **_Dokan Vendor Completed Order_** email template can not be overridden using Child Theme.
I am using the **Dokan Theme** and below is the file path I followed to override the email template,
File Path: **wp-content > themes > dokan > woocommerce > emails > vendor-completed-order.php**

**How to Reproduce:**
1. Override the **_Dokan Vendor Completed Order_** email template
2. log in as a Vendor
3. Navigate to Orders
4. Change the status of any order to **Complete**
5. Now check the email received by the Vendor
6. You will see that the **_Dokan Vendor Completed Order_** email template has not been overridden.

**Expected Behavior:**
We should be able to override the **_Dokan Vendor Completed Order_** email template. 

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
WordPress: 5.7.1
WooCommerce: 5.2.2

**Comment by shohag121** [comment]
Hello @nawaz0705 Bhai,

By default, WC copy email templates in `your-theme/woocommerce/email/` directory but for overriding **dokan's** email templates we need to copy the email templates in `your-theme/dokan/email/`.

Hope this clarifies the misunderstanding. Please contact me if you need any additional information.

Thanks.
