### ISSUE TITLE
Earning column in the Orders listing page of the Vendor Dashboard is not exported

### ISSUE THREAD

**Issue by nawaz0705** [weDevsOfficial/dokan#1187]
**Description of the Bug:**
When a Vendor exports Orders from his dashboard, the **Earning** column is not exported. 

**How to Reproduce:**
1. log in as a Vendor
2. Navigate to **Orders**
3. Click on **Export All**
4. Now open the exported **.csv file**. 
5. You will see that the **Earning** column is not available. 

**Expected Behavior:**
For a Vendor, the **Earning** column is important and it should be a part of the exported **.csv file**. 

**System Status:**
Dokan Lite: 3.2.4
Dokan Pro: 3.2.2
WordPress: 5.7.1

**Comment by alamgircsebd** [comment]
Resolved already
