### ISSUE TITLE
REST API: Update store settings route not found

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#1192]
**Describe the bug**
There is no endpoint available to update the store settings via REST API. The documentation also does not include the PUT method: https://wedevsofficial.github.io/dokan/#update-settings

**To Reproduce**
1. Make a PUT request using this endpoint: **/wp-json/dokan/v1/settings**
2. The result is like this: 
`{
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method.",
    "data": {
        "status": 404
    }
}`

**Expected behavior**
REST API endpoint should update the information in the store settings.

**Reported Here**
https://wordpress.org/support/topic/rest-no-route-in-put-settings/

**Environment (please complete the following information):**
Dokan Version: 3.2.5
Dokan Pro Version: 3.2.3
WooCommerce Version: 5.2.2

**Comment by HusamoBinAref** [comment]
to solution this :
goto file rest in yoursite for dokan :
get path file In  
 yourplay/wp-content/plugin/dokan-lite/includes/REST/StoreSettingController.php
 
 and add this function to update:




    public function update_settings( $request ) {  
    $store_name= $request->get_param( 'store_name' );
     $vendor = $this->get_vendor();
        if ( is_wp_error( $vendor ) ) {
            return $vendor;
        }
         else
         {
         $response1 = dokan_get_store_info( $vendor->id );
         $response1['store_name']  =$store_name;

    $response = dokan()->vendor->update( $vendor->id,  $request);

        return rest_ensure_response( $response );
        }
    }

`register_rest_route(
            $this->namespace, '/' . $this->rest_base , [
				[
					'methods'             => WP_REST_Server::EDITABLE,
					'callback'            => [ $this, 'update_settings' ],
					
					
                    
					'permission_callback' => [ $this, 'get_settings_permission_callback' ],
				],
			]
        );`



see full code  :
https://github.com/HusamoBinAref/dokan-setting/blob/main/StoreSettingController.php


good lock

**Comment by alamgircsebd** [comment]
Resolved
