### ISSUE TITLE
Product visibility catalog mode is not working

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#1196]
**Describe the bug**
If you select catalog mode in the product's other options > visibility the "Add to cart" button does not go away

**To Reproduce**
1. Go to Vendor dashboard > Products > Edit a product
2. Select "Catalog" on Other options > Visibility
3. Save & view the product
4. It will still show the "Add to cart" button

**Expected behavior**
Catalog mode should not show the "Add to cart" button.

**Screenshots**
https://prnt.sc/12o7pcr

**Environment (please complete the following information):**
Dokan Version: 3.2.5
Dokan Pro Version: 3.2.3
WooCommerce Version: 5.2.2

**Comment by shohag121** [comment]
Hello @rashedripon,

We are miss understanding the product visibility catalog mode.
Please check the attached video ( https://youtu.be/MwbacHBOtGg ).

Please let me know if any additional information is needed.
Thanks.
