### ISSUE TITLE
Store Reviews - Star rating display issue

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1200]
Please note that there's an issue in `/wp-admin/admin.php?page=dokan#/store-reviews` when displaying the star ratings for vendors.

![ratings](https://user-images.githubusercontent.com/3336728/117794432-e80c0c00-b255-11eb-93f9-ba19bc4d92a9.png)

As you can see, the stars are misaligned and break their container box.

**Comment by alamgircsebd** [comment]
Hello @Tangol 

We have checked this issue, it working fine. May be your site have any conflicting issue with some others scripts, please submit a ticketed to support team with your site access details we will check it. 

Thanks 

![Screenshot (38)](https://user-images.githubusercontent.com/25417335/118755554-e44a3c00-b88a-11eb-943c-fc1280085381.png)

**Comment by Tangol** [comment]
The screenshot is from your own Demo https://dokan.wedevsdemos.com/wp-admin/admin.php?page=dokan#/store-reviews

**Comment by alamgircsebd** [comment]
> The screenshot I posted is from your own Demo https://dokan.wedevsdemos.com/wp-admin/admin.php?page=dokan#/store-reviews

ok, we will fix it on our demo location, thanks
