### ISSUE TITLE
DELETE is "forced" on API even with param described as default to false

### ISSUE THREAD

**Issue by mariovalney** [weDevsOfficial/dokan#1202]
**Is your feature request related to a problem? Please describe.**

There is no information about "force" param on DELETE in products [on documentation](https://wedevsofficial.github.io/dokan/#delete-a-product). Said that, WooCommerce API Rest provide us this feature and the Dokan REST registration has this parameter too ([here](https://github.com/weDevsOfficial/dokan/blob/develop/includes/REST/ProductController.php#L103)).

But in the abstract class **delete_item** method [forces the deletion](https://github.com/weDevsOfficial/dokan/blob/develop/includes/Abstracts/DokanRESTController.php#L187).

I'm not sure this is a feature request or a bug (as the param is registered).

**Describe the solution you'd like**

The force param should be accepted.
Maybe true as default to backward compatibility.

**Describe alternatives you've considered**

There is no alternative.

**Additional context**

There is no additional context.

**Comment by nurul-umbhiya** [comment]
@mariovalney I've checked your pr and we will merge this or in the next release of Dokan Lite.
