### ISSUE TITLE
Tooltips showing wrong

### ISSUE THREAD

**Issue by AmahAjavon** [weDevsOfficial/dokan#1204]
This could be a css issue but the tooltip are all off, I have added a screenshot

<img width="442" alt="Screen Shot 2021-05-12 at 9 59 13 PM" src="https://user-images.githubusercontent.com/10400673/118080019-285ead80-b36e-11eb-92df-dfd6b1e75e8b.png">

**Environment**
 - Dokan Version: v3.2.6
 - Dokan Pro Version: v3.2.5
 - WooCommerce Version: v5.3.0
 - Browser chrome
 - Current Theme: Astra pro

**Comment by alamgircsebd** [comment]
Hello @AmahAjavon 

We have checked this issue with Astra theme, it look fine. If you still getting the issue please submit a ticket to support team. We will check it directly on your site. 

Thanks

<img width="834" alt="Screen Shot 2021-05-19 at 9 59 16 AM" src="https://user-images.githubusercontent.com/25417335/118754577-2ecab900-b889-11eb-8e1d-e03b7e332a28.png">
