### ISSUE TITLE
Please add split cart per vendor feature.

### ISSUE THREAD

**Issue by erikdemarco** [weDevsOfficial/dokan#1211]
I love dokan very much.
But currently dokan's single vendor feature feels so useless and its gives user very very bad experience.
Imagine you add a product to cart. But then you dont want to buy this product. Instead you add another product but gets a warning message. User will confuse how to buy the other product. Not all user is smart. The basic rule for UX is make it as simple as possible for the user.

If we compare dokan's single vendor and webkul's split cart feature. Dokan's will make conversion rate so low. And Webkul's feature is like etsy's checkout experience, which is very good.

See this image for exlaination:

[https://i.stack.imgur.com/1dvHL.png](https://i.stack.imgur.com/1dvHL.png)

The idea is very very simple (I also bought webkul's version, the plugin is only 25kb in size):
Use custom 'cart' template, loop for each vendor. And for each checkout button, it adds "product_ids" parameters which will be sent to checkout page. And in checkout page it will read that params and reset the cart to add all of this product_ids programatically. when loading other page, the cart session restored to original.

So the implementation is far more easier than split order. So split order require much more programming code. And more prone to error when woocommerce change something in the order process.

**Comment by XTard** [comment]
Hi, what is the status on this feature? Other marketplaces have this feature.

**Comment by nurul-umbhiya** [comment]
The current implementation was based on user feedback. If you want, you can enable Single Seller Mode. However, if you need multicart system like webkul, you can ask for customization support from [weLab](https://wedevs.com/welab/).
