### ISSUE TITLE
Cash On Delivery deduct Withdrawal balance

### ISSUE THREAD

**Issue by vincebuck** [weDevsOfficial/dokan#1220]
Hi Guys,

I am searching for a way to implenent reverse withdrawal in Dokan (as WCFM already has). I mean it would be great to setup a store with this plugin , but if I let sellers accept cash or cash on delivery , it calculates the commission and deducts the commission from the withdrawal balance. 
f.e : seller gets a order for 100$ andmy commission is 5% so i take 5$. Yet the buyer paid the vendor with cash and I want that the vendor balance will be -5 not 0. Is that possible and has anybody a code for that or is it in the pro features and I just overlooked it?

Greets Vince

WCFM example: https://wclovers.com/knowledgebase/wcfm-marketplace-reverse-withdrawal/

**Comment by Tangol** [comment]
Related to https://github.com/weDevsOfficial/dokan/issues/34

**Comment by nurul-umbhiya** [comment]
alrerady fixed
