### ISSUE TITLE
Sub order not showing if its in Custom Order Status Dokan

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#1222]
Custom order status are not showing on parent order details page where customer see the sub orders for Customers.

Lets Say 423822 parent order and 423823 and 423824 is sub order.

If I visit the URL I will not see any sub order because all are in a custom status ( pending-approval ) https://www.abc.com/my-account/view-order/423822/

Sol:
Add filter to this function  http://prntscr.com/13yg5vk

`dokan_order_show_suborders()`

**Comment by alamgircsebd** [comment]
We have fixed this issue on our Dokan Lite v3.2.6 

Please update your plugin it will be resolve. 

Thanks!
