### ISSUE TITLE
Vendor Dashboard - View Product

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1224]
When clicking on view product in the vendor dashboard, the link opens in the same tab and this is bad for usability, as a vendor could have hundreds of products that he wants to quickly check.

So to fix this, the **View** link should have the `target="_blank"` attribute, that will open it in a new tab for faster viewing.

![view](https://user-images.githubusercontent.com/3336728/120901948-499d7b80-c646-11eb-8ab8-a7fd4528a2b7.png)

It's the same for viewing the permalink when editing the product. It should open in a new tab.

![perma](https://user-images.githubusercontent.com/3336728/120902412-f1b44400-c648-11eb-95f0-87f6643f308c.png)

**Comment by alamgircsebd** [comment]
Have this fix on this PR https://github.com/weDevsOfficial/dokan/pull/1223

**Comment by tareq1988** [comment]
We won't be adding support for this.

**Comment by Tangol** [comment]
@tareq1988 any reason for this?
A few years ago I worked at Amazon North America support, and everything in the backend was opening in new tabs in order to prevent losing page changes by wrong clicking, and also to speed up the viewing/checking of stuff.

**Comment by tareq1988** [comment]
I appreciate your thoughts and feedback, but you were the first person to request this feature. From the beginning it was like this, so until we get enough requests, we will not be adding the support as already most of the users are familiar with the current system.

**Comment by Tangol** [comment]
Thanks for the clarification.
And a big thank you to @alamgircsebd for https://github.com/weDevsOfficial/dokan/pull/1223/commits/785b2a9416c3ce1cd2224368f72115c520ebe885 as who needs it, can use this code.
