### ISSUE TITLE
Missing confirmation when adding a product

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1225]
When adding a product using the **Product Popup**, you don't get any confirmation that the product was added successfully.

![confirmation](https://user-images.githubusercontent.com/3336728/120902142-68e8d880-c647-11eb-84b4-1d692ee70815.png)

You should see something like this, somewhere inside the popup:
![edit](https://user-images.githubusercontent.com/3336728/120902150-756d3100-c647-11eb-8602-a1899ef2e916.png)

**Comment by alamgircsebd** [comment]
Resolved already and released on v3.2.8
