### ISSUE TITLE
Issue while the vendor is going to create a tag which is existing with a different case

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1227]
**Describe the bug**
If the vendors are given the ability to create tags and if there is a tag already existing like "test" and the vendor wants to create another tag "Test" then both the options are being shown in the dropdown. If the vendor chooses the option that was just typed (Test) instead of the existing one (test) then the system does not save the tag.

**Video URL:** https://www.loom.com/share/ce9d970b495c46bd814017449eef8ca5

**To Reproduce**

1. Provide the ability to the vendors to create tags from their vendor dashboard.
2. Go to the vendor dashboard and click on **add new product**.
3. Write an existing tag with a different case. For example, if there is a tag already existing like "**test**" then write "**Test**" in the tag field.
4. There will be two options to choose from the dropdown list. Choose the one you have just typed. In this case, choose "**Test**"
5. Click on **Create product** and there will be no tags available on the edit product page of that product.

**Expected behavior**
I think it will be better if we show only the existing tag if the user types any existing tag using a different case.

**Environment (please complete the following information):**
Dokan Lite: v3.2.6
Dokan Pro: v3.2.5
WordPress: v5.7.2
WooCommerce: v5.3.0

**Comment by alamgircsebd** [comment]
We have checked the issue on our locally we see it correctly working, maybe you getting the issue with style conflicting, can you open a ticket to our support team with your site details, we will check it. 
![Screenshot (42)](https://user-images.githubusercontent.com/25417335/121161751-1ee23b80-c86f-11eb-92aa-bf750f051fc5.png)

**Comment by Tangol** [comment]
> **Expected behavior**
> I think it will be better if we show only the existing tag if the user types any existing tag using a different case.

I agree with this solution.
Doing this, will prevent the addition of thousands of duplicate tags that are useless.

If we have an existing tag named **test**, all other user typed tags independent of their form (**TEST** or **Test** or **teSt** etc.) should be associated to the existing one.
So basically if **test** exists, if the user enters **TEST**, then the existing **test** will show up.

@alamgircsebd  The issue:
At the moment, even if the **test** tag exists, if the user types **tEst**, **TEST** etc., then a new tag gets shown/created.
So the script doesn't query correctly the database. If the word contains an uppercase letter, it assumes that it's a new word.

Hope it makes sense now.

**Comment by J-H-Mojumder** [comment]
I believe this is not a conflict issue as I have already tested it on multiple environments and found the same result. In your case, as you have already got a tag named **Tag1**, if you type another tag named **TAG1** or **TaG1** then the system will show the same result as mine.

I think the query is being done without case sensitivity. But my suggested solution can be if the query finds out even a single row as a search result then it can skip showing the typed one as an option and will show only the previously saved one.

**Comment by alamgircsebd** [comment]
Thanks @J-H-Mojumder and @Tangol for clarify the issue, we have fixed the issue, hope by our next release have this fixes.
