### ISSUE TITLE
Order Filter also by Customer Phone Number

### ISSUE THREAD

**Issue by Tangol** [weDevsOfficial/dokan#1240]
Please note that besides customer **Name** and **Email**, we also need **Phone Number** filtering in the orders section.

![phone](https://user-images.githubusercontent.com/3336728/121519585-8d073980-c9fa-11eb-8c42-bd975aec0373.png)

The whole idea behind this, is related to the fact that sometimes we get calls from difficult customers and before answering/calling back, we need to first check if they have an existing order with us, so that we can prepare a speech.
This helps in preventing cases when the support team gets caught off-guard by tricky questions and also eases the customer identification by caller ID.

PS: the search should strip any special characters (+ / - spaces), so it shouldn't take into consideration if there's a `+` in the number or `spaces`.
So if the customer has a number like `+88 01531549617`, if you enter in the search box just `880` the search should return all customers with phone numbers that start with `880` (including `+88 0`).

Thanks!

**Comment by nurul-umbhiya** [comment]
Since we have a filtering feature by the customer, we are not considering this feature to include as a core feature. If you still need this feature kindly ask for customization support from [weLab](https://wedevs.com/welab/)
