### ISSUE TITLE
Dokan Banner image resulting not found when use aws s3 as image provider WP Offload Media Lite

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#1243]
We are using aws s3 as image provider. When updating image form Settings page and upload and crop and image the it generates a new cropped image but the url returns the website URL which is invalid.

1. Dashboard http://i.prntscr.com/1hE2Aay5SA2Ze2VzR_j8NQ.png
2. Request When Cropping: http://i.prntscr.com/0B2CPkqVT_WNqqnkhqJDAA.png
3. Code that generating the URL : http://i.prntscr.com/AXYFvPi9Tv_tyZKm723uXw.png
4. In media library URL is different http://i.prntscr.com/QkBlGYaJQB_PXiSZObzIcQ.png
5. When I use `wp_get_attachment_url`  outside code it returns the aws s3 url but insde code it returns local website url

Plugin Used: WP Offload Media Lite

**Comment by rajankarmakar** [comment]
This issue is tested and everything is alright. We used the same plugin as yours (WP Offload Media Lite).
See the test result [here](https://prnt.sc/1re1drp).

**Comment by royrakesh** [comment]
Hi @rajankarmakar do you get the URL after reload or when its cropping and just added? 
Can you post loom video.

**Comment by royrakesh** [comment]
Hi
We are on the same page
You are getting this because you have disabled this option http://prntscr.com/1rkzluo
When you upload the image, it is first uploaded into your site then copied to aws s3.
Currently you are keeping 2 copies of your image which is bad if you have 100000+ products in your store.

**Comment by rajankarmakar** [comment]
Hi @royrakesh,

I have missed telling you about my settings. I had set up the settings and tested as you mentioned with the screenshot. Check out my settings from [here](https://prnt.sc/1s1216o).

**Comment by royrakesh** [comment]
Hmm
I don't know why it is happening with our site.
Tested with staging also same issue.
Then we used a filter to bypass the file delete for the banner image upload and it worked. 

Thanks for comment.
