### ISSUE TITLE
expandable product category list

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1244]
when we have a very long product category list ( 50+) which combine with multi-level category, it's becoming very inconvenience for vendor to read through the whole list from the small dropdown box to find out what they need,  [https://imgur.com/a/H8LZzoT](url) and they need to read through the list again and again to add multi-category for their product. the current simple list is ok for some simple site, but not for the medium/big size marketplace. by having the expandable category list will make the user experience much better.

**Comment by Tangol** [comment]
The only way to cleanly implement this is by having an add product wizard like [these guys](http://wcmpdemos.com/all-in-one-demo/vendor_dashboard/add-product/) implemented.

![wizard](https://user-images.githubusercontent.com/3336728/122828949-fdf9fb80-d2ee-11eb-87a4-ed8c7ae56117.png)

This is the most beautiful and convenient way of adding a product, I've ever experienced on any marketplace.
And it also fixes my other report regarding the search for existing products before adding a new one: https://github.com/weDevsOfficial/dokan/issues/1154

**Comment by shahadat015** [comment]
Hi @leew999,

Thanks for your suggestion. You can search for your desired category and select that category. Here I have added a [screen record](https://drive.google.com/file/d/1LqKcYvm2C-V2_WhstIXKgPCHsEPDgHPF/view?usp=sharing).

**Comment by leew999** [comment]
Hi @shahadat015 , Thanks, what you suggested is fine for admin who can search the keywords, but as a vendor, they don't know what's included in the category list, so mostly they will look through the whole list to findout what's included, so its a bad experience for the vendor, especially when they are more than 50 categories, its a super long/narrow list that showing on the screen which is difficult to work with.
