### ISSUE TITLE
[Stuck] In lite mode i am unable to grant selling access to vendor

### ISSUE THREAD

**Issue by themakerman** [weDevsOfficial/dokan#128]
I wanted to try out dokan and so used lite version but seems like i am stuck. Plz fix the issue or is it that in lite mode you cannot approve vendors of selling and creating products??

**Comment by nayemDevs** [comment]
Hello @themakerman,

I am sorry for the delay. In dokan-lite you can easily add vendor and enable his permission to upload product. After registering as a vendor, you have to enable his adding product permission from wp-admin -> User -> Edit user -> "Enable Adding product" option. After enabling adding product permission, the vendor would be able to upload product.
