### ISSUE TITLE
Customize Store Page for every vendor

### ISSUE THREAD

**Issue by themakerman** [weDevsOfficial/dokan#129]
Hi, I want to follow latest design trends for every vendor page on the front end so users can have immersive user experience. I don't want to use the facebook style cover image which dokan provides by default for every vendors store page.

Is this achievable? I would only buy it if it is possible. Thanks.

**Comment by sabbir1991** [comment]
For this feature, we have Dokan Elementor module to customize store page from the admin panel. But for individual vendors, this customization is not possible.
