### ISSUE TITLE
 when suborder is created, vendor is not getting shipping cost.

### ISSUE THREAD

**Issue by hafiza1234** [weDevsOfficial/dokan#1310]
**Describe The Bug:**
when customer purchase product from multiple vendors, vendor is not getting shipping cost.

**How To Reproduced:**
1. Go to dokan -> settings ->selling options.
2. Admin set shipping fee recipient as vendor.
3. Then customer purchase product from multiple vendors.

**Expected Result**: For example, one vendor purchase product cost at $500 and another vendor purchase product cost at $200 . Ship cost $5.Total cost at$705. One vendor will get $502.50 and another vendor will get $202.50
**Actual Result**:  vendor is not getting shipping cost.

**Attachment:**
Video link: https://www.loom.com/share/9615a00246ac401cabbfdaf8a6961545

**Bug Type**: Functional
**Dokan Version**: 3.2.10
**Dokan Pro**: Deactivate
**WooCommerce Version**: 5.6.0
**Browser**: Chrome,Firefox
**Priority** :High.

**Comment by nurul-umbhiya** [comment]
Related Issue: https://github.com/weDevsOfficial/dokan/issues/1288
