### ISSUE TITLE
Changing image sizes on Vendor profile page

### ISSUE THREAD

**Issue by oliviertassinari** [weDevsOfficial/dokan#1323]
**Is your feature request related to a problem? Please describe.**

We are using Dokan as a headless API. We are rendering the vendor's profile page on a custom React page. The generated image is 150x150 which means that, at most, we can render it in a 75x75 container. Otherwise, it looks blurry on any high-resolution screens, e.g. all the Apple products.

Burry: ⬇️ it looks unprofessional

<img width="606" alt="Screenshot 2021-09-07 at 22 55 21" src="https://user-images.githubusercontent.com/3165635/132409666-c0a5c1cc-e003-48e7-9905-02c8e62452d1.png">

https://mui.com/store/contributors/minimal/

**Describe the solution you'd like**

I would like an option to skip the image cropping.

<img width="294" alt="Screenshot 2021-09-07 at 22 56 37" src="https://user-images.githubusercontent.com/3165635/132409787-c6e3925b-502c-4520-8c59-7a776a82c630.png">

**Describe alternatives you've considered**

A new setting option 

**Additional context**

This is a follow-up on https://wordpress.org/support/topic/changing-image-sizes-on-vendor-profile-page/.

**Comment by shohag121** [comment]
Hi @oliviertassinari,

Currently, Dokan suggests store profile picture to be 150x150px and display a button to crop the image but if the provided image resolution is higher than 150x150 and the Vendor sets a cropping rectangle to cover hole image, the avatar or profile picture size will be the actual cropped image size (bigger than 150x150).

API response for store information includes this bigger-sized avatar image URL also.

Hope this clears the confusion.

Thanks.

**Comment by oliviertassinari** [comment]
> Vendor sets a cropping rectangle to cover hole image, the avatar or profile picture size will be the actual cropped image size (bigger than 150x150).

The vendor can't set a cropping rectangle to cover the hole image, it's will always be cropped to 150x150.

> API response for store information includes this bigger-sized avatar image URL also.

It returns the cropped version, e.g. https://oliviert.sg-host.com/wp-json/dokan/v1/stores?per_page=100

**Comment by devAsadNur** [comment]
> The vendor can't set a cropping rectangle to cover the hole image, it's will always be cropped to 150x150.

The image only supports 1:1 square aspect ratio cropping, as it's a store profile picture. But the image is not cropped to 150x150. Please take a look at this [screen record](https://www.loom.com/share/e79731f38ddc4541bff8ff12d4151661). 

> It returns the cropped version, e.g. https://oliviert.sg-host.com/wp-json/dokan/v1/stores?per_page=100

Yes, the API returns the cropped version of the image. But it's not 150x150. I showed this also in the above video.

Hope this clears the confusion. Feel free to let us know if you have any other queries.

Thanks.
