### ISSUE TITLE
There is no required product price field creation , Price field should be required.

### ISSUE THREAD

**Issue by hafiza1234** [weDevsOfficial/dokan#1324]
**Describe the Bug:** 
vendor create a new product without price.

**How to Reproduce:**
1. Go to vendor dashboard.
2. create product without price.

**Attachment:**
video link:https://www.loom.com/share/44917a90683a4672995564edb72582dd

**Actual Result**: Without price product successfully added.

**Expected Result:** product not be added it will show error message.

**Bug type**: Functional
**Dokan Version**: 3.2.11
**Dokan pro Version**: 3.3.6
**WooCommerce Version:** 5.6.0
**Wordpress Version**: 5.8.1

**Comment by Tangol** [comment]
Related to https://github.com/weDevsOfficial/dokan/issues/1258
Some other important fields are also missing required status.

**Comment by nurul-umbhiya** [comment]
closing duplicate entries
