### ISSUE TITLE
email address is showing when email checkbox is disable from vendor settings

### ISSUE THREAD

**Issue by hafiza1234** [weDevsOfficial/dokan#1332]
**Describe the bug:**
Email address is showing when email checkbox is disable from vendor settings
**How to Reproduce:**
1.Go to vendor dashboard.
2.click on settings.
2.disable email checkbox.

**Attachment:**
**Vedio link**:https://www.loom.com/share/e8670ca189bd4295b47bbbb0cf552225

**Expected Result**: email address will not be showing
**Actual Result** : showing email address in store

**Bug Type**: Functional
**Dokan Version**: 3.2.11
**Dokan Pro**: Deactivate
**WooCommerce Version:** 5.6.0
**Browser:** Chrome,Firefox

**Comment by shahadat015** [comment]
I have checked this issue but could not reproduce it. I added a [screen record](https://drive.google.com/file/d/1a4nJSEM1pM4OXk3Oe8WW78Q__KITfTos/view?usp=sharing).
