### ISSUE TITLE
WP Rocket is giving error when Delay JS Execution on on Single Product Page 

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#1334]
On `dokan-lite/includes/Assets.php` file All dokan js are loading on Single product page. There should e filter so we can remove dokan js form single product page.  http://prntscr.com/1t2ajz0

When I removed the `is_product()` check there is no error from WP Rocket

**Comment by nurul-umbhiya** [comment]
@shohag121 bhai kindly take care of this issue
