### ISSUE TITLE
Processing order email for vendors

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1342]
**Description:**
Right now, vendors are getting a new order and completed order email notification.

But when an order status is **Cancelled/Failed** and later if the order status changed to **Processing**, only customers get information through an email.

It could be a better option to inform vendors through email that the order status is now processing.

**Comment by shahadat015** [comment]
The vendor receives an email when an order status is **Failed** and later if the order status changed to **Processing**, but not for canceled.

**Comment by shahadat015** [comment]
Yes, you're right, I have implemented this and working as expected.
