### ISSUE TITLE
Custom Order Status

### ISSUE THREAD

**Issue by uskuhub** [weDevsOfficial/dokan#1343]
**Describe the bug**
The custom order status documentation on [wedev](https://wedevs.com/blog/336381/dokan-custom-order-status) does not display on the woocommerce admin panel.

**To Reproduce**
Steps to reproduce the behaviour:
1. Once the code has been added into functions.php
2. Go to WooCommerce > Orders > Edit an order > Select your custom status
3. Return to the Orders page
4. Notice that the edited order is not listed anymore

**Expected behaviour**
The order labeled with the custom order status should still be displayed in the panel.

**Screenshots**
Order page that displays the orders.
https://snipboard.io/8f10HZ.jpg

**Environment (please complete the following information):**
 - Dokan Version: v3.2.12
 - Dokan Pro Version: v3.3.6
 - WooCommerce Version: v5.7.1
 - Browser Chrome
 - Current Theme: Themeisle - Hestia

**Comment by nurul-umbhiya** [comment]
This is not related to dokan core feature, hence I'm closing this issue.
