### ISSUE TITLE
Multiple fields for multiple category

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1358]
We only have a simple dropdown list for category on the product form, we are building a marketplace that need to have multi-category product, its better to have multi-field for different category rather than ask vendor to pick multi-category within only one long list . I believe this is quite fundamental for lots marketplace, its a simple change on site, but will make a big different for how adding products.

**Comment by nurul-umbhiya** [comment]
Already implemented on Dokan lite.
