### ISSUE TITLE
Store Address input fields are missing from the store setting form

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1359]
**Description of the Bug:**
Store Address input fields are missing from the store setting form when only the Dokan Lite plugin is activated.

**How to reproduce:**
Keep only the Dokan Lite plugin activated to see the issue

**Expected Behavior:**
The Store Address input fields should be available on the store setting form.

**System Status:**
Dokan Lite: 3.2.13
WordPress: 5.8.1
WooCommerce: 5.7.1

**Comment by nurul-umbhiya** [comment]
@devAsadNur Kindly consult with me before working on this
