### ISSUE TITLE
Showing product count including translated products when WooCommerce WPML activated

### ISSUE THREAD

**Issue by shahadat015** [weDevsOfficial/dokan#1366]
WooCommerce WPML handles product translation by creating a product for each language. For that reason Dokan vendor dashboard [showing product count](https://prnt.sc/1v51xpf) for all, online and in stock including translated products. That's why vendors get confisued. We can add also counts for each language [like that WPML showing](https://prnt.sc/1v525i6).

**Comment by nurul-umbhiya** [comment]
We are not going to provide this feature, since users can switch languages to see the count for each language. Besides, this feature will complicate the existing user interface.
