### ISSUE TITLE
Store Product per page setting doesn't work with Divi Theme

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1389]
**Description of the Bug:**
The Store Product per page setting doesn't work with the Divi Theme. It shows all products on one page of the store page.

**_Screenshot:_** https://snipboard.io/z4GyHq.jpg

**How to reproduce:**
Try to change the setting from the admin/vendor setting screen to see the issue.

**Expected Behavior:**
Store Product per page setting should work the Divi Theme.

**System Status:**
Dokan: v3.2.15
Dokan Pro: v3.3.9
WordPress: v5.8.1
WooCommrece: v5.8.0

**Comment by devAsadNur** [comment]
The issue has been generated from Divi Theme's end. We don't have anything to do without getting a fix from them. So, I'm closing the issue for now. We can re-open it later if needed.
