### ISSUE TITLE
Allow hiding product categories from Dokan dashboard

### ISSUE THREAD

**Issue by davefx** [weDevsOfficial/dokan#1398]
**Is your feature request related to a problem? Please describe.**
We are introducing Dokan into an existing shop. Here we have some _internal_ categories that we don't want to show to Vendors. We need a filter that allows us to hide categories from the Dokan dashboard so they are not visible to them. 

**Describe the solution you'd like**
It would be great if we have a hook that allows us to customize the product categories that are shown in the dashboard.

**Describe alternatives you've considered**
We know that we could get this by customizing the existing templates, but we consider this change to be interesting as a new feature in Dokan.

**Comment by nurul-umbhiya** [comment]
I'm going to close this pr, is because there is already a hook defined: dokan_product_cat_dropdown_args
use this filter hook and add exclude param,

**Comment by davefx** [comment]
The hook is defined, but it's not being called when generating the category dropdown in the modified interfaces!

**Comment by nurul-umbhiya** [comment]
We are already using this hook to include specific categories from the Vendor Subscription module, this should work just fine. If this doesn't work, kindly share your code with us, will try to figure this out. thanks

**Comment by davefx** [comment]
Ok. I found the actual origin of my found error: dokan_product_cat_dropdown_args was not being called from listing-filter.php. I'm now creating the correct Pull Request with the correct changes.
