### ISSUE TITLE
show seller's review/bio/contact/follow in the product page

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1402]
In most of the marketplace,  when buyer looking at the product page, they would like to see who is the seller ( this is not necessary for the B2C online shop, but necessary for marketplace because each product from different seller), at the moment, the seller info is hiding inside the " Vendor info"  tab,  user can't see the vendor review/bio at the same time when they see the product.
I would suggest if we can have the setting to show the vendor's review/bio/contact/follow in his product page, this will dramatically boost the sales of the product,

**Comment by nurul-umbhiya** [comment]
What you are requesting can't be done from the Dokan plugin. You can achieve this from the theme level with a few customizations.
![Screenshot 2023-06-02 at 2 31 05 PM](https://github.com/weDevsOfficial/dokan/assets/10240343/4981be7b-16bb-496d-bb8b-e512f98640d6)
