### ISSUE TITLE
Tooltip in the vendor dashboard is not working in the latest version of Electro theme (v3.2.0)

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1412]
**Description**
The tooltip of the vendor dashboard's [product edit form](https://snipboard.io/6akghK.jpg) is not working using the latest version of the Electro theme (v3.2.0).

**How To Reproduce**
1. Activate Electro theme (v3.2.0)
2. Navigate to the vendor dashboard's product edit form
3. The tooltips are now working

**Expected behavior**
The tooltips are supposed to work with the Electro theme's latest version with BootStrap 5.

**Environment**
 - Dokan Version: [ v3.3.0]
 - Dokan Pro Version: [ v3.4.0]
 - WooCommerce Version: [ v5.9.0]
 - WordPress Version: [ v5.8.1]
 - Electro theme: [ v3.2.0]

**Comment by MdAsifHossainNadim** [comment]
Executing our tooltip features is absolutely fine. Electro themes by default dequeued our tooltip assets. So this problem is created on the theme side.
