### ISSUE TITLE
dokan product category list doesn't match with  default category list

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1418]
I have a product category call "Other" which I put on the bottom of the default product category list, but on the dokan add product page, the "other" is showing on the middle of the list https://imgur.com/a/XEYjkbe , I guess the dokan product category list should match with the default woocommerce product category list.

**Comment by MdAsifHossainNadim** [comment]
Typically, Dokan follows the ascending order for the dropdown categories. The alphabetical order is being followed here. If you wish, you can maintain manual order with this filter hook 'dokan_product_cat_dropdown_args'.
