### ISSUE TITLE
dimension field for product 

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1423]
We are running a marketplace for selling artworks, each product that need to show the dimension on the product page and for the shipping purpose. if the dimension field that can be added into the default add product form. this is fundamental for lots type of products .

**Comment by CasperBraske** [comment]
+1
It's a feature in the Pro version. I hope they consider putting it in the Lite version as well.

**Comment by nurul-umbhiya** [comment]
Since we have this feature in pro version, I'm closing this issue now.

**Comment by leew999** [comment]
in the pro version, vendor need to add variable product to be able to use the dimension field, but in lots of the case, we don't want vendor to work with variable product, its just a single simple product, the dimension field should be able to be used for the simple product.
