### ISSUE TITLE
Item meta is not being deleted from the order details page of the WordPress dashboard.

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1435]
**Description of the Bug:**
The item meta is not being deleted upon deleting a meta from the order when an order is created from the WordPress dashboard.

**Video:** https://www.loom.com/share/b25b76f1b5bd47d1a8e8dd5bc809abb7

**How to reproduce:**
1. Create order from the WordPress dashboard.
2. Add multiple meta of an item.
3. Delete a meta and save it.
4. The deleted meta will still exist there.

**Expected Behavior:**
The metadata should be deleted after deleting.

**System Status:**
Dokan: v3.3.1
Dokan Pro: v3.4.1
WordPress: v5.8.2
WooCommrece: v5.9.0

**Comment by nurul-umbhiya** [comment]
@J-H-Mojumder have you tested this with Dokan and Dokan pro disabled?

**Comment by J-H-Mojumder** [comment]
@nurul-umbhiya it works completely fine when Dokan and Dokan Pro is disabled with only keeping WooCommerce enabled.
