### ISSUE TITLE
Pending Reviewed products are being published automatically when a vendor's selling capability is disabled and enabled again

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1439]
**Description of the issue:**
If a vendor has 10 products and 3 of them are in the **Pending Review** mode, for some reason, the admin disables the selling capability of that vendor.

At that time, all products go to **Pending Review** mode.

Later, when the admin enabled the selling capability of that vendor again, then all products are being published automatically, even the Pending Reviewed products.

**How to reproduce:**
- Keep a vendor product in the Pending Review mode
- Disable the selling capability of that vendor
- Now, all products are in the Pending Review mode
- Enable the selling capability of that vendor
- All products are being published

**Expected Behavior:**
When a vendor's selling capability is disabled, instead of the **Pending Review** mode, they could go in the **Draft** mode.

**System Status:**
Dokan: v3.3.2
WordPress: 5.8.2
WooCommerce: 5.9.0

**Comment by Themoonroy** [comment]
Expected Behavior:
When a vendor's selling capability is disabled, instead of the Pending Review mode, they could go in the Draft mode.
**

> Or better to create new product status if possible. like "Rejected product's", "Under review".

**

**Comment by Themoonroy** [comment]
**### This Enhancement is important.**

**Comment by devAsadNur** [comment]
The issue has been fixed by the following PR:
* #1840
