### ISSUE TITLE
Customizing>Dokan>Store page appears messy for some theme

### ISSUE THREAD

**Issue by Themoonroy** [weDevsOfficial/dokan#1448]
Theme: Woodmart
Builder: WpBakery 

> Screenshot: [CLICK ME](https://prnt.sc/22715j3)

**CSS for fix issue: (worked for me)** 
`.ui-state-default a, .ui-state-default a:link, .ui-state-default a:visited, a.ui-button, a:link.ui-button, a:visited.ui-button, .ui-button {
    display: inline-table;
}`

**Comment by Aunshon** [comment]
This is issue could not be regenerated, so i'm closing this issue. In future the issue occurs again we will reopen or create another issue.

Screenshot:
<img width="1440" alt="image" src="https://github.com/weDevsOfficial/dokan/assets/32583103/319e0371-703f-421d-b520-69c51cb7485d">

Tested on,
Dokan lite: 3.7.19
Dokan Pro: 3.7.22
Woocommerce: 7.7.2
Woodmart: 7.2.4
WPBakery: 6.13.0

**Comment by Aunshon** [comment]
This is issue could not be regenerated, so i'm closing this issue. In future the issue occurs again we will reopen or create another issue.

Screenshot:
<img width="1440" alt="image" src="https://github.com/weDevsOfficial/dokan/assets/32583103/319e0371-703f-421d-b520-69c51cb7485d">

**Tested on**,
Dokan lite: 3.7.19
Dokan Pro: 3.7.22
Woocommerce: 7.7.2
Woodmart: 7.2.4
WPBakery: 6.13.0
