### ISSUE TITLE
Admin should have the option to rearrange commission structure for his marketplace.

### ISSUE THREAD

**Issue by Themoonroy** [weDevsOfficial/dokan#1449]
**Admin should have the option to rearrange commission structure for his marketplace.**
Issue: Actually if you trying to make a free Dokan subscription package, and 2 premium package for your vendors. and want to set commission for the premium package 5%, 6% no extra charge. other hands for the free package if you want to set commission category-wise.  The Category commission overrides the premium package Store commission.
I need help to make this change because the developer does not give any setting for changing the Priority Between category and default Commission. or should give us an option to select/rearrange[...]

**Give admin an option to rearrange this structure **

**Comment by nurul-umbhiya** [comment]
We are planning to upgrade our commission calculation feature where we might be removing product-based commission system. If you still need this feature, feel free to take our customization support from [weLab](https://wedevs.com/welab/)
