### ISSUE TITLE
hierarchy product categories

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1452]
We have about 100 product categories, there will be more in the near future, they are all showing in a single super long list on the add product section,  its very difficult for vendor to find what they need,  see here https://imgur.com/a/ZCmjOav . if dokan is only a B2C shop run by admin, this won't be a problem, as admin I always can find what I need, but dokan its for hundreds vendors, they just found very difficult to find the product category, the section is very small, and the list is super long, its very difficult to use. I believe the hierarchy product categories is something must in the long term,

**Comment by nurul-umbhiya** [comment]
Already implemented on Dokan Lite
