### ISSUE TITLE
physical product variable showing on the product creating page when only selling digital product

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1454]
We have choose "I plan to sell only digital product" on the dokan setting page, but when creating the product variable, there are still many strange options showing which makes vendor very confused. https://imgur.com/a/R3Wtm8C  "Weight dimension downloadable virtual manage stock sku..." all these should be for physical product only. please remove these variable options when only selling digital products,  the vendors are very confusing with these options and they should not be there. thanks

**Comment by tanmayjay** [comment]
Hello, @leew999 

This is default behavior of WooCommerce. In the Vendor Dashboard, the fields are mapped according to the fields mapped by WooCommerce in the Admin panel. Also, for more information about Digital/Downloadable products, you can read the [documentaion](https://woocommerce.com/document/digital-downloadable-product-handling/#section-6).

**Comment by tanmayjay** [comment]
Hello, @leew999 
These fields are mapped exactly like WooCommerce did. However, we have considered the fact that when "I plan to sell only digital product" is checked in Dokan settings, the `Downloadable` and `Virtual` options should be automatically checked. In that case, the weight and dimension fields will be unavailable but stock management fields will be available as per the use cases of WooCommerce. You can check these use cases by adding/editing a product from Admin panel. Also, for more information about digital products, you can visit [the documentation](https://woocommerce.com/document/digital-downloadable-product-handling/).
