### ISSUE TITLE
simplify the creation of product attributes and variable

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1459]
when creating the product attributes and variable, its a multistep process, its not easy to understand what to do and where to click, our vendors found very difficult to work with the attribute and variable at the beginning,  as admin I need to have a very detail long page to describe how to setup the attribute and variable for our vendors.  this will block the usage from vendors. I was looking at the fiverr.com's product creation process, they have a one-step simple form to let vendor enter the attributes and variables. please see here [](https://imgur.com/a/cdIRXrJ)  I will suggest the dokan to have a maybe module to only work on this part to simplify this. otherwise as admin I found difficult to work on the attribute and variable at the beginning, I can't imaging the vendors will have patience to learn how to setup the attribute/variable,  this is related to the strategy of the dokan, is dokan for prefessional developer or for the majority of the end-users?

**Comment by nurul-umbhiya** [comment]
@leew999  We've redesigned the product edit page on our new Dokan Vendor Dashboard. Kindly use the new dashboard and let us know your experience.
