### ISSUE TITLE
Multiple category field for parent taxonomy

### ISSUE THREAD

**Issue by stylebbs** [weDevsOfficial/dokan#1462]
We have a marketplce for educational courses. each of the course will need to be saved into multiple category, like "course type, course level, Qualification type, Method of study etc.."  we also need to have the sidebar search/selection for these categories.
we have created multiple parent/child product categories through woocommerce, but we only have a single field for all these category. we need to have multiple fields for each of the parent category. please add this if possible .

**Comment by nurul-umbhiya** [comment]
Already implemented on Dokan Lite
