### ISSUE TITLE
make product description field "required"

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1470]
we are getting empty product description from vendors, see here https://imgur.com/a/b5xGZ8k  , after enter the short description field, vendor ignore the description field, its a small thing, but makes the website look bad.

**Comment by Tangol** [comment]
Duplicate of https://github.com/weDevsOfficial/dokan/issues/1258

**Comment by nurul-umbhiya** [comment]
Closing duplicate entries.
