### ISSUE TITLE
Dokan promo banner notice is not responsive

### ISSUE THREAD

**Issue by shanjidah** [weDevsOfficial/dokan#1471]
**Describe the bug**
Dokan promo banner notice is not responsive, overlap the button & text

**To Reproduce**
1. Activate Dokan Lite Plugin
2. Go to Dokan Menu

**Expected behavior**
The Promo banner should be responsive.

**Screenshots**
<img width="1272" alt="Screen Shot 2021-12-23 at 5 32 32 PM" src="https://user-images.githubusercontent.com/37714632/147311528-961b5b47-ce6c-4b5b-8e05-5986b4ba40a7.png">

**Comment by shahadat015** [comment]
Please mention your tested screen size
