### ISSUE TITLE
dimension field for simple product

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1475]
my previous feature request was closed. so I open this again,  in the pro version, vendor need to add variable product to be able to use the dimension field, but in lots of the case, we don't want vendor to work with variable product, its just a single simple product, the dimension field should be able to be used for the simple product. this is very basic for lots type of products.

**Comment by Riyadh1734** [comment]
Hello, @leew999 Are you saying something about this field??
![image](https://user-images.githubusercontent.com/59993047/148900289-7389c4c6-c93f-45cf-b1ed-5376d2221573.png)

**Comment by leew999** [comment]
yes @Riyadh1734 , dimensions for simple product

**Comment by Riyadh1734** [comment]
@leew999 If you need this one then go to https://github.com/Riyadh1734/Product-dimensions and download it then install this plugin to your site. Also, you can edit your function.php file to add the feature.

**Comment by leew999** [comment]
@Riyadh1734 thanks,  I added your php through code-snippets, but there is no change on the product adding page, still no dimension field.
and also, is your plugin supported by dokan ?

**Comment by Riyadh1734** [comment]
@leew999 Yes, Supported. Please check !!

**Comment by leew999** [comment]
@Riyadh1734  I added your code through code-snippets like this https://imgur.com/a/tigMGgn but there is no diemension field added into the product page, please advise

**Comment by Riyadh1734** [comment]
please upload the plugin zip file to the plugin upload option than active it ..I think it will work well for you

**Comment by nurul-umbhiya** [comment]
@rajankarmakar kindly look into this.

**Comment by Riyadh1734** [comment]
@leew999 Please use "dimension/dimension.php"

**Comment by Riyadh1734** [comment]
@leew999 
![image](https://user-images.githubusercontent.com/59993047/148976133-04fbab74-f59f-4842-8796-0aea17e8c06e.png)

**Comment by Riyadh1734** [comment]
> @Riyadh1734 I download/upload your plugin zip file which including the "Product-dimensions-main/dimension/dimension.php" , during the installation, its showing to me "The package could not be installed. No valid plugins were found. ,Plugin installation failed." see here please https://imgur.com/a/9lqFAsn

If there is a problem, copy the Dimensions folder and create your own zip file. Then upload the plugin it will work just fine

**Comment by leew999** [comment]
@Riyadh1734 thanks, I installed and enabled the plugin, but there is no "dimension" field showing on the add product/edit-product page for simple-product type, am I missing something ?

**Comment by Riyadh1734** [comment]
@leew999 Sorry! I think you missed something. Because single or variable products both are supported shipping options to set the dimension of the product. 
And my plugin only shows your dimensions on the product page that I saw in the first picture of mine.

**Comment by rajankarmakar** [comment]
Hello @leew999,
If I am not wrong, The dimension field is already there for a vendor. The vendor can add dimensions as in the image below. Please correct me if I'm wrong. Maybe you have missed this portion.

[See the screenshot](https://ibb.co/RpmqhX0)

**Comment by leew999** [comment]
@rajankarmakar  there is no dimension field on the create product page, but there are dimension fields under the shipping/tax section which showing on the edit product page, its kind of different, the dimension fields should be as the basic product information that showing on the create product page, most user will miss the shipping/tax section on the edit product page.

**Comment by rajankarmakar** [comment]
@leew999 you are correct that the dimension field does not show on the create product page. Because we wanted to make the product create modal minimal so that it fits the screen and looks clean. Besides if anybody wants to change anything about the product we redirect the user to the product edit page to add or edit additional fields like dimension and other things. Hope you understand our intention. Your feedback is so valuable to us. If we make any big change to our product creation modal then we will consider your request.
