### ISSUE TITLE
Hide related products when a vendor subscribes to a certain package dokan subscription

### ISSUE THREAD

**Issue by renrax** [weDevsOfficial/dokan#1493]
I want sellers who have a certain subscription package to be able to disable the display of Related Products on a single product page on their own.

On dokan edit product page there should be a checkbox to enable/disable this feature, if allowed by the administrator.

The Dokan Subscription product type should have a checkbox to allow or prohibit the seller to manage related products on a single product page. When creating a new subscription the administrator enables or disables this option.

**Comment by nurul-umbhiya** [comment]
We are planning to add module-based restrictions for Vendor Subscription Module, unfortunately, we don't have any plan to include feature-based restrictions. 
However, If you need this feature, you can ask for support from weLab https://wedevs.com/welab/
