### ISSUE TITLE
limit product gallery image 

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1503]
there are no limits for how many product images that user can upload for now, please see here https://imgur.com/a/4tZt07g I have user who upload 20 images for his product, this is disaster, please add limitation setting for how many images that user can upload

**Comment by Tangol** [comment]
Here is a nice code snippet that might help you, until the Dokan devs find a solution:
https://wordpress.stackexchange.com/questions/21084/how-can-you-limit-the-number-of-images-videos-that-can-be-uploaded-to-a-wordpr

**Comment by leew999** [comment]
@Tangol I tested the code doesn't work... @nurul-umbhiya don't understand the logic for this, if this is something very basic for everyone, why don't include in lite or pro ? as long as running a marketplace through dokan, this will be a critical thing. we don't use the subscription module, if there is another way to help with this ? thanks

**Comment by devAsadNur** [comment]
We're closing the issue, as this feature is already available with `Dokan Vendor Subscription` Module. Also, we don't have any plans to include this feature directly in `Dokan Lite` or `Dokan Pro`.
