### ISSUE TITLE
Geolocation with Google Maps not working as expected (vendor settings and store listings)

### ISSUE THREAD

**Issue by dman926** [weDevsOfficial/dokan#1509]
**Describe the bug**

**To Reproduce**
1.)
1. Go to the vendor settings page
2. Click on the map in a different town
3. See that the input field is not updated.

2.)
1. Go to store listing page
2. See that stores aren't being shown in the map

**Expected behavior**
1.) Selecting a town on the map should update the location in the input field
2.) There should be markers in the store-listing page's map for each store

**Screenshots**
![Screenshot_20220120_181037](https://user-images.githubusercontent.com/13112544/150436811-e913d5c4-a27a-45b4-b942-d3f3548e3b81.png)
![Screenshot_20220120_180956](https://user-images.githubusercontent.com/13112544/150436812-40491f18-76a7-4979-9864-77b38d355a81.png)

**Environment (please complete the following information):**
 - Dokan Version: 3.3.6
 - Dokan Pro Version: 3.4.4
 - WooCommerce Version: 6.1.0
 - Browser Chrome, Edge, Firefox
 - Current Theme: Dokani Develop

**Additional context**
At least for the first issue, if the gmap variable was global, I could fix it myself, but it's inside of a jQuery ready function.

**Comment by shashwatahalder01** [comment]
Scenario: 
Vendor settings: The location input field is only updated by dragging the location marker. The location input field should also be updated by clicking on any point on the map. 


For reference, Go to vendor product edit page > Geolocation see location input field update behavior.
https://www.awesomescreenshot.com/video/7076170?key=3c0c5d9bd925269d61efee1c7c285bf6
