### ISSUE TITLE
multiple category fields for product

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1520]
We are trying the dokan on different marketplace, we face the same problem on different products, almost all of the products will need to be saved into multiple category, one of our site are for fashion, products that need to be saved into many cateogries like men/women , product style, product type, product brand, another makerplace we are facing the problem for artworks, each of the product that need to be saved into multiple categories like artwork type, artwork-style,  artwork-country, artwork-time-period, etc.., its impossible to get all this by only have one category field, I guess this is very fundamental for all of the marketplace, am wondering how others are dealing with this situation.

**Comment by nurul-umbhiya** [comment]
Already implemented on Dokan Lite
