### ISSUE TITLE
Gateway fees from woocommerce paypal payments not being deducted

### ISSUE THREAD

**Issue by danielbreves** [weDevsOfficial/dokan#1528]
As of 1 Sept 2021, [PayPal Checkout](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout) is officially retired from WooCommerce.com, and support for this product ended on 1 March 2022 in favour of [PayPal Payments](https://github.com/woocommerce/woocommerce-paypal-payments). Dokan deducts PayPal Checkout [fees](https://github.com/weDevsOfficial/dokan/blob/e5c7ff9bf0801134934252fccf6ef1b6808eaa45/includes/Commission.php#L770-L783) from vendors earning [here](https://github.com/weDevsOfficial/dokan/blob/master/includes/Commission.php#L74), but it does not deduct PayPal Payments fees.

~Unfortunately, [PayPal Payments doesn't set transaction fee metadata](https://github.com/woocommerce/woocommerce-paypal-payments/issues/467) at the moment.~ As of [1.7.0](https://github.com/woocommerce/woocommerce-paypal-payments/pull/490), PayPal Payments sets transaction fee metadata [here](https://github.com/woocommerce/woocommerce-paypal-payments/blob/caf9a2c50d7f340d0aa11b83b6aca6404025ef80/modules/ppcp-wc-gateway/src/WCGatewayModule.php#L78). However, Dokan's [`dokan_get_processing_fee`](https://github.com/weDevsOfficial/dokan/blob/dd83540234f970b1ac4a37076ed7650da64e79ff/includes/Commission.php#L782) filter seems to fire before [`woocommerce_paypal_payments_order_captured`](https://github.com/woocommerce/woocommerce-paypal-payments/blob/caf9a2c50d7f340d0aa11b83b6aca6404025ef80/modules/ppcp-wc-gateway/src/WCGatewayModule.php#L78), when the fee metadata is set.

**To Reproduce**
1. Make a purchase using PayPal Checkout
2. Make a purchase using PayPal Payments
3. Compare the difference between `net_amount` and `order_total` in `dokan_orders`

**Expected behavior**
Dokan should deduct PayPal Payments fees from vendor earnings.

**Environment (please complete the following information):**
 - Dokan Version: 3.3.6
 - WooCommerce Version: 6.1.1

**Comment by nurul-umbhiya** [comment]
@danielbreves we are working on this, will be fixed soon.

**Comment by nurul-umbhiya** [comment]
@danielbreves is this issue still exists with PayPal Checkout?
