### ISSUE TITLE
Using more user-friendly alert for sub-orders refund from the main order and refunded products are not being restocked.

### ISSUE THREAD

**Issue by shafinoid** [weDevsOfficial/dokan#1529]
**Is your feature request related to a problem? Please describe.**
It is an enhancement request for the alert which is triggered once a user tries to refund sub-orders from the main order.

You can have a look at this [screenshot](https://snipboard.io/1kzLHf.jpg) for a better understanding.

**Describe the solution you'd like**
It will be great if it just says something like "You cannot refund sub-orders from here. Kindly refund from the individual sub-orders page.".

**Comment by bigboss97lnt** [comment]
Hi, it doesn't decrease the quantity when you refund a sub-order as well

**Comment by shafinahmad01** [comment]
*******BUG*******
******************
In Addition,

You have two different vendors' products with 10 pcs in stock. After ordering from different vendors they might have 9 pcs in the stock. Now, try to refund any of them then the stock will not be creased or added back to the product.

Kindly check that issue as well.

**Comment by vreoo** [comment]
I am wondering if this bug is resolved in the new Update??

**Comment by bigboss97lnt** [comment]
bug still exists after the last update (Dokan 3.3.8 & Dokan Pro 3.5.1)

**Comment by bigboss97lnt** [comment]
I request changing the name of this ticket, it should say "Sub-order refund doesn't re-stock refunded products"
and how come after 2 months its still not fixed while this is a huge issue
