### ISSUE TITLE
Google Analytics fails due to max size being reached

### ISSUE THREAD

**Issue by dman926** [weDevsOfficial/dokan#1532]
**Describe the bug**
Google analytics doesn't work for very large vendors due to the URL length limit Google enforces.

**To Reproduce**
1. Create Vendor
2. Add a large number of products (issue affecting one account with 220 products)
3. Go to analytics page
4. See google analytics error on location page and lack of dashboards throughout the analytics tabs

**Expected behavior**
There should be an analytic dashboard.

**Screenshots**
![Screenshot_20220208_120048](https://user-images.githubusercontent.com/13112544/153037553-d43adb0a-85da-46db-8309-8f915a8f8f07.png)

**Environment (please complete the following information):**
- Dokan Version: 3.3.7
- Dokan Pro Version: 3.5.0
- WooCommerce Version: 6.1.1
- Browser Chrome, Edge, Firefox
- Current Theme: Dokani Develop

**Additional context**
This is caused by the fact that a large query isn't broken up to avoid the URL length limit

**Comment by bigdaddyral** [comment]
This was opened 8 months ago, any idea when it will be resolved?
