### ISSUE TITLE
display "Get support button" by default

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1547]
my previous post about the same request seems was closed. but I don't see this has been improved from the latest version. I have a digital service marketplace. At the moment, almost none of my vendors are able to display the "Get support" button on the product page,  it seems user need to enter their address on their setting page to have the button display. but none of the vendors are doing this because they are selling digital things. please make the "Get Support" button display by default, without having this button, buyer almost no way to get in touch with sellers. its a real problem.

**Comment by nurul-umbhiya** [comment]
Hello @leew999, I couldn't reproduce this issue with the latest version of Dokan lite and pro. I also tried with a fresh installation, still no luck. Kindly check your admin settings from WP Dashboard --> Dokan --> Settings --> Store Support. Save the setting again. Let me know if this fixed your issue.
