### ISSUE TITLE
REST API Error 401

### ISSUE THREAD

**Issue by jeffreyturingan** [weDevsOfficial/dokan#1574]
**Describe the bug**
I'm trying to get data from the withdraw endpoint using Basic Auth (plugin installed) in postman (https://gmkt.tvcxsolutions.com/wp-json/dokan/v1/withdraw/) and it throws a 401 error so i tried using JWT Authentication but same error.. i also tried some endpoints but the only successful endpoint is the stores endpoint

![image](https://user-images.githubusercontent.com/1893238/158583555-a652dfec-49e4-452c-99d5-bd157e9fa604.png)
![image](https://user-images.githubusercontent.com/1893238/158583773-06a14f93-27d0-458b-bef7-2708d8b129e7.png)
![image](https://user-images.githubusercontent.com/1893238/158583654-3a6a976b-e97a-4dd5-b6c6-b45d51f8499a.png)

**Environment (please complete the following information):**
 - Dokan Version:  v3.3.9
 - Dokan Pro Version: 3.5.2
 - WooCommerce Version: 6.2.1
 - Browser : Postman
 - Current Theme: XStore
 - Wordpress. 5.8.1

**Comment by NAbdulla1** [comment]
Hello @jeffreyturingan, after getting this issue from you we have tested the API endpoints from several API clients(postman, thunder client, etc) and we have come to the conclusion that the endpoints are okay. Please check your authentication configuration carefully.
