### ISSUE TITLE
Vendor earnings & withdrawal balance remains the same after a refund

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1575]
**Description of the bug:**
Refunding an order from the admin dashboard keeps the vendor earnings and withdrawal balance the same instead of negative the respective amount.

**Screenshots:**
https://snipboard.io/CfsRQ0.jpg
https://snipboard.io/F85N6L.jpg
https://snipboard.io/w2BdFG.jpg
https://snipboard.io/ynFGBC.jpg

**How to reproduce:**
Refund an order from the **WP Admin > WooCommerce > Orders** screen and check the vendor dashboard to see the issue.

**Expected Behavior:**
After a refund, the respective amount should be negative from the vendor earnings and withdrawal balance.

**System Status:**
Dokan: v3.4.1
WordPress: v5.9.2
WooCommerce: v6.3.1

**Comment by Riyadh1734** [comment]
@tanjiralmamun please check this issue #905 with the commit https://github.com/alamgircsebd/dokan/commit/b8a8e9a0b0e33cedf70fe763dfd7224df92372b5

**Comment by shohag121** [comment]
@tanjiralmamun Bhai, 
As the payment method is `COD` It might not reflect on the vendor balance.  Dokan has a setting with the relation of vendor balance and `COD`. Dokan > Settings > Withdraw options > Exclude COD Payments options determine if the balance should reflect based on payment or refund.

I am assuming that is the case here. Closing the issue. Feel free to open it if my assumption is not correct.

**Comment by tanjiralmamun** [comment]
@shohag121 Bhai,
Although we have the option to exclude COD payments from the vendor balance, this is an optional setting. Since we have introduced the Reverse Withdrawal feature, most users may not use that option now. 

Additionally, if anyone uses other offline/non-adaptive payment methods, the case is the same for them. So, it would be better if we can fix it.

Alternatively, you can look the @alamgircsebd bhai's [PR](https://github.com/alamgircsebd/dokan/commit/b8a8e9a0b0e33cedf70fe763dfd7224df92372b5).

**Comment by oliviertassinari** [comment]
I have noticed the same bug when a chargeback happens with "WooCommerce Stripe Gateway". The vendor earning don't update after it. Both /wp-admin/admin.php?page=dokan#/reports?tab=logs&order_id= and `dokan_vendor_balance` database have wrong values.

**Comment by shohag121** [comment]
@oliviertassinari "**WooCommerce Stripe Gateway**" handles chargeback events by changing order status from webhook events. 
Dokan already handles Order status change events for Parent Orders and Clild Orders.

We suggest you check the webhook setup from the stripe end, especially the webhook secret settings.

**Comment by bkluiter** [comment]
@oliviertassinari have you found a solution for this bug? I have the same problem and cant find a way to solve this.

**Comment by oliviertassinari** [comment]
@bkluiter We don't use the Dokan commissions system, we have built our own. I noticed this while exploring whether we could rely on the built-in system.
