### ISSUE TITLE
dashboard page conflict with WP-UserFrontend

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1578]
I installed the WP-UserFrontend first and created all WPUF pages, then install the Dokan, the dashbaord page is conflict with WPUP's dashboard page, the system can't create the dashboard page as required, I have to manually to create the page, but the permalink still conflict with WPUP's dashboard page

**Comment by nurul-umbhiya** [comment]
@leew999 we couldn't reproduce this issue on our end. kindly ask for help from support, we'll investigate this issue on your site.
