### ISSUE TITLE
Fatal Error: Dokan Pro Elementor Module and Elementor Pro Incompatible

### ISSUE THREAD

**Issue by fisher2470** [weDevsOfficial/dokan#1579]
Fatal error: Declaration of WeDevs\DokanPro\Modules\Elementor\Widgets\StoreFollowButton::render_text() must be compatible with Elementor\Widget_Button::render_text(?Elementor\Widget_Base $instance = null) in /www/mycommunitymade_125/public/wp-content/plugins/dokan-pro/modules/elementor/includes/Widgets/StoreFollowButton.php on line 147

**Environment (please complete the following information):**
 - Dokan Version: 3.4.1
 - Dokan Pro Version: 3.5.4
 - WooCommerce Version: 6.3.1
 -  Elementor Pro: 3.6.4
 - Current Theme: Dokani Child Theme

**Comment by nurul-umbhiya** [comment]
We will be releasing a new version soon. Till then kindly downgrade Elementor free version to previous version.
