### ISSUE TITLE
product shipping dimension including "inch "

### ISSUE THREAD

**Issue by leew999** [weDevsOfficial/dokan#1581]
Its only showing the "cm" on the product dimension, but in EU and US most of people prefer to see the "inch" , its very basic on almost all of the shop website. please add automatic conversion for "inch" and "cm".

**Comment by nurul-umbhiya** [comment]
@leew999 I think this is the default WooCommerce behavior. Let me know if you think otherwise.

**Comment by nurul-umbhiya** [comment]
@leew999 Kindly follow this documentation: https://woocommerce.com/document/adding-dimensions-and-weights-to-products-for-shipping/
