### ISSUE TITLE
Delivery time pop-up calendar content only shown in English language and format

### ISSUE THREAD

**Issue by lonifasiko** [weDevsOfficial/dokan#1584]
Good morning,

Our marketplace is based in Spain and thus we've established Madrid for the timezone and local datetime format settings in Wordpress general settings. In spite of this, when using the delivery time module, the calendar shown to users during checkout shows English-based date format, that is, names of days and month in the pop-up calendar are shown in English, and week starts on Sunday (see picture here: https://imgur.com/a/mygsIEl). We need days and month names of the calendar to be in Spanish and it's mandatory that week starts on Monday. Otherwise, this unusual week-start in Spain can lead our users to error when selecting the desired delivery date, as they are used to seeing Monday on the left and Sunday on the right side. 

To reproduce it, add a product to the cart, and with delivery time module enabled, in the checkout page, just click in the field to select a delivery date. The calendar, will pop-up, completely in English format, while we are based in Spain.

Hope you can solve this issue as soon as possible, it's very important for us not to confuse users during checkout process as this could lead them to abandone the process. 

Thanks very much in advance. 

Best regards, 
Miguel.

**Comment by lonifasiko** [comment]
Dokan has recently corrected in Dokan Pro 3.7.13 the issue with the starting day of the week in the calendar, that is, calendar now gets the general local/regional format defined in Wordpress general settings. However, names of the week days and months shown in calendar still cannot be translated.

**Comment by nurul-umbhiya** [comment]
@lonifasiko You need to translate the day week and month names first.

**Comment by lonifasiko** [comment]
Where? We do not see these strings anywhere in the backend settings, and
the multilanguage plugin we use, WPML, neither shows them.

Please do tell me where exactly we should look at.

Thanks,

**Comment by nurul-umbhiya** [comment]
file: dokan-pro/modules/delivery-time/module.php
line: 199 - 263
Look for context with `Flatpickr calender` eg `Flatpickr calender shorthand month name`
If you still couldn't find the string, reload dokan pro pot file from WPML

**Comment by lonifasiko** [comment]
Thanks, I'll check it out with the developers.
--
Miguel Loitxate 'Lonifasiko'

Web <https://www.Lonifasiko.com/> | Twitter <https://twitter.com/Lonifasiko>
 | Facebook <https://www.facebook.com/Lonifasiko> | Instagram
<https://www.instagram.com/Lonifasiko/> | LinkedIn
<https://es.linkedin.com/in/miguelloitxatelonifasiko>
