### ISSUE TITLE
[Single Store]: The newly added sections (featured, latest, top rated, best selling) are not appearing.

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1587]
**Describe the bug**
The newly added product sections on the single store page (featured, latest, top rated, best selling) are not appearing upon settings.

**To Reproduce**

1. Navigate to the Customizer > Dokan > Single store section.
2. Uncheck the sections to show products on the single store page as shown in [this screenshot](https://snipboard.io/8KOltC.jpg).
3. The sections will not be added respecting the settings.

**Expected behavior**
The sections should appear and disappear upon settings.

**Screenshots**
https://snipboard.io/8KOltC.jpg

**Environment:**
 - Dokan Version: [v3.4.1]
 - WooCommerce Version: [v6.3.1]
 - Current Theme: [Dokan]

**Comment by MdAsifHossainNadim** [comment]
@J-H-Mojumder I was able to reproduce this problem and find out if this feature is correct. We should check the "Store page product sections" options then it will work fine for customizer settings.
