### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by aref0448** [weDevsOfficial/dokan#1593]
My new suggestion is that in the dokan plugin, after editing the product by the seller, the product should not be removed from the site. Because this is bad for site SEO
and In the next update, custom statuses will be created and implemented for products sent by sellers.
tnx

**Comment by nurul-umbhiya** [comment]
You can disable this feature by disabling **Edited Product Status** From WordPress Admin Dashboard --> Dokan --> Settings --> Selling Options.
