### ISSUE TITLE
The third store header template is broken

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#1625]
**Description of the issue:**
The third store header template style doesn't match the setting image.
Dokan Theme - https://snipboard.io/VRxaXh.jpg
Storefront - https://snipboard.io/WBM8r6.jpg

**How to reproduce:**
Choose the third store header template to see the issue

**Expected Behaviour:**
The third store header template style should match the setting image.

**System Status:**
Dokan: v3.5.1
Dokan Pro: v3 6.2
WordPress: v6.0
WooCommerce: v6.5.1

**Comment by fisher2470** [comment]
#1654 will resolve this issue
