### ISSUE TITLE
Sort order for order listing page changed to ascending

### ISSUE THREAD

**Issue by danielbreves** [weDevsOfficial/dokan#1667]
**Describe the bug**
Sort order for order listing page seems to have changed to ascending.

**To Reproduce**
1. Go to /dashboard/orders/
2. Notice order list is in ascending order

**Expected behavior**
Order listing should be in descending order, i.e. showing most recent orders first

**Screenshots**
![Screen Shot 2022-08-02 at 7 19 58 pm](https://user-images.githubusercontent.com/2517811/182340436-5b30b229-00e5-4191-81a9-7fad13fa589d.png)

**Environment (please complete the following information):**
 - Dokan Version: 3.6.3
 - WooCommerce Version: 6.7.0

**Comment by danielbreves** [comment]
@NAbdulla1 @nurul-umbhiya possibly introduced by https://github.com/weDevsOfficial/dokan/pull/1480/files#diff-1e09f64467508a7c5f9c0b869811d1a71c0e64773812292bc96f2cfb1eb9ce81L68

**Comment by nurul-umbhiya** [comment]
@danielbreves already fixed this issue in develop branch. Will be fixed on the next release of Dokan Lite possibly on the 10th of August.
