### ISSUE TITLE
Hook needed 

### ISSUE THREAD

**Issue by kingplugins** [weDevsOfficial/dokan#1677]
Hi there, We are plugin developers working on a Dokan integration and we need a hook in Dokan Lite. 

Please add this hook like in the next image, shouldn't take more than a few seconds of your time. 

In dokan-lite/Includes/Product/Hooks.php we need this filter: https://i.imgur.com/DJN0QHk.png 

Thank you,

**Comment by nurul-umbhiya** [comment]
`$query_results = apply_filters( 'dokan_store_product_search_results', $wpdb->get_results( $querystr ), $store_id, $keyword );` has been added
