### ISSUE TITLE
View orders from other sellers in Rest Api

### ISSUE THREAD

**Issue by hassan-hossini** [weDevsOfficial/dokan#1680]
Hello

Since version 3.6.3 orders for other sellers are displayed in RESTAPI !!

Because when receiving orders, the seller’s ID is not set:

**dokan-lite/includes/REST/OrderController.php
Line 420**

```
$args = [
    'status'      => $request['status'],
    'order_date'  => $request['order_date'],
    'limit'       => $request['per_page'],
    'paged'       => isset( $request['page'] ) ? absint( $request['page'] ) : 1,
    'customer_id' => $request['customer_id'],
];

$orders = dokan()->order->all( $args );
```

I put it like this and it was fixed:

```
$args = [
    'status'      => $request['status'],
    'order_date'  => $request['order_date'],
    'limit'       => $request['per_page'],
    'paged'       => isset( $request['page'] ) ? absint( $request['page'] ) : 1,
    'customer_id' => $request['customer_id'],
    'seller_id'   => get_current_user_id(), // <= Seller ID
];

$orders = dokan()->order->all( $args );
```

Please solve this problem.

Thanks.

 - Dokan Version: [e.g. v3.6.4]
 - Dokan Pro Version: [e.g. v3.1.2]
 - WooCommerce Version: [e.g. v6.8]
 - Browser [chrome, safari]
 - Current Theme: [Store Front]

**Comment by nurul-umbhiya** [comment]
fixed on latest version of dokan lite
