### ISSUE TITLE
Dokan Category

### ISSUE THREAD

**Issue by krazyplugins** [weDevsOfficial/dokan#1681]
Thank you for the updating category layout in the vendor dashboard.

Now, I wishes to have an ability when the category is selected, I want to do some modification using jQuery to the form fields. I tried to do it by trying the change event on hidden field for the category but it is not working. It looks like the change event should be fired from the code where the hidden field is created. can you please look into it and let me know how can I do that?

I am sure this issue will be faced my many developers so it will be great if you can sort it out as soon as possible.

**Comment by nurul-umbhiya** [comment]
@Aunshon can we add some hooks here?

**Comment by Aunshon** [comment]
Added a hook named  `dokan_multistep_category_selected`, now you can do anything right after a category is selected,
Code example: 
```
wp.hooks.addAction(
    'dokan_multistep_category_selected', 
    'dokan-multistep-category', 
    function ( selected_cat ) { 
        console.log(selected_cat + " this is the category.");
    } 
);
```

**Note: This code will work after this pr is merged.**
