### ISSUE TITLE
[Security] Moment.js@2.21.0 JavaScript library with known security vulnerability

### ISSUE THREAD

**Issue by vreoo** [weDevsOfficial/dokan#1692]
**Describe the bug**
The Bug is mainly in a specific JavaScript library called "**moment**" The current version is @2.21.0.
According to [snyk.io](https://security.snyk.io/package/npm/moment), there is a **Directory Traversal** vulnerability that "aims to access files and directories that are stored outside the intended folder" & overwriting sensitive files

**To Reproduce**
1. Must have `dokan-lite` plugin
2. On any page on your website run the lighthouse test.
3. 
![image](https://user-images.githubusercontent.com/74427567/188583572-ea995fa1-212d-46fb-8f82-edb7ede2dd64.png)

**Expected behavior**
No expected behavior but an update to the `moment@2.21.0` library to the LATEST NON-VULNERABLE VERSION.
LATEST NON VULNERABLE VERSION is [2.29.4](https://security.snyk.io/package/npm/moment/2.29.4)

**Environment (please complete the following information):**
 - Dokan Version: v3.6.4
 - Dokan Pro Version: v3.7.4
 - WooCommerce Version: v6.8.1
 - Browser Chrome
 - Current Theme: Flatsome

**Comment by nurul-umbhiya** [comment]
Will be fixed within next version of dokan lite

**Comment by nurul-umbhiya** [comment]
Fixed on dokan lite version 3.7.0
