### ISSUE TITLE
Admin toolbar visible in the vendor dashboard 

### ISSUE THREAD

**Issue by Fayeakuzzamantonmoy** [weDevsOfficial/dokan#1698]
**Description of the bug**
With a newly installed Dokan environment, Admin Area Access is enabled in the backend settings which is supposed to not to show the WordPress admin toolbar at the top of the page when logged in as a vendor.
However, the vendor is still able to view the admin toolbar at the top of the vendor dashboard. To fix this issue, the admin needs to disable the Admin Area Access option, save it and again enable it, save it.

**Way of reproduce**
Execute a fresh install and add a vendor. Then please navigate to the vendor dashboard. You will be able to find the Admin Toolbar

**Expected behavior**
Admin toolbar should not be visible in the vendor dashboard.

**Environment**
 - Dokan Version: 3.6.5
 - Dokan Pro Version: 3.7.5
 - WooCommerce Version: 6.8.2

**Comment by Fayeakuzzamantonmoy** [comment]
Bhai as per our discussion, you are unable to find the issue. So, I rechecked it from my end and was able to find the case. Reference available here: https://www.loom.com/share/48ad8f02007946fe8454c7054d21346a

**Comment by nurul-umbhiya** [comment]
fixed
