### ISSUE TITLE
Approving refund request should refund on the payment gateway too

### ISSUE THREAD

**Issue by oliviertassinari** [weDevsOfficial/dokan#1718]
**Is your feature request related to a problem? Please describe.**

We are processing refunds as follow https://mui-org.notion.site/Approve-refunds-from-contributors-a50294341dfd4ea7a3864cacf5788862. There are more steps that it needs to be. 

**Describe the solution you'd like**

We would like steps 3, 5, 6, 7 to be handled by Dokan for the official Stripe and PayPal payment gateways. And no, we have no interests in using dokan payment gateways like https://wedevs.com/dokan/modules/stripe-connect/.

**Comment by Aunshon** [comment]
Have the “Approve Refund” do the refund on the payment gateway directly. It already works in dokan. 
Please make sure You have enabled Process Refund via API in Dokan settings -> SELLING OPTIONS -> Process Refund via API
<img width="1440" alt="Screen Shot 2022-10-03 at 12 08 00 PM" src="https://user-images.githubusercontent.com/32583103/193511467-6cda1d67-1e75-43aa-a99b-3b432ffaee15.png">
And when request for vendor click the `Refund $-- via ----` button, as screen shot.
<img width="1440" alt="Screen Shot 2022-10-03 at 12 11 59 PM" src="https://user-images.githubusercontent.com/32583103/193511822-e45c6db6-783d-4e74-b0ec-c8627a0d4bb4.png">


Check out this video:
https://www.awesomescreenshot.com/video/11466349?key=1af5e4ca7658851446bb345b4ca575d0

**Comment by nurul-umbhiya** [comment]
Dokan Lite doesn't support refunds and is perfectly working on Dokan Pro. Kindly upgrade to Dokan Pro for the refund feature. For now, I'm closing this issue.

**Comment by oliviertassinari** [comment]
We didn't have this switch on, not sure why. It behaves as expected once it's turned on. Thanks, it's saving our operations team time and reduces mistakes.
