### ISSUE TITLE
[Dokan data updater]: The Dokan Data Updater is not working when WooCommerce Conversion Tracking is activated.

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1731]
**Describe the bug**
When the `WooCommerce Conversion Tracking` plugin is activated, the data updater of Dokan is not working.

**To Reproduce**
1. Install and activate the WooCommerce Conversion Tracking plugin.
2. Try to click on the data updater of Dokan.
3. Nothing will happen and the updater will not run.

**Expected behavior**
The updater was supposed to trigger a pop-up and work properly.

**Environment:**
 - Dokan Version: [v3.7.1]
 - Dokan Pro Version: [v3.7.7]
 - WooCommerce Version: [v7.0.0]
 - WooCommerce Conversion Tracking: [v2.0.10]

**Comment by nurul-umbhiya** [comment]
Can you please create an issue under the WooCommerce Conversion Tracking repo? they include their scripts on every page and the SweetAlert library needs an update.
