### ISSUE TITLE
Sub Category on Dokan Product Category widget didn't work

### ISSUE THREAD

**Issue by Fayeakuzzamantonmoy** [weDevsOfficial/dokan#1739]
**Describe the bug**
The subcategory of the Product Category widget only works for the Dokan theme. Except for the Dokan theme you are unable to get those subcategories under the product categories widget.

**To Reproduce**
1. Enable the StoreFront theme first
2. Go to **WP Dashboard > Appearance > Widgets**
2. Please add **Dokan: Product Category**
3. Now navigate to the specific location where you add the widget.
4. The Sub Category is unavailable in the widget

**Expected behavior**
The sub-categories should be available under the main categories.

**Screenrecording**
https://www.loom.com/share/ec4fc5fc5be94141be0c9e734867f8b4

**Comment by myntillae** [comment]
Thank you for looking into this. Resolving it will be very helpful so this feature can be used on any theme.

**Comment by myntillae** [comment]
@nurul-umbhiya  Do I need to do an update to see the fixes on my website?
