### ISSUE TITLE
Vendor Category

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/dokan#176]
We should be able to categorize the vendors

**Comment by kjy112** [comment]
Is this planned for next release or at least for the Professional+ package?

**Comment by tareq1988** [comment]
This is planned, but not for the next release. Maybe after 2.8 is released, which is scheduled for next week.

Will be available from starter package.

**Comment by timwaring** [comment]
Did this ever get into the release?

**Comment by djm56** [comment]
Following up on this, did this feature get added or is being planned to be added?
Thanks

**Comment by saimonh3** [comment]
This feature has been added in Dokan Pro v2.9.7 and be available from the starter package.
