### ISSUE TITLE
Stripe Connect, same Stripe account for multiple vendors

### ISSUE THREAD

**Issue by ProRealCode** [weDevsOfficial/dokan#1772]
Hello, 
Is it possible that the Dokan system allows multiple vendors to use the same Stripe Connect acount (same "dokan_connected_vendor_id" and same "_stripe_connect_access_key")? I have that "issue" (2 different vendors that are connected with same Stripe Connect account), so I'm wondering if this option is intentional or related to a possible bug? and how it will impact the reports stats for each of the vendor? Thanks.

**Comment by nurul-umbhiya** [comment]
Technically this shouldn't be happing with stripe connect unless both of the vendors use the same stripe account. Have you migrated old data from one site to another or something similar where there is a chance to copy/duplicate one vendor's data to another? I would suggest you discount both vendor stripe accounts from the Vendor Dashboard payment settings page and instruct vendors to connect again. This should fix the issue. Let me know if you need further assistant.
