### ISSUE TITLE
Commission calculation is incorrect when changing the decimal separator to (,)

### ISSUE THREAD

**Issue by TanvirHasan19** [weDevsOfficial/dokan#1779]
### Description of the bug:

From the WooCommerce settings if we change the decimal separator (.) to (,) then the commission earning is not calculated correctly when uploading a new product from the vendor dashboard.

### How to reproduce

Please check this video to know how to reproduce the issue. https://www.loom.com/share/b117fbc3465f49dfaffa4027d671a982.

### Expected Behavior

The commission calculation should be exactly the same whether the client will use (.) or (,) as a decimal separator from the `WP dashboard -> WooCommerce -> Settings -> General -> Currency options -> Decimal separator`  

**System Status:**
Dokan: v3.7.8
Dokan Pro: v3.7.11
WordPress: v6.1.1
WooCommerce: v7.2.2

**Comment by devAsadNur** [comment]
We've removed the `Earnings` column from all over the product listing, adding and editing pages by following PRs: 
* https://github.com/weDevsOfficial/dokan/pull/1869
* https://github.com/weDevsOfficial/dokan-pro/pull/2319

So I'm closing this issue, as the earning calculation feature is no more existed.
