### ISSUE TITLE
dokan_get_store_info to update information

### ISSUE THREAD

**Issue by rexarvind** [weDevsOfficial/dokan#1789]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to update the store details received with dokan_get_store_info()

**Describe alternatives you've considered**
update_user_meta() of wordpress.

**Additional context**
No

**Comment by nurul-umbhiya** [comment]
There are a couple of hooks you can work with, for example, dokan_new_vendor, dokan_before_create_vendor, dokan_vendor_create_data, etc. Kindly check the codebase for available hooks.
