### ISSUE TITLE
[Reverse Withdrawal] The decimal value is being not updated from Total Collected option. 

### ISSUE THREAD

**Issue by YeasinArafat1998** [weDevsOfficial/dokan#1801]
**Describe of the bug**
If a payment has been made via reverse withdrawal and the amount is in decimal value, The decimal value has not been added to the **Total Collection** portion. Here is the screenshot: https://snipboard.io/Pflzsv.jpg

**To Reproduce**

1. Make a reverse withdrawal payment from the vendor dashboard with a decimal value like 46.23 or 50.21 and complete it.
2. Then navigate to WP-Admin→ Dokan→ Reverse Withdrawal menu you will see that payment has been made with the decimal value. But the **Total Collection** is not accepting the decimal value. 

**Expected behavior**
The **Total Collection** should accept the decimal value also. 

**Screenshot**
https://snipboard.io/7q3DRa.jpg

**Environment**
 - Dokan: [3.7.10]
 - WooCommerce: [7.3.0]
 - WordPress: 6.1.1

**Comment by nurul-umbhiya** [comment]
Fixed with https://github.com/weDevsOfficial/dokan/commit/01f3ee3c01a45b107538ee9613624f7ef2734d76
