### ISSUE TITLE
Store Categories filtering not showing proper results

### ISSUE THREAD

**Issue by lonifasiko** [weDevsOfficial/dokan#1802]
We've defined two store categories in our marketplace ('Eibar' and 'Ermua') We assign the store category when creating a new vendor profile.

We want to use these two store categories as a direct link, as a filter in the marketplace, so that users can click and only see a list of stores inside each category.

We understand that in order to show a list of stores inside the category 'Eibar', we should just redirect users to a URL like this: https://eramateko.eus/es/tiendas/?store_categories=eibar. The problem of this URL is that Dokan also shows in the list, stores that are inside the other category, 'Ermua'. WHY the hell is happening this? 

Moreover, if the already confused user wants to only show 'Eibar' stores, he has to select in that page category 'Eibar' and press button in the right (with the text 'Aplicar') to apply the filter (please check image: https://imgur.com/a/qMNyMd0). This is the only way Dokan only shows a proper list of stores inside 'Eibar' category. And last but not least: I've noticed that when pressing that filter button, a parameter named '_store_filter_nonce', associated with a random dynamic value, probably associated with session ID or whatever, is added to the URL, that can look like this: https://eramateko.eus/es/tiendas/?store_categories%5B%5D=eibar&_store_filter_nonce=8e0cf3d811. 

Could you please explain me why the initial simple and logical query does not work properly, needing to add a second parameter with a dynamic value (we cannot control as it changes between sessions)? It makes very much sense to have a direct link where users can access and see only stores under a concrete category, for example, from a menu/link in the marketplace.

Hope you can fix this or take it into account in future development, as it is a non-sense. 

Best regards, 
Miguel

**Comment by devAsadNur** [comment]
We're removing the nonce checking here after discussing it with @Mohaiminulislam1989 Bhai.

**Comment by lonifasiko** [comment]
Thanks very much guys, let's build a better Dokan together! 💪
--
Miguel Loitxate 'Lonifasiko'

Web <https://www.Lonifasiko.com/> | Twitter <https://twitter.com/Lonifasiko>
 | Facebook <https://www.facebook.com/Lonifasiko> | Instagram
<https://www.instagram.com/Lonifasiko/> | LinkedIn
<https://es.linkedin.com/in/miguelloitxatelonifasiko>
