### ISSUE TITLE
Option for dokan_get_new_post_status() to return 'draft'

### ISSUE THREAD

**Issue by mike-battaglia** [weDevsOfficial/dokan#1819]
## Currently
When a trusted vendor adds a new product, there are two pages in the process.

1. The new product page: /dashboard/new-product/
2. The edit product page: /dashboard/products/?product_id=0&action=edit

When the trusted vendor completes Page 1, the product is **_published_**, even though the vendor has not completed the critical details in Page 2 (such as shipping information).

## Problem
This results in products being published that may be incomplete.
_wp-content/plugins/dokan-lite/includes/functions.php_ 
```
/**
 * Get product status based on user id and settings
 *
 * @return string
 */
function dokan_get_new_post_status() {
    $user_id = get_current_user_id();

    // trusted seller
    if ( dokan_is_seller_trusted( $user_id ) ) {
        return 'publish';
    }

    // if not trusted, send the option
    $status = dokan_get_option( 'product_status', 'dokan_selling', 'pending' );

    return $status;
}
```

## Solution 1
The Admin should have an optional setting to chose if new product posts return 'publish' or 'draft.'

This is different from 'pending.' Pending requires the admin to approve before a product is published. Draft would allow the vendor to fully complete the product details before publishing it on their own, without further Admin action required.

## Solution 2
Include a hook in the plugin so that developers can write a filter to do achieve the same result, as discussed here:
[https://wordpress.org/support/topic/set-new-product-status-to-draft/#post-16499691](https://wordpress.org/support/topic/set-new-product-status-to-draft/#post-16499691)

**Comment by nurul-umbhiya** [comment]
@mike-battaglia we will be adding a new filter hook for the method dokan_get_new_post_status(), will let you know after we implement the hooks.

**Comment by mike-battaglia** [comment]
Thank you @nurul-umbhiya , but

`$status     = $is_trusted ? 'publish' : dokan_get_option( 'product_status', 'dokan_selling', 'pending' );`

should be

`$status     = $is_trusted ? dokan_get_option( 'product_status', 'dokan_selling', 'publish' ) : 'pending';

**Comment by nurul-umbhiya** [comment]
the existing implementation is ok, if a store is trusted (ie: Publish Product Directly settings is enabled for that vendor), then the product status will be publish, otherwise product status will be retrieved from the admin settings.

What you can do is: use `dokan_get_new_post_status` hooks and apply your custom logic from there. you'll get all the required data as hook parameters, eg: $status, $user_id and $is_trusted
