### ISSUE TITLE
Issue with the product rest api endpoint , in_Stock parameter not working (filtering the product data)

### ISSUE THREAD

**Issue by atmikbharat** [weDevsOfficial/dokan#1829]
https://wedevsofficial.github.io/dokan/#product-properties as per this documentation inside product properties it is clearly written that the products can be filtered using object in_stock=true/false(as it's boolean) when the request is made to http://dokan.test/wp-json/dokan/v1/products/ and we have also cross-checked everything it's not working please help us with a fix at the earliest.

**Comment by nurul-umbhiya** [comment]
We've confirmed this issue, We will release a fix soon.

**Comment by atmikbharat** [comment]
Please try to release an urgent fix , has been reporting this issue for more than a month! can see my tickets

**Comment by atmikbharat** [comment]
Can you please suggest what changes do we need to make if we want this to be working on our end , hope to receive your response at the earliest.
