### ISSUE TITLE
Allow us to enter the link of invoice for the vendor withdrawal part so it's invoice is visible in the withdrawal history

### ISSUE THREAD

**Issue by atmikbharat** [weDevsOfficial/dokan#1831]
Hi team , we have an urgent request kindly allow us to attach the invoices with vendor withdrawal part like you allow the withdrawal note, if you allow us to attach the attachment this would also work. Please, introduce this feature as vendors need invoices for the payments and it's not possible to mail the invoices of each month to the individual vendor. The admin can attach the invoice in the attachment once he/ she is approving the withdrawal.

**Comment by nurul-umbhiya** [comment]
@atmikbharat We are planning for a new Invoicing system, that will solve this issue. Till than, I'm closing this issue since we are not providing any quick fix for this.
