### ISSUE TITLE
Vendor withdrawl issue

### ISSUE THREAD

**Issue by atmikbharat** [weDevsOfficial/dokan#1839]
Hi Team,

We would like to inform you that as a multivendor itself means that a platform will be aggregating multiple brands on it's platform, so if the order is marked as unfulfilled due to the reasons like the vendor didn't update the product stock and the order was placed by the customer than in such cases the fines are imposed on the vendor but the issue is in the withdrawal segment there is no such option to mention the fine amount and the reason of fine , if your team can look into this it would be really a very great help and one more thing this fine should also be visible in repost statement just like it show the statement of completed orders and withdraws.

* Similar issue in Dokan Pro: https://github.com/weDevsOfficial/dokan-pro/issues/1171

**Comment by nurul-umbhiya** [comment]
@shashwatahalder01 we can use the reverse withdrawal feature to tackle this kind of situation. kindly create an enhancement for this.
