### ISSUE TITLE
Title string escape issue

### ISSUE THREAD

**Issue by oliviertassinari** [weDevsOfficial/dokan#1846]
**Describe the bug**

1. Go to the dokan vendor admin
2. Update the title to have an `&` (ampersand)

<img width="595" alt="Screenshot 2023-04-02 at 16 54 51" src="https://user-images.githubusercontent.com/3165635/229365746-7f0ff550-de75-4f46-89b4-3f3a293a056f.png">

3. Save
4. 💥

The value is recorded like this in the database:

<img width="726" alt="Screenshot 2023-04-02 at 16 54 46" src="https://user-images.githubusercontent.com/3165635/229365796-94ac282c-03c6-47ae-bc8c-1baad1e2ecd3.png">

The value is displayed like this for the admin:

<img width="489" alt="Screenshot 2023-04-02 at 18 17 49" src="https://user-images.githubusercontent.com/3165635/229365806-fe2c1e42-8796-4676-9792-48428d3abc64.png">

**Expected behavior**

I would expect:

<img width="569" alt="Screenshot 2023-04-02 at 16 52 43" src="https://user-images.githubusercontent.com/3165635/229366177-a7cdbebf-125e-4e7e-a7a0-6bddb085358d.png">

**Versions**

 - Dokan Version: 3.7.15
 - Dokan Pro Version: 3.7.17
 - WooCommerce Version: 7.5.1
 - Browser: all
 - Current Theme: Storefront 2.5.0

**Related**

https://stackoverflow.com/questions/44887191/how-to-keep-wordpress-from-changing-into-html-amp

**Comment by devAsadNur** [comment]
Admin can save unfiltered HTML. Vendors or shop managers can't do that. That's the reason behind this issue. The issue has been reported by so many users to the Wocommerce Github repo. Here is the issue link: https://github.com/woocommerce/woocommerce/issues/25243
