### ISSUE TITLE
Edit product editor is too limited

### ISSUE THREAD

**Issue by oliviertassinari** [weDevsOfficial/dokan#1847]
**Is your feature request related to a problem? Please describe.**

The product editor on vendor's side is a lot more limited than the one available on the admin side,

vendor:

<img width="714" alt="Screenshot 2023-04-02 at 20 00 53" src="https://user-images.githubusercontent.com/3165635/229370833-51ad7cd9-002b-4233-bdfa-322576ae3761.png">

admin:

<img width="946" alt="Screenshot 2023-04-02 at 20 08 41" src="https://user-images.githubusercontent.com/3165635/229370863-45784723-4a16-4c54-b21d-664221e8fc9b.png">

**Describe the solution you'd like**

Have at least the ability to pick h1, h2, p, and to see the source code:

https://github.com/WordPress/WordPress/blob/a415951b8f85d53739e53525825af9b646078bf7/wp-includes/script-loader.php#L524

**Describe alternatives you've considered**

Write my custom textarea input, with markdown.

```php
    <div class="dokan-form-group">
      <label for="wccaf_description" class="form-label"><?php esc_html_e('Description', 'dokan-lite'); ?></label>
      <?php dokan_post_input_box($post_id, 'wccaf_description', [], 'textarea'); ?>
    </div>
```

**Comment by fisher2470** [comment]
would highly recommend we don't allow vendors to use h1 tags, the H1 tag should in most cases be the product title, vendors will misuse the h1 tag throughout text area if given access to it

**Comment by oliviertassinari** [comment]
Makes sense, the problem for me started with a vendor who wanted to add an h2.

**Comment by fisher2470** [comment]
Additionally, this improvement is needed in order for the RankMath integration to work properly on the vendor side. Currently a vendor is incapable of adding keywords to at least one heading, and it doesn't appear rankmath recognizes the description length or keyword usage in the product description either.

**Comment by oliviertassinari** [comment]
I'm late to the party, but thanks for fixing this, it looks good now.

Vendor side:
<img width="527" alt="SCR-20241125-bmuu" src="https://github.com/user-attachments/assets/958fd4f3-55ce-4b07-bd66-e6a055e86e5a">
