### ISSUE TITLE
Dokan / Settings / Shipping - freeze on save

### ISSUE THREAD

**Issue by tomektomczuk** [weDevsOfficial/dokan#1861]
**Describe the bug**
Dokan Settings Shipping - when you save settings it's freeze

**To Reproduce**
1. Go to Dokan Settings
2. Click on Shipping
3. Add your entries and save
4. See error in the console (print screen attached)

**Environment (please complete the following information):**
 - Dokan Version: [3.7.16]
 - Dokan Pro Version: [3.7.18]

**Additional context**
![dokan2](https://user-images.githubusercontent.com/40096666/231473434-a24093a1-6336-483e-a850-5e2fde468707.png)

**Comment by devAsadNur** [comment]
@tomektomczuk Thaks for reporting the issue. But, the issue can't be reproduced from our side. Maybe the issue exists only on your site. Please contact support and tell them to create a client issue. 

Also, your recommended solution is temporary. It will be reverted after updating `Dokan`.
