### ISSUE TITLE
[ONE LINE EDIT] Load_Order_Items() in Ajax.php (dokan-lite) does not use correct templating for refunds

### ISSUE THREAD

**Issue by gosixl** [weDevsOfficial/dokan#1880]
Uses include( DOKAN_PRO_DIR . '/templates/orders/views/html-order-items.php' );
Should instead use dokan_get_template_part()

This forces using dokan's template instead of the one in the child theme, so is currently displaying inconsistent numbers for refund requests

**Comment by aihimel** [comment]
@Mohaiminulislam1989 
Clarification required. Please let me know if this bug should be solved.
Thanks

**Comment by aihimel** [comment]
After discussing with @nurul-umbhiya, this bug needs to be fixed.
