### ISSUE TITLE
In Dashboard > Orders: Add code hook to allow filtering out of order listing by order status

### ISSUE THREAD

**Issue by gosixl** [weDevsOfficial/dokan#1881]
I don't want vendors to see orders that are pending payment (common stripe express issue) or failed. 

Currently there is no hook made available in dokan-lite/includes/Dashboard/Templates/Orders.php around line 140

Which reads from all() in dokan-lite/includes/Order/Manager.php (no hook there either)

**Comment by nurul-umbhiya** [comment]
https://github.com/weDevsOfficial/dokan/pull/1262

**Comment by gosixl** [comment]
Do we need to wait for author reply in the PR? Can we not just go ahead

**Comment by nurul-umbhiya** [comment]
Fixed Here:
https://github.com/weDevsOfficial/dokan/commit/52bb9c6ee4e929f9a69e5a345b728baa378da89e
