### ISSUE TITLE
Allow adding metadata to Stripe Express payment intent metadata 

### ISSUE THREAD

**Issue by gosixl** [weDevsOfficial/dokan#1882]
In create_payment_intent() in dokan-pro/modules/stripe-express/includes/Controllers/Checkout.php

At the PaymentIntent::create() line, Stripe documentation allows for a metadata field to enrich the information about payments. Would be great if you refactored to something like the below (bold is new) and added a hook to allow the admin dev to add more metadata about payments.

 // Loop over $cart items
  **$prods = [];
  foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
      array_push($prods, $cart_item['data']->get_title());
  }**
  
  $payment_intent = PaymentIntent::create(
      [
          'amount'               => Helper::get_stripe_amount( $amount, strtolower( $currency ) ),
          'currency'             => strtolower( $currency ),
          'payment_method_types' => Helper::get_enabled_payment_methods_at_checkout( $order_id ),
          'capture_method'       => Settings::is_manual_capture_enabled() ? 'manual' : 'automatic',
          **'metadata' => [
              'user_id' => get_current_user_id(),
              'site' => get_site_url(),
              'prods' => json_encode($prods),
              'email' => WC()->cart->get_customer()->get_billing_email(),
          ]**
      ]
  );

**Comment by nurul-umbhiya** [comment]
We are already assigning metadata on payment intent when payment is successful: see this file: modules/stripe-express/includes/Processors/Payment.php, method name: generate_data()
We will investigate and try to add metadata for all payment intent.

**Comment by gosixl** [comment]
Hi Nurul, thank you for pointing that out.
I think metadata for unsuccessful payments can be just as informative as for successful ones.
Kind regards,
Gos
