### ISSUE TITLE
[Single Store Page]: The Store Product Category widget does not show the parent category to be collapsed by default.

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1887]
**Describe the bug:**
The `Dokan: Store Product Category` widget's parent categories are not collapsed by default as shown in [this screenshot](https://snipboard.io/yGjkbX.jpg).

**To Reproduce:**
1. Add the `Dokan: Store Product Category` widget to the `Single Store Sidebar`.
2. Add a product to a store and assign a child category to it.
3. When the single store page is first visited, the parent categories are not collapsed.

**Expected behavior:**
The `Dokan: Store Product Category` should show the parent categories to be collapsed when the single store page is visited. The parent categories should expand only when the user clicks on them.

**Screenshots:**
https://snipboard.io/yGjkbX.jpg

**Environment:**
Dokan: [v3.7.18]
WooCommerce: [v7.7.0]
WordPress: [v6.2.1]

**Comment by KingMilli75** [comment]
1. In addition to this the mobile view behaviour should be identical not only desktop view. So, click  should open the parent and display the child. On large store with 10k products now its impossible to see on the mobile the product category as its simply to large when its full expanded. 

2. Now to make this part even better as a user experience the menu should be able to dynamic integrate into the WP menu structure. A picture here below will show what we mean by this. 

![viber_image_2023-05-16_12-20-14-917](https://github.com/weDevsOfficial/dokan/assets/101454545/cfa57a4d-76a4-477c-84e8-fc9bd53d4444)

The current menu under Category in this part is pulled from WP menu structure. It would be nice that the widget recognises the store it is in and display the Category menu as per shop not like now made manually. For this part we use woodmart theme from Xtemos as its one of the best ones to integrate. 

Cheers

**Comment by devAsadNur** [comment]
In the `WooCommerce: Product Categories List` widget, the product categories and sub-categories remain expanded by default. We implemented the same behavior to our `Dokan: Store Product Category` widget.

As per discussion with @Mohaiminulislam1989 Bhai, we're not implementing this enhancement. So, I'm closing the issue.

**Comment by KingMilli75** [comment]
Dear Sirs,

This feauture is important for large shops. It's simply to display product when your product category tree has 10 category and maybe 10 sub cat.

But with a shop of let's say 15k products you can not have default a expanded cat tree this in we have 25 category and about 60 sub categories. This would mean on the mobile view when expanded a endless scroll.
