### ISSUE TITLE
Jet Accordion Widget for Elementor doesn't open when Dokan is Activated

### ISSUE THREAD

**Issue by smile00000** [weDevsOfficial/dokan#1895]
**Describe the bug**
Jet Accordion Widget for Elementor doesn't open when Dokan is Activated

**To Reproduce**
1. Go to Elementor Editor
2. Add Jet Accordion Widget
3. Add a few Accordion Items
4. See error the Jett Accordion items won't open

**Expected behavior**
Jet Accordion Widget items should open.

**Screenshots**

**Environment (please complete the following information):**
 - Dokan Version: 3.7.19
 - Dokan Pro Version: (Not installed, but make sure it works with Pro as well)
 - Elementor Version: 3.13.3
 - Elementor Pro Version: 3.13.2
 - WooCommerce Version: 7.7.0
 - Browser: Safari Version: 16.4
 - Current Theme: Elementor Hello Version: 2.7.1

**Additional context**
The behavior works as expected only when Dokan is disabled.

**Comment by devAsadNur** [comment]
@smile00000 Thanks for reporting the issue. But we can't reproduce the issue from our end. It might be generated to your site from any other 3rd party plugins. Please check out once again by disabling other plugins except `WooCommerce`, `Elementor`, `Elementor Pro`, and `Dokan`.

If you still find the issue, please make sure to look at the browser console, if there is any error. Feel free to contact our support with screenshots or screen records. Thanks again.
