### ISSUE TITLE
Conflict Dokan with LiteSpeed Cache Plugin

### ISSUE THREAD

**Issue by amirsheikhhassan** [weDevsOfficial/dokan#1927]
Hi,
After activating the [LiteSpeed Cache Plugin](https://wordpress.org/plugins/litespeed-cache/) next to the dokan plugin, a critical error has been caused on the website and the website will stop and without any js / php errors to be displayed until the plugin is deactivated.
It was returned only empty dom with only empty head and body tag when i was activated the litespeed cache plugin.
Is there a solution to fix this problem ?

**Comment by shohag121** [comment]
Hello @amirsheikhhassan,

Without the error message or log, it is impossible to know where things have gone wrong. 
Generally, LightSpeed Cache Plugin does not have any conflict with the Dokan.

Can you please provide the error log or message related to the conflict?

In the meantime please contact [Support](https://wedevs.com/account/tickets/) with website credentials. They will be able to help after checking your website.

Thank You.
