### ISSUE TITLE
[Order]: Stock is not updated when a child order's order status is changed to Canceled.

### ISSUE THREAD

**Issue by J-H-Mojumder** [weDevsOfficial/dokan#1931]
**Describe the bug**
When the `order status` of a `child order` is changed to `canceled`, the stock amount is not updated.

**To Reproduce**

1. Steps to reproduce the behavior:
2. Set the stock of products from two vendors.
3. Include those two products in a single order.
4. See the order details, the stock will be decreased.
5. Cancel one of the child orders from the associated vendor's dashboard.
6. The stock will not be increased.

**Expected behavior**
The stock is supposed to be `increased` when the order is `canceled`.

**Screenshot:**
https://snipboard.io/H0wBjF.jpg

**Environment:**
 - Dokan Version: [ v3.7.21]
 - WooCommerce Version: [ v7.8.2]

**Comment by devAsadNur** [comment]
The issue has been already fixed in the latest `develop` branch.
