### ISSUE TITLE
translations issue

### ISSUE THREAD

**Issue by sevenseconds777** [weDevsOfficial/dokan#1940]
It is that only some translations are not reflected.

The version about 3 months ago was translated.

I re-translate every update.

Please see the attached file.

https://sevenseconds.xsrv.jp/mps-simple/img/tr01.png
https://sevenseconds.xsrv.jp/mps-simple/img/tr02.png

I was able to translate it before, but it’s a pity that it can’t be done with the update

**Comment by aihimel** [comment]
@sevenseconds777 
Thanks for reaching out. These translation issues will get solved in the next release. Thanks for your co-operation.
