### ISSUE TITLE
How do I quickly disable the feature that restricts vendors from purchasing their own products in Dokan Lite 3.7.24? 

### ISSUE THREAD

**Issue by ashtonlclark** [weDevsOfficial/dokan#1950]
Yesterday, Dokan Lite (3.7.24) released the following new feature:

"Restrictions added for vendors to review and purchase their own products. Previously, vendors could purchase and post reviews for their own product. Which is not logical and could manipulate the search results of a product in a marketplace. With this update, vendors will not be able to purchase or post reviews for their own product." 

I want my vendors to be able to purchase their own products.

1. How can I quickly disable this feature - is there code that I can add to disable this new feature quickly?
2. Can you add an option in the Dokan Lite Admin settings to disable this feature?

Thanks in advance for your help.

**Comment by aihimel** [comment]
@tanjiralmamun,
Kindly consider the following question.

* Is this a popular client request?

@Mohaiminulislam1989,
Kindly consider the following questions.

* Should you pursue this feature request
* Should add a hook to disable this feature
* Should we add admin settings to enable disable this feature

Thanks

**Comment by tanjiralmamun** [comment]
@aihimel,
The most popular request was to prevent vendors from purchasing and reviewing their own products and stores, which was already implemented.

If any users want to enable the feature again for their specific marketplace needs, we can provide the flexibility through a hook like below:

`#-- Enable Vendors Own Products Purchase --#
remove_filter( 'woocommerce_is_purchasable', 'dokan_vendor_own_product_purchase_restriction', 10, 2 );`

`#-- Enable Vendors Own Products Review --#
remove_filter( 'woocommerce_product_review_comment_form_args', 'dokan_vendor_product_review_restriction' );`

Now, it depends on @Mohaiminulislam1989 bhai, whether he would suggest providing any admin settings or not.

**Comment by Mohaiminulislam1989** [comment]
@ashtonlclark Thank you for your request and creating this issue. I am sorry that we suddenly removed this feature to purchase own store product. The reason we got this decision is, we thought it is not fair to purchase my own product and put a review for his own product. 
@aihimel Thank you for your question.
@tanjiralmamun thank you for your message. I hope your reply could solve @ashtonlclark's problem.

**Comment by ashtonlclark** [comment]
Thank you.

Removing the filter works for me. I can confirm that the code works. Thanks for the quick reply.

Thanks,

Ashton
________________________________
