### ISSUE TITLE
Duplicate suborders for the same order

### ISSUE THREAD

**Issue by danielbreves** [weDevsOfficial/dokan#1987]
**Describe the bug**
Dokan seems to have created duplicate suborders for the same order. Even though the total amount only includes the sum for one subset.

**To Reproduce**
It's unclear how to reproduce, but I noted for one group of suborders the user had a slightly different email address and full name.

The parent order was created via Paypal. I received Order Failed notifications for all orders including the parent #29452, but also one additional successful New order notification for the parent #29452. The payment in paypal for the parent order succeeded.

**Expected behavior**
No duplicate suborders should be created.

**Screenshots**
Note the capital Ash for some suborders. The duplicate orders were cancelled manually by me after the fact.
![Screenshot 2023-09-01 at 9 41 06 am](https://github.com/weDevsOfficial/dokan/assets/2517811/b0948a00-8561-4901-aadb-85aeaf39cc14)

**Environment (please complete the following information):**
 - Dokan Version: 3.8.1
 - WooCommerce Version: 8.0.3
 - WooCommerce PayPal Payments Version: 2.2.2
 - Current Theme: Store Front

**Additional context**

**Comment by nurul-umbhiya** [comment]
@danielbreves Have you enabled the HPOS feature?

**Comment by nurul-umbhiya** [comment]
A fixed has been pushed. https://github.com/weDevsOfficial/dokan/commit/243ce92e7206a6638cec216bb4de3ecf611419de

**Comment by danielbreves** [comment]
> Have you enabled the HPOS feature?

I have not.

Thanks for the quick fix!
