### ISSUE TITLE
Show vendor name under their products

### ISSUE THREAD

**Issue by Sophivorus** [weDevsOfficial/dokan#23]
The name of the vendor should be visible under each one of their products, both when viewing them in the main store page, as when viewing the product individually. Something like "Sold by {name of the store}" The vendor name should of course link to their store.

This feature is common to all other multi-vendor plugins (WCMP, WCVendors, Product Vendors and Yith) so there are probably WooCommerce hooks in place to make this feature easy to implement. Some of these plugins also allow you to configure what text to show before the name of the vendor, so that you may change it from, say, "Sold by Joe" to "Brought to you by Joe".

If there's some markets where it might not be desirable to display the vendor name under every product, then there should be an option in the Dokan Settings to toggle it, but the feature should definitely be an option.

**Comment by jgajera** [comment]
Check out these resources -
1. https://wedevs.com/support/topic/display-product-vendors-name/
2. https://nayemdevs.com/display-vendor-name/
3. https://stackoverflow.com/questions/43632297/how-to-show-store-name-on-the-product-thumbnail-in-dokan-multivendor-plugin-by-w

**Comment by wptricks** [comment]
please help me to :
show number of product vendor in dokan

**Comment by saimonh3** [comment]
@wptricks Did you mean, number of products of a vendor? If so, you can use function like this. Thanks
`
function dokan_get_number_of_products_of_vendor( $vendor_id ) {
    $vendor          = dokan()->vendor->get( $vendor_id );
    $vendor_products = $vendor->get_products();

    return $vendor_products->found_posts;
}

dokan_get_number_of_products_of_vendor( $vendor_id );
`

**Comment by riteshghimire9090** [comment]
How to show vendor phone number in vendor info tab in product page dokan vendor?
