### ISSUE TITLE
bug: in product edit with wpml

### ISSUE THREAD

**Issue by DaddyMadu** [weDevsOfficial/dokan#233]
while using wpml with arabic language (or any other language than the default one)

after translating categories and tags to the new language

add a new product as vendor with whatever language you like it doesn't matter choose product tag and product category

save the new product

go to vendor dashboard, change your language and edit the product

you will find that the category and tag is wiped and you have to select them again and click save, if you saved

and then went to vendor dashboard and changed to default language and edited the same product again, you will find that the category and tag is wiped again, and you have to select them again

short story: you have to edit any product with the language you saved it with otherwise you will have to save select them and save again but if you changed your language and tried to edit you will need to select them again

i can reproduce the error on a fresh wp with fresh woo-commerce and just dokan with wpml and of course dokan wpml is installed

**Comment by alamgircsebd** [comment]
Hello @DaddyMadu 

Please use latest Dokan WPML plugin from here https://github.com/weDevsOfficial/dokan-wpml/releases/tag/v1.0.3 hope issue will resolved. 

Thanks
