### ISSUE TITLE
Allow vendors to write a description of their store

### ISSUE THREAD

**Issue by Sophivorus** [weDevsOfficial/dokan#24]
Vendors should be able to write some free-form text about their store in their Settings > Store, and that text be displayed under their store header, and also probably under the Vendor Info section of their products.

**Comment by Sophivorus** [comment]
@rafsuntaskin I'm ready to send a pull request for this, but before I do I'd like to know if this feature would be welcome, or not.

**Comment by jgajera** [comment]
@Sophivorus yes please! It wouldn't hurt :) 👍

**Comment by ManigandanRaamanathan** [comment]
Any update on this issue?

**Comment by saimonh3** [comment]
Similar feature has been added in Dokan Pro. Thanks
