### ISSUE TITLE
Get shop details from user ID

### ISSUE THREAD

**Issue by ttremain** [weDevsOfficial/dokan#240]
My client has asked me to make a custom widget.

So I already have a list of users, I need to check each one to see if they have a shop, I can do this by seeing if they have the Role of Seller.
If they do, how to I get the shop details (name, permalink) from there? 
Is there a get_shop_from_user_id() function, or similar?

**Comment by CasperBraske** [comment]
Check whether user is a seller :
[dokan_is_user_seller( $user_id );](https://github.com/weDevsOfficial/dokan/blob/master/includes/functions.php#L57)

To get store info:
[dokan_get_store_info( $seller_id );](https://github.com/weDevsOfficial/dokan/blob/master/includes/functions.php#L1128)

**Comment by CasperBraske** [comment]
Not tested, but I thing you can get better info from:
[Dokan_Vendor::get_shop_info();](https://github.com/weDevsOfficial/dokan/blob/f2b30d1c5ba9dea1953d6dceb8d53554e378d81d/includes/class-vendor.php#L184)

**Comment by ttremain** [comment]
Wonderful!  I spent quite some time trying to find this...  Thank you greatly!

**Comment by ttremain** [comment]
I'm still unable to find the shop permalink.  Am I just missing it?

**Comment by CasperBraske** [comment]
Have a look on the files I linked.
On Dokan_Vendor, you have the method "get_shop_url".
It's not that hard. Just search the repo for "[url](https://github.com/weDevsOfficial/dokan/search?l=PHP&q=url&type=)", "[link](https://github.com/weDevsOfficial/dokan/search?l=PHP&q=link&type=)" etc.

**Comment by CasperBraske** [comment]
The method uses `dokan_get_store_url( $seller_id );`.

**Comment by sabbir1991** [comment]
@ttremain, you can also use like 

`
$vendor = dokan()->vendor->get( $vendor_id );
$shop_name = $vendor->get_shop_name();
$shop_url = $vendor->get_shop_url();
$shop_info = $vendor->get_shop_info();
`
