### ISSUE TITLE
Parent order status is not changing with the change of sub-order status

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#253]
When a parenting order has sub-orders, the parent order remains on-hold or in processing mode. Even if both sub-orders are cancelled. But the status changed to completed when the suborders are completed.

**Comment by sabbir1991** [comment]
Resolved

**Comment by pratiweb** [comment]
I have same issue could you help me ?

**Comment by kapilpaul** [comment]
@pratiweb please update the dokan-lite to latest version.

**Comment by pratiweb** [comment]
@kapilpaul I have dokan pro starter edition. Will it work on this ?

**Comment by kapilpaul** [comment]
yes, this will work. Please update both versions (dokan-lite and dokan-pro)
