### ISSUE TITLE
Dokan removes custom column added by different plugin from Order List Table.

### ISSUE THREAD

**Issue by iamdharmesh** [weDevsOfficial/dokan#254]
Dokan is using `dokan_admin_shop_order_edit_columns` function for add custom columns to order list table. In starting of function it define `$columns = array();` without care of existing columns and then add default WC columns along with Dokan's custom column. So, if any third party plugin adds custom column in order list table then it will get removed by dokan.

So, desired solution for now is that instead of define blank array and add column into that you can just add dokan's custom columns to `$existing_columns`

Like this:
```
function dokan_admin_shop_order_edit_columns( $existing_columns ) {
    if ( WC_VERSION > '3.2.6' ) {
        $existing_columns['seller']           = __( 'Vendor', 'dokan-lite' );
        $existing_columns['suborder']         = __( 'Sub Order', 'dokan-lite' );
    } else {
        $existing_columns['seller']        = __( 'Vendor', 'dokan-lite' );
        $existing_columns['suborder']        = __( 'Sub Order', 'dokan-lite' );
    }
    return $existing_columns;
}
```
Let me know if you need any other information.

Thanks and regards,
Dharmesh

**Comment by sabbir1991** [comment]
Hi, 
Thanks for reporting this issue. We will fix this issue in next update
