### ISSUE TITLE
Settings Page Issues

### ISSUE THREAD

**Issue by tareq1988** [weDevsOfficial/dokan#271]
**Typo:**
![](http://tareq.in/RTdOuS+)

**SMS gateway settings aren't showing:**
![](http://tareq.in/70FOUe+)

**Add default value:**
![](http://tareq.in/FB42XH+)
![](http://tareq.in/Wy5Gek+)

**Comment by saimonh3** [comment]
SMS gateway settings aren't showing:
https://github.com/weDevsOfficial/dokan/pull/268
https://bitbucket.org/wedevs/dokan-plugin/pull-requests/132/refactor-sms-verification-make-some/diff

**Comment by saimonh3** [comment]
This issue will be fixed via this PR
https://bitbucket.org/wedevs/dokan-plugin/pull-requests/134/refactor-dokan-settings-fields-make-some

**Comment by sabbir1991** [comment]
Resolved
