### ISSUE TITLE
create costum view order btn

### ISSUE THREAD

**Issue by Arsintorabi** [weDevsOfficial/dokan#281]
i want make a button for display orders and get nonce security .

my code : 
`<a class="dokan-btn dokan-btn-default dokan-btn-sm tips" href="<?php print site_url(); ?>/dashboard/orders/?order_id=<?php echo $ord['order_id'];?>&_wpnonce=<?php echo wp_create_nonce('view-'.$ord['order_id']); ?>" data-toggle="tooltip" data-placement="top" title="" data-original-title="نمایش" ><i class="fa fa-eye">&nbsp;</i></a>`

**Comment by Arsintorabi** [comment]
i found this way: 
`$the_order=wc_get_order($ord['order_id']);
 echo '<a class="dokan-btn dokan-btn-default dokan-btn-sm tips" href="' . wp_nonce_url( add_query_arg( array( 'order_id' => dokan_get_prop( $the_order, 'id' ) ), dokan_get_navigation_url( 'orders' ) ), 'dokan_view_order' ) . '"><i class="fa fa-eye">&nbsp;</i></a>'; `

**Comment by sabbir1991** [comment]
You can use like this.
```$the_order = wc_get_order( $order_id );```
```echo '<a href="' . wp_nonce_url( add_query_arg( array( 'order_id' => dokan_get_prop( $the_order, 'id' ) ), dokan_get_navigation_url( 'orders' ) ), 'dokan_view_order' ) . '"><strong>' . sprintf( __( 'Order %s', 'dokan-lite' ), esc_attr( $the_order->get_order_number() ) ) . '</strong></a>';```
