### ISSUE TITLE
Vendors currently not able to edit products that was created and assigned to them by admin

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#285]
Vendors currently not able to edit products that was created by admin and was assigned to them by admin.  It contains invalid permalink* and when clicking edit link of that item from vendor account redirects to a page that is 404 not found.

**Comment by sabbir1991** [comment]
Hi,
I didn't find such kind of problem. I am creating a product from admin and then assign this product for a specific vendor and then I am trying edit this product from vendor dashboard. I didn't get any 404 page. All things working fine.

Can you specify which version you are using? and can you try again by saving permalink settings from admin settings?

**Comment by ManigandanRaamanathan** [comment]
Now all my product not able to edit. Even the one created from the vendor dashboard after fresh login. 
images below:- please check the urls on them and their output

![screenshot 77](https://user-images.githubusercontent.com/22089729/41740143-b928721e-75c9-11e8-98b1-f393712925c0.png)

![screenshot 78](https://user-images.githubusercontent.com/22089729/41740162-bfda461e-75c9-11e8-802a-84b0ffbfc1ac.png)

**Comment by ManigandanRaamanathan** [comment]
I'm using dokan 2.8.1

**Comment by ManigandanRaamanathan** [comment]
Found that culprit bug. It has to do with the permalink. Just changed the dokan permalink structure custom base to: /shop/
