### ISSUE TITLE
How to get the Store SEO meta keywords in Rest API vendor list?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#290]
How to get the Store SEO meta keywords in Rest API vendor list output when call the get store list endpoint?

**Comment by ManigandanRaamanathan** [comment]
@sabbir1991  I found the fix for this enhancement. The developer have already created the codes to fetch the Store SEO but did not mention it on the api endpoint: The fix as below:-

Perform changes in includes/class-vendor.php
//Add new function in :-
    public function get_store_seo() {
        return $this->get_info_part( 'store_seo' );
    }

//And add this line under the line 100
'store_seo'				=> $this->get_store_seo(),

and it returns the store seo data when call the endpoint

**Comment by sabbir1991** [comment]
SEO meta has already been added in pro version in REST API.
