### ISSUE TITLE
Google map not loading in vendor page

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#292]
Facing issue on google map location on vendor page. Already registered the map api key from google in admin panel. Below screenshot:-

![capture3](https://user-images.githubusercontent.com/22089729/41807936-2d92e19e-7709-11e8-9f91-7d1f1ba481e3.PNG)

**Comment by sabbir1991** [comment]
Hi, 
Please set your google map API correctly in Dokan settings page form back end 
Then the map loaded automatically in this section 

<img width="1280" alt="screen shot 2018-06-24 at 9 56 35 pm" src="https://user-images.githubusercontent.com/2692939/41820843-d40f352c-77f9-11e8-9c71-c776436756b3.png">
