### ISSUE TITLE
View active vendors and pending

### ISSUE THREAD

**Issue by HenryKenya** [weDevsOfficial/dokan#3]
Hey guys.
Great plugin. Currently testing it out on a client's new site so am using the free version of dokan.
I have a few questions'

1. Is there a way in which the super-admin can approve vendors from the wp dashboard? Currently, I think it is set such that a new vendor automatically becomes active.
2. Can one view the list of all vendors (active and pending) or is that just a pro feature?

**Comment by rafsuntaskin** [comment]
Hi,

1. You can control whether new Vendors can sell or not immediately after registration. All sellers can access the dashboard but if they are not allowed to upload products they can't sell.
Goto Dokan > Settings > Selling option :
<img width="649" alt="screen shot 2017-03-19 at 8 10 53 am" src="https://cloud.githubusercontent.com/assets/7523321/24077570/ebc60154-0c7b-11e7-9bee-15e3694cf223.png">

You can then again manually Enable or Disable as needed from your Wordpress Admin > Users > User profile :
<img width="840" alt="screen shot 2017-03-19 at 8 21 14 am" src="https://cloud.githubusercontent.com/assets/7523321/24077599/13eda60e-0c7d-11e7-9986-ab3e6ac000c7.png">


2. Yes, we have it as a pro feature.
