### ISSUE TITLE
Invalid report summary and no graphs generating

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#301]
I'm making orders using rest api using the latest rest api code fix. The report summary only display the first order's information instead of all the orders.
Currently I have made a total of 3 Orders with amount 300+. But the report for the month's sales and sale by day shows only the first order details as summary which is incorrect. And there is no graphs generating.

Below proof of 3 orders in the vendor's account dashboard:-
![capture19](https://user-images.githubusercontent.com/22089729/41935030-f590c324-79ba-11e8-8b97-a3f55bfb767b.PNG)

Below shows the report tabs invalid values:-
![capture20](https://user-images.githubusercontent.com/22089729/41935091-228dc624-79bb-11e8-8bea-893641c9addd.PNG)

![capture21](https://user-images.githubusercontent.com/22089729/41935159-4ff8d9aa-79bb-11e8-8f33-f71e9fdac4fa.PNG)

**Comment by sabbir1991** [comment]
Already fixed
