### ISSUE TITLE
Custom order status not displaying well after selection/assigning in vendor dashboard

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#302]
Hi, I'm using custom order status in my wordpress, It is working fine for assigning the status via the vendor dashboard. But the problem is that it is not visible to the user once the custom order status is selected by the user. After assigning the custom status, the complete order icon in the button from order list for the particular order is missing

Below shows the custom order status "Ready for Pickup":-
![capture22](https://user-images.githubusercontent.com/22089729/41935321-d0559606-79bb-11e8-9584-e859f9d19af6.PNG)

Below is how it looks after assigning/setting the custom order status:-
![capture23](https://user-images.githubusercontent.com/22089729/41935408-2f8584b0-79bc-11e8-9b32-45f8720e6591.PNG)

After assigning the custom status, the complete order icon in the button from order list for the particular order is missing:- 
![capture24](https://user-images.githubusercontent.com/22089729/41935443-4d5f6190-79bc-11e8-972f-6b9a8719b697.PNG)

**Comment by saimonh3** [comment]
@ManigandanRaamanathan How did you add custom order status? Can you please forward the code sample? Thanks

**Comment by ManigandanRaamanathan** [comment]
Using yith custom order status plugin

**Comment by saimonh3** [comment]
It's not fully compatible with dokan, you need to make it compatible. @ManigandanRaamanathan

**Comment by ManigandanRaamanathan** [comment]
How to make it compatible?

**Comment by saimonh3** [comment]
@ManigandanRaamanathan either you or the yith custom order status plugin author :) Thanks

**Comment by ManigandanRaamanathan** [comment]
How should I make compatible my self? Any code or requirements?

**Comment by 2dkazi** [comment]
Hi I am also facing the same issue and looking for a solution is you got a solution if yes please share with me if no what is the possibility @ManigandanRaamanathan

**Comment by 2dkazi** [comment]
@saimonh3 can you please help for making it compatible?

**Comment by ManigandanRaamanathan** [comment]
@2dkazi I don't have the solution yet. If you have the solution please share. TQ.

**Comment by 2dkazi** [comment]
I have one developer he ready to solve this issue but it will charge 3000 Rs (Indian Rupee). @ManigandanRaamanathan what to do now thinking this only here is my Mobile number 8898849266.lets connect to WhatsApp and solve this issue together.
