### ISSUE TITLE
Needed a page for administrators to view a particular vendors account sales and withdrawals details

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#304]
Needed a page for administrators to view a particular vendors account sales and withdrawals details. Currently the admin does not have any option to view all the transaction between a vendor.  (For the admin to view a complete report on transaction of a particular vendor including withdrawal/paid details)

Moreover, I'm also requesting you guys to add a manual options for the admin to key in the vendor payment details whenever the admin paid the vendors directly or using external payment methods.

**Comment by nurul-umbhiya** [comment]
This feature has been added. So I'm closing this issue.
