### ISSUE TITLE
Need additional columns in admin report > All log (Date and Product and withdraw details)

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#305]
Need additional columns in admin report > All log (Date and Product and withdraw details).

Currently it only shows :-
Order | Vendor | Order Total | Vendor Earning | Commision | Status
Very limited options
![capture18](https://user-images.githubusercontent.com/22089729/41968325-a37ae5a2-7a36-11e8-9b42-883c0545d8c6.PNG)

But what we need is (Taken from WC Vendors):-
![capture16](https://user-images.githubusercontent.com/22089729/41968159-23fce348-7a36-11e8-8a83-ae20d40011c1.PNG)

Must allow the table to sort based on column header, and must provide options such as paid and unpaid and search and fields for data, products.s in order, paid or not status and paid data and reference.

With this, dokan can become more powerful and will stand out in the market.

**Comment by Mohaiminulislam1989** [comment]
We have already updated this feature.
