### ISSUE TITLE
How do administrator view a particular vendor balance sales/payable amount?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#312]
How do administrator view a particular vendor balance sales amount? Currently after the administrator approve withdraw request, the admin doesnt know the balance that the admin owe the vendor? We need a statement page for the administrator to view a complete progress report on sales and withdrawals of vendor in admin. Else it is getting very hard for us to manage the vendors sales and payables.

**Comment by saimonh3** [comment]
@ManigandanRaamanathan Admin can see the vendor available balance from the Vendors menu under Dokan. All he has to do is to just click on the vendor's name.
![annotation on 2018-6-2](https://user-images.githubusercontent.com/13016829/42226923-1413185a-7f02-11e8-8bfe-6b0a23133ced.png)
![annotation on 2018-6-2 1](https://user-images.githubusercontent.com/13016829/42226978-3414ad94-7f02-11e8-8a45-e5e220022760.png)

**Comment by ManigandanRaamanathan** [comment]
@saimonh3  is there a page to view statement of a specific vendor from admin for the administrator?  A statement that shows the vendors sales and withdraw details with date options and sortable options?

**Comment by ManigandanRaamanathan** [comment]
@saimonh3 currently there are only graph page for the admin to view. We need a list like statement to show complete details of sales and withdraw selected vendors.

**Comment by ManigandanRaamanathan** [comment]
The admin dashboard need the exact same statement view that the vendor page has. With additional option to sort based on type of description eg. Withdraw, sales and so on. Also need option to print and export pdf
