### ISSUE TITLE
Withdrawal payment method other than paypal not available in vendor withdrawal page.

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#313]
Withdrawal payment method other than paypal not available in vendor dashboard. In the admin dokan setting page it has option to set withdrawal methods such as paypal, bank transfer and skrill. But when the admin checked the bank transfer option, the information is not reflected the vendor withdraw page payment method drop down. The vendor drop down by default is selected as paypal

**Comment by saimonh3** [comment]
@ManigandanRaamanathan A vendor must fill the payment info in the payment settings page and only then it will be populated as a withdrawal method. 
Thanks

**Comment by ManigandanRaamanathan** [comment]
The payment settings is just the paypal email address option available for the vendor in their dashboard.

**Comment by ManigandanRaamanathan** [comment]
@saimonh3  there are only paypal email address field for the vendor in the vendor dashboard

**Comment by sabbir1991** [comment]
We have tested all things. We didn't found any issue as you described.

**Comment by ManigandanRaamanathan** [comment]
@sabbir1991  can the admin pay the withdraws automatically via woocommerce? Plus can you add vendor statement views and print options for those vendor statements list and total order list?
