### ISSUE TITLE
Rest API get all order need order line shop name and shop id in data field and sort parameters in url

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#334]
Rest API get all order need order line shop name and shop id in data field and sort parameters in get URL.

**Comment by saimonh3** [comment]
@ManigandanRaamanathan What did u mean by that?  Are you fetching all orders for a vendor?

If you are trying to fetch individual vendor's orders then why did you need shop name and shop id as you already know the vendor id.
Thanks

**Comment by ManigandanRaamanathan** [comment]
I mean when we use the woocommerce rest api to get the list of order or just a particular order via rest api, I want the vendor id and vendor shop name to be listed together with the order product in the {line item} output data field of rest api

**Comment by saimonh3** [comment]
It makes sense now. We will do that in the upcoming release @ManigandanRaamanathan
