### ISSUE TITLE
Rest API in get all orders, need option to filter orders based on vendor id

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#344]
Rest API in get all orders, need option to filter orders based on vendor id. One order can consist of multiple products from multiple vendors. In your get all order list rest api http request url showed below, we need option to filter the orders based on vendor id:-
GET http://dokan.test/wp-json/dokan/v1/orders/

currently it will print all the order list no matter who the vendor is. I want to get orders that associated with certain vendor only. And please remove the basic authentication. Because currently were unable to get to use the http request that contains basic auth from http site. Therefore please sort the auth issue as well.

Thank you.

**Comment by Sk-Shaikat** [comment]
Hello ManigandanRaamanathan,
You are log in with the admin account. Please log in by vendor account to get individual vendors order list.

Thank you

**Comment by ManigandanRaamanathan** [comment]
@Sk-Shaikat But there is a problem, whenever I try using basic auth with admin or vendor, It always says 

{
    "code": "rest_forbidden",
    "message": "Sorry, you are not allowed to do that.",
    "data": {
        "status": 401
    }
}

**Comment by ManigandanRaamanathan** [comment]
@Sk-Shaikat  could you please explain this below from rest api doc:-

> You may use HTTP Basic Auth by providing the username and password.
> 
> For Basic auth you can use Basic Auth Plugin.
> 
> Occasionally some servers may not parse the Authorization header correctly (if you see a “Username is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the username/password as query string parameters instead.

**Comment by saimonh3** [comment]
@ManigandanRaamanathan Please install `Basic Auth` plugin and try again.  (Note: I know it's too late to reply)
