### ISSUE TITLE
Rest API Need a vendor filter option in Woocommerce WC Order list rest api. 

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#352]
Since im facing issues with dokan rest api with basic auth in getting the list of orders of a particular vendor.  Can you please add a filter option in the Woocommerce REST API to filter list of orders (in the GET LIST OF ORDER WC endpoint) based on the vendor id. This will be helpful for admin in fetching the orders based on the vendors without needing to login as the vendor in the basic auth. @saimonh3

**Comment by saimonh3** [comment]
@ManigandanRaamanathan As a vendor you can fetch your orders only. As an admin to solve the issue you could fetch all order via wc_rest_api and filter those using vendor_id as you can get the vendor info in store object.

**Comment by ManigandanRaamanathan** [comment]
@saimonh3 So you are saying that the admin able to view all orders currently the vendor processing via wc_rest_api using their vendor id?

**Comment by aaronbesson** [comment]
@ManigandanRaamanathan 
you can do https://yourdomain.com/wp-json/wc/v3/orders?consumer_key=ck_XXXXX&consumer_secret=cs_XXXXX&?store=9

**Comment by nurul-umbhiya** [comment]
already fixedd
