### ISSUE TITLE
Need email notification to both admin and vendor when a new coupon is created and if it expired or limit reached (max used, or date expired...)

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#356]
Need an email notification to both admin and vendor whenever a new coupon is created and if it expired or limit reached (max used, or date expired...). It will be better if the final expired/limit reached email contains the orders/customer summary used the coupon.

If the admin creates coupon for products of a particular vendor, then the specific vendor should receive notification that coupon is created and the products and conditions.

**Comment by Mohaiminulislam1989** [comment]
We will add a mail option for the user when he follows the vendor
