### ISSUE TITLE
Need option in admin to make all new vendor coupons and edits approval in admin

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#361]
We need an option within the admin dokan dashboard to enable the option to require approval of any new coupon creation or modification. Based on the approval the WC Rest API coupon retrieving code must have approval status field. 

Thanks

**Comment by nurul-umbhiya** [comment]
We couldn't found any real use case for this. besides, we will add supports for admin coupons where admin will create coupons for vendors. I'm closing this issue for now.
