### ISSUE TITLE
Bug and Insufficient options for coupon from vendor account compared to Woocommerce available options

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [weDevsOfficial/dokan#384]
**First**
**1) The below discount type option is confusing, which one is discount and fixed amount discount?**
**The default _Product Discount option_ is shown as _Percentage Discount in Woocommerce Admin_**

Need Percentage discount option and Fixed cart discount option
![image](https://user-images.githubusercontent.com/22089729/45926153-124c1680-bf52-11e8-9667-2de1b6a83b45.png)

**Second**
**2) Few of the below restriction options that available in Woocommerce are not available in _dokan vendor page_ when creating and editing new coupon

- i) Missing "usage to X items"

- ii) Missing "usage limit per user"

- iii) Missing "usage to X items and Usage limit per user"
 **
![image](https://user-images.githubusercontent.com/22089729/45926195-bb930c80-bf52-11e8-940d-0f8799404aad.png)

**

- iv) Missing "Maximum Amount in vendor page"

**
![image](https://user-images.githubusercontent.com/22089729/45926262-74594b80-bf53-11e8-9628-ff4f4e9dff8e.png)

**Comment by LokeshwariGautam** [comment]
I am Facing the similar issue we need to restrict coupon for per user. Can anyone tell how this can be achieved?

**Comment by alamgircsebd** [comment]
Hello @LokeshwariGautam 

We have resolved the point restrict coupon per user on dokan pro, please wait until our next release or if you want to implement it urgently then contact our support team they will help you implement the new codes.

Thanks!

**Comment by alamgircsebd** [comment]
Resolved
