### ISSUE TITLE
Child theme can't upload image for products or avatar/banner

### ISSUE THREAD

**Issue by KevinDuclos** [weDevsOfficial/dokan#402]
Hi everyone, since some update, i can't upload file from the vendor dashboard if i activate my child-theme for storefront, it work perfectly if i re-activate the original theme so anyone have an idea or have same issues with a child theme ?
The bug is that when i click on the button to upload file, the page become grey and nothing else happen.
Thanks a lot for the answers.

**Comment by saimonh3** [comment]
@KevinDuclos Hello I've tested with a storefront child theme and found there is no such issue. Thanks
