### ISSUE TITLE
Show Withdraw Request "Details" when using a custom Withdraw Method

### ISSUE THREAD

**Issue by luisdfp** [weDevsOfficial/dokan#408]
I added a custom withdraw method for another payment processor (Payfast). I found no major issues when using the different filters and hooks available to achieve this. However, the "Details" column in the Withdraw Requests table won't show the details of my withdraw method. Example:

![withdraw-request](https://user-images.githubusercontent.com/13454345/46842233-7a945800-cd9a-11e8-904b-2e08c2879437.png)

In this case, it should show the vendor's Payfast account E-mail, as specified in their Payment settings:

![screencapture-dev-somart-test-pantheonsite-io-vendor_dashboard-settings-payment-2018-10-11-21_32_47](https://user-images.githubusercontent.com/13454345/46842809-c98fbc80-cd9d-11e8-9545-14121cfb7705.png)

At the moment, it seems like there is no way to do this because the payment methods are hardcoded in `src/admin/pages/Withdraw.vue`:

```js
        getPaymentDetails(method, data) {
            let details = '—';
            if ( data[method] !== undefined ) {
                if ( 'paypal' === method || 'skrill' === method ) {
                    details = data[method].email || '';
                } else if ( 'bank' === method ) {
                    if ( data.bank.hasOwnProperty('ac_name') ) {
                        details = this.sprintf( this.__( 'Account Name: %s', 'dokan-lite' ),  data.bank.ac_name );
                    }
                    if ( data.bank.hasOwnProperty('ac_number') ) {
                        details += this.sprintf( this.__( ', Account Number: %s', 'dokan-lite' ), data.bank.ac_number );
                    }
                    if ( data.bank.hasOwnProperty('bank_name') ) {
                        details += this.sprintf( this.__( ', Bank Name: %s', 'dokan-lite' ), data.bank.bank_name );
                    }
                    if ( data.bank.hasOwnProperty('routing_number') ) {
                        details += this.sprintf( this.__( ', Routing Number: %s', 'dokan-lite' ), data.bank.routing_number );
                    }
                }
            }
            return details;
        },
```

Thank you and keep up the good work. :thumbsup:

**Comment by saimonh3** [comment]
@luisdfp Thanks for noticing it. We will fix it in the next version.

**Comment by saimonh3** [comment]
@luisdfp You can use this js filter dokan_get_payment_details to get your desired result. 
563fdb008dbac465a439f0404c195c99531e4f59

**Comment by PaulDavidMoore** [comment]
@luisdfp would you mind sharing how you accomplished adding payfast as a vendor payment method?

**Comment by Joacro78** [comment]
> I added a custom withdraw method for another payment processor (Payfast). I found no major issues when using the different filters and hooks available to achieve this. However, the "Details" column in the Withdraw Requests table won't show the details of my withdraw method. Example:
> 
> ![withdraw-request](https://user-images.githubusercontent.com/13454345/46842233-7a945800-cd9a-11e8-904b-2e08c2879437.png)
> 
> In this case, it should show the vendor's Payfast account E-mail, as specified in their Payment settings:
> 
> ![screencapture-dev-somart-test-pantheonsite-io-vendor_dashboard-settings-payment-2018-10-11-21_32_47](https://user-images.githubusercontent.com/13454345/46842809-c98fbc80-cd9d-11e8-9545-14121cfb7705.png)
> 
> At the moment, it seems like there is no way to do this because the payment methods are hardcoded in `src/admin/pages/Withdraw.vue`:
> 
> ```js
>         getPaymentDetails(method, data) {
>             let details = '—';
>             if ( data[method] !== undefined ) {
>                 if ( 'paypal' === method || 'skrill' === method ) {
>                     details = data[method].email || '';
>                 } else if ( 'bank' === method ) {
>                     if ( data.bank.hasOwnProperty('ac_name') ) {
>                         details = this.sprintf( this.__( 'Account Name: %s', 'dokan-lite' ),  data.bank.ac_name );
>                     }
>                     if ( data.bank.hasOwnProperty('ac_number') ) {
>                         details += this.sprintf( this.__( ', Account Number: %s', 'dokan-lite' ), data.bank.ac_number );
>                     }
>                     if ( data.bank.hasOwnProperty('bank_name') ) {
>                         details += this.sprintf( this.__( ', Bank Name: %s', 'dokan-lite' ), data.bank.bank_name );
>                     }
>                     if ( data.bank.hasOwnProperty('routing_number') ) {
>                         details += this.sprintf( this.__( ', Routing Number: %s', 'dokan-lite' ), data.bank.routing_number );
>                     }
>                 }
>             }
>             return details;
>         },
> ```
> 
> Thank you and keep up the good work. 👍

Hi there, I would like to integrate payfast as a split payment on dokan
Can this be done

**Comment by alamgircsebd** [comment]
Hello @Joacro78 please check this gist: https://gist.github.com/alamgircsebd/0049ac314267abfb6317c93c88667477
here have solutions, 

`
/**
 * Dokan admin add custom withdraw method details
 *
 * @return void
 */
function dokan_admin_withdraw_list_add_custom_method() {
  ?>
  <script>
    var hooks;
    function getCustomPaymentDetails( details, method, data ) {
      if (data[method] !== undefined) {
        if ('custom' === method) {
          details = data[method].email || '';
        }
      }
      return details;
    }
    dokan.hooks.addFilter( 'dokan_get_payment_details', 'getCustomPaymentDetails', getCustomPaymentDetails, 33, 3 );
  </script>
  <?php
}
add_action( 'admin_print_footer_scripts', 'dokan_admin_withdraw_list_add_custom_method', 99 );
`

**Comment by Joacro78** [comment]
Thank you so much, could you please tell me where I can add the above code

**Comment by alamgircsebd** [comment]
> Thank you so much, could you please tell me where I can add the above code

Add this on child/parent theme functions.php file

**Comment by Joacro78** [comment]
Thank you
