### ISSUE TITLE
Cash on delivery and other manual payments still added to vendor total

### ISSUE THREAD

**Issue by UVLabs** [weDevsOfficial/dokan#433]
This was already mentioned here: https://github.com/weDevsOfficial/dokan/issues/34 I'm bringing it back up because I believe it's a reasonable thing. I don't think as fellow developers we should make decisions for end users. We should give them a choice

A solution to this would be giving the marketplace owner a choice to whether or not they want totals for cash on delivery (or other manual payment methods such as Bank Transfer) added to the vendors total. Then you can run a check against the order and check the payment method to see if it meets the conditions:

http://woocommerce.wp-a2z.org/oik_api/wc_orderget_payment_method/

https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html

---

You mentioned how would the marketplace owner collect commissions? The thing is the marketplace owner has access to all orders. They can keep track of orders happening and request that the vendors submit the appropriate commission or risk their store items being taken down from the website.

**Comment by saimonh3** [comment]
https://github.com/weDevsOfficial/dokan/pull/435
