### ISSUE TITLE
Shipping for virtual variable products with physical product 

### ISSUE THREAD

**Issue by marcofrasson** [weDevsOfficial/dokan#476]
I'm having a problem adding a physical product with freight and another digital product without shipping.

Dokan makes some markup for the digital product to have shipping, so I can not finalize the purchase.

I'm using a downloadable digital variable product and a simple physical product for delivery.

**Comment by saimonh3** [comment]
@marcofrasson Hello, we are unable to reproduce the issue. Would you please capture a video regarding the issue and send to us?

Regards

**Comment by saimonh3** [comment]
Long time no update. Closing the issue.
