### ISSUE TITLE
Validate customer or seller registration when running in REST and CLI environments

### ISSUE THREAD

**Issue by ediamin** [weDevsOfficial/dokan#533]
Dokan is using `Dokan_Registration::validate_registration` to validate customer and seller registration process only when in browser environment(ie, only when we have `$_POST` present). We need to validate this process in REST and CLI environment too.

**Comment by DastanIqbal** [comment]
After applying this fix also,I cannot call http://exmple.com/wp-json/dokan/v1/user/register. I checked http://exmple.com/wp-json/ there is no route dokan/v1/user/register. Instead I am getting this response when I am posting

  {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}

Please help. !!
