### ISSUE TITLE
Commission for customers

### ISSUE THREAD

**Issue by LazarTB** [weDevsOfficial/dokan#545]
I know that there is commission to set for Vendors, and then they have to enter the price for their products and commission will be reduced from that price.

Can we somehow set for price to be automatically set 10% (this could be optional) more than vendors price for product?
Basically, if product is 100$, automatically set price to 110$, so customer pays 110$, vendor gets 100$ and Admin get 10$ commission. (just an example)

Is this doable?

**Comment by saimonh3** [comment]
@LazarTB I don't see any difference between the current procedure and your mentioned one.

**Comment by LazarTB** [comment]
Never mind, we managed to set everything trough woocommerce.

**Comment by AmayasLeBoss** [comment]
Hello LazarTB, could you tell me how you set it through woocommerce ? That would help a lot :) !
