### ISSUE TITLE
Get all orders problem rest api

### ISSUE THREAD

**Issue by erknertn** [weDevsOfficial/dokan#547]
Hi,
When I log in as admin, it brings all orders. But when I login as a vendor, it does not bring orders.

incoming postman result;
[]

GET /wp-json/dokan/v1/orders/ HTTP/1.1
Host: localhost
Authorization: Basic aW5mb0BtdXppa3JleW9udS5jb206MTk4NzE5OAc=
cache-control: no-cache
Postman-Token: 828a0664-431f-400c-b5b2-72be6a5b846a

**Comment by saimonh3** [comment]
@erknertn Hello, I've checked and found no such issue. Thanks

**Comment by ediamin** [comment]
Resolved in 1d6cf2fa207184ecd5f1be6a0f82df9abe030213
