### ISSUE TITLE
Maps API having issues - This page can't load Google Maps correctly

### ISSUE THREAD

**Issue by arg3301** [weDevsOfficial/dokan#548]
I see you telling people to set the API details properly.
ERROE: This page can't load Google Maps correctly
The issue is not simply setting the API;s properly but something else.
I am still getting the errors after setting the API up properly, restricting access (Using wildcards)

To emphasise the issue, I point you to your own website

![dokan maps](https://user-images.githubusercontent.com/41543363/52540086-ea851000-2d85-11e9-8ba3-ad30829522b8.jpg)

**Comment by saimonh3** [comment]
There is no such issue right now.
