### ISSUE TITLE
Rest api update settings

### ISSUE THREAD

**Issue by erknertn** [weDevsOfficial/dokan#563]
Hi,
PUT dokan/v1/settings

There is a problem in the rest api update settings. postman comes empty as a result.

**Comment by saimonh3** [comment]
@erknertn Hello, please use `dokan/v1/stores` api endpoint to add, edit or delete a vendor. Thanks

**Comment by erknertn** [comment]
dokan/v1/stores/18?first_name=blabla

it only makes an update when logged in with admin. the seller gives an error when logged in.


{
"code": "rest_forbidden",
"message": "Sorry, you are not allowed to do this.",
- "data": {
"status": 403
}
}

**Comment by saimonh3** [comment]
@erknertn We gave the required permission to vendor, which will be available in the next release. Thanks
https://github.com/weDevsOfficial/dokan/pull/564

**Comment by HusamoBinAref** [comment]
to solution this :
goto file rest in yoursite for dokan :
yourplay/wp-content/plugin/dokan-lite/includes/REST/StoreSettingController.php
and replace it with this file:
https://github.com/HusamoBinAref/dokan-setting/blob/main/StoreSettingController.php

file path IMage help :
https://github.com/HusamoBinAref/dokan-setting/blob/main/storeSettinfPath.PNG

good lock
