### ISSUE TITLE
Unable create customer using WC_Rest API

### ISSUE THREAD

**Issue by saimonh3** [weDevsOfficial/dokan#578]
https://github.com/weDevsOfficial/dokan/issues/533

**Comment by DastanIqbal** [comment]
After applying this fix also,I cannot call http://exmple.com/wp-json/dokan/v1/user/register. I checked http://exmple.com/wp-json/ there is no route dokan/v1/user/register.  Instead I am getting this response when I am posting

  ``` {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}```


Please help. !!

**Comment by DastanIqbal** [comment]
May I now why its closed ?? I already applied that fix, do I need to generate new ticket?
