### ISSUE TITLE
Upload image for downloadable product is not showing the image

### ISSUE THREAD

**Issue by shabnam611** [weDevsOfficial/dokan#613]
When vendor creates a downloadable product and adds the file, if that is an image and vendor uploads the image directly from his machine, then the image remains unavailable for the vendor. 

Screenshot: https://prnt.sc/nh1dr3

**Comment by saimonh3** [comment]
@shabnam611 Found this is the default behavior of WooCommerce. Please try the same thing from the backend.

**Comment by saimonh3** [comment]
No such issue.
