### ISSUE TITLE
Dokan Dashboard Crashed with Uncaught ReferenceError

### ISSUE THREAD

**Issue by geekysihag** [weDevsOfficial/dokan#646]
In my Dokan Dashboard i am getting this issue recently, everything was working fine, but this break suddenly…..can anyone please help ?

Uncaught ReferenceError: Chart is not defined
at HTMLDocument.<anonymous> ((index):879)
at i (jquery.js?ver=1.12.4-wp:2)
at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
at Function.ready (jquery.js?ver=1.12.4-wp:2)
at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

https://homiti.com/dashboard/

**Comment by saimonh3** [comment]
@geekysihag Hello, we are unable to reproduce the issue. Please email at support@wedevs.com with your site credentials so that we can debug on your site. Thanks

**Comment by geekysihag** [comment]
Alright i am doing it now

**Comment by geekysihag** [comment]
I just sent an email to you guys
