### ISSUE TITLE
Vendor page going blank

### ISSUE THREAD

**Issue by BatmanLives** [weDevsOfficial/dokan#65]
I applied the Flatsome3 theme (http://flatsome3.uxthemes.com/) on my Wordpress site with Dokan in it. Now, the vendors page has turned blank. It looks like the footer DIV is covering everything. I sent a support email to Flatsome3 folks and they said this is something that Dokan has to fix. Please take a look:
http://puppyfor.me/store/pets/

**Comment by nayemDevs** [comment]
@BatmanLives This is not a plugin core issue. Your theme footer is overlapping with the content. You can use similar kind of CSS like below : 

`.footer{
    clear: both;
}`

As the Flatsome theme is not officially compatible with Dokan for that reason it is creating some layout issue. If you have created ticket then our support team will help :)

**Comment by tomtev** [comment]
Hi there, this is the author of Flatsome. This is 100% something Dokan needs to fix. They are not clearing their floats!

Adding #main{overflow:hidden} fixes this, but the plugin author should of course clear their "floats" if they use float for layout.

**Comment by nayemDevs** [comment]
@tomtev Thanks for your valuable comment. We have added it to the plugin and from the next update it should work fine :) I hope the flatsome theme will fully compatible with Dokan. Lots of Dokan users are using Flatsome.

**Comment by Joshuagier** [comment]
Hi, can I ask whether the Flatsome-Dokan compatibility is resolved? 

I love the theme, however, I would like to able to create a multi-vendor biz

Can I comfortably purchase Dokan at this stage knowing that I won't need to change my . current theme

**Comment by nayemDevs** [comment]
Hello @Joshuagier 

Dokan is not officially integrated with Flatsome. It can cause a CSS issue on the store page of Dokan which can be fixed easily. You can install the Dokan free version on your website to check and solve if there is any issue!

**Comment by Joshuagier** [comment]
Ever since I installed Dokan nothing happens when I click on the Register button, whether I want to register as a customer or a vendor



<img width="1260" alt="screen shot 2018-07-18 at 4 34 41 pm" src="https://user-images.githubusercontent.com/40202198/42869866-e3fda70e-8aa8-11e8-8e98-dff04195ff1c.png">

**Comment by nayemDevs** [comment]
Hello,

Please kindly create a support ticket. Our support team will help you on
this issue!

Regards,
Md. Nazmul Hassan
Lead Support Engineer/Project Manager
Website: https://nayemdevs.com
Contributor @ WordPress.org
<https://profiles.wordpress.org/nazmulhassann20/>
Linked in: https://www.linkedin.com/in/nayemdevs
Twitter: @nayemdevs <https://twitter.com/nayemDevs>
