### ISSUE TITLE
Dokan add generic link to shop

### ISSUE THREAD

**Issue by iyfm** [weDevsOfficial/dokan#651]
Hello, 

We are using Dokan and we find that the button in the vendor account "Go to Shop" is not clear for our customers.

We would like to add a large button with a generic link that points to the vendor shop.

https://www.domain.nl/vendorslug/($store_url?)

We got the function to call: 
dokan_get_store_url( dokan_get_current_user_id() )

Question how can we call this function with this link: https://www.domain.nl/vendorslug/

Hope somebody can help us?

**Comment by AndreaBarghigiani** [comment]
Hi there, 
I am not part of the Dokan team but I am working on a heavy customization as well. 

Looking in the documentation I've found [this article](https://wedevs.com/docs/dokan/developer-documentation/adding-removing-url-dokan-dashboard/) that I think you'll find really useful.

In addiction there is also a [full article](https://wedevs.com/98671/adding-extra-menu-dokan-vendor-dashboard/) documenting the steps needed.

Hope this can help.

**Comment by saimonh3** [comment]
@iyfm Hello, I'm assuming you wanted to change the `Go to Vendor Dashboard` in vendor my-account page. If so you can use this filter `dokan_set_go_to_vendor_dashboard_btn_text` like this to change the button.
```php
add_filter( 'dokan_set_go_to_vendor_dashboard_btn_text', function() {
    return __( 'My Custom Button', 'dokan' );
} );
```
Otherwise follow how @AndreaBarghigiani  suggested. Thanks
