### ISSUE TITLE
How to add field to Add New Vendor backend modal

### ISSUE THREAD

**Issue by AndreaBarghigiani** [weDevsOfficial/dokan#652]
Hi weDevs team,
I am working on a customization of your plugin and I would like to know how it is possibile to add a simple field into your Add New Vendor modal.

I have checked your code and I found out that your modals are built usign Vue.js and that makes really difficult for me to add or remove the fields.

I know that you shared with us [how to add fields in the settings page](https://wedevs.com/108107/how-to-add-extra-field-on-vendor-settings-page/) but how can I add the same field in the modal?

Do you have any ideas?

**Comment by saimonh3** [comment]
@AndreaBarghigiani You have to follow this documentation https://developer.wordpress.org/block-editor/packages/packages-hooks/ 

For example to add field in vendor address area you can use this filter `getVendorAddressFields`. 

Hope this helps. Thanks

**Comment by abe001** [comment]
Ok same problem and how the hooks work is clare for me but where have I to manage it? what file? which plugin?
Can you explain to me?

**Comment by saimonh3** [comment]
@abe001 You'll have to enqueue a vue script in your child theme or your plugin then u can use that filter to include any other content. 

Use this action `dokan-vue-admin-scripts` to enqueue your script.

**Comment by abe001** [comment]
I'm gonna try thanks!
