### ISSUE TITLE
Is it possible to create secondary language product from dokan dashboard?

### ISSUE THREAD

**Issue by khm-developer** [weDevsOfficial/dokan#681]
Hi,

Is it possible to create a secondary language product from the dokan dashboard?
How to create secondary language products from the dokan dashboard because vendor needs to create second language product from own..

**Comment by saimonh3** [comment]
@khm-developer It's not possible right now. But if you give the vendor backend access (there is an option to do so) then they can create product with their own language.

**Comment by khm-developer** [comment]
Thanks for quick reply,

In vendor access for backend is not working but at the initial stage of my development, that option is working good. Also, Vendor products must need admin permission to publish because to verify any hidden contact are available on the product page. 

Is it possible to develop my requirement using my own code on functions.php....

**Comment by FaraziF** [comment]
We have WPML integration 
https://wedevs.com/dokan/modules/wpml-integration
