### ISSUE TITLE
Bug when using WooCommerce Subscriptions in Vendor panel

### ISSUE THREAD

**Issue by trajche** [weDevsOfficial/dokan#683]
Bug & fix: Uncaught error: Call to undefined function get_current_screen() in woocommerce-subscriptions/includes/admin/class-wc-subscriptions-admin.php on line 1803

This is a compatibility bug with WooCommerce Subscriptions that shows up in the Vendor Panel. The fix for this is to add the following in dokan-pro.php (if you use the Pro version) or if using Lite I assume in: dokan.php or includes/functions.php

```
//Fixing call to undefined function get_current_screen() because of Subscriptions Plugin
require_once(ABSPATH . 'wp-admin/includes/screen.php');
```

**Comment by saimonh3** [comment]
@trajche I'm unable to reproduce the bug. Can you please tell us how to reproduce it?

**Comment by trajche** [comment]
@saimonh3 You must be also using WooCommerce Subscriptions (https://woocommerce.com/products/woocommerce-subscriptions/) and have a few active subscriptions. You can try to also assign a subscription product to a vendor (this should call the get_current_screen) function.

**Comment by saimonh3** [comment]
@trajche I had WooCommerce Subscription installed with no active subscriptions though and WooCommerce Subscription is not compatible with Dokan BTW.

**Comment by trajche** [comment]
^ Yeah, but even after we removed the subscriptions from that user all the vendor users could see the error. Either way the fix is here if someone needs to have a look. I'll close this for now. Thanks for looking into it.
