### ISSUE TITLE
Combined Commission Issue

### ISSUE THREAD

**Issue by imMrRAW** [weDevsOfficial/dokan#687]
If i select FLAT commission and set it to 10SEK, and then go to Edit Product and set the price to 10 it says "You Earn: 0kr".

If i select PERCENTAGE and set it to 10%, and review the price calculation again it says "You Earn: 9kr" - all fine the also.

If i set COMBINED commission where the percentage is 0% and FLAT is 10kr" it says "You Earn: 0kr".

HOWEVER - if i change the percentage to 10% and leave FLAT at 10kr it says "You Earn 10kr".

So, by using combined with a value that goes beneath 0.0kr will cause the calculation to be wrong.
But the issue doesn't really stop there - the commission will be wrong in the system as well.

It will give the Vendor 10SEK and the Owner of the site 0SEK.

This is a BIG issue!

**Comment by saimonh3** [comment]
@imMrRAW Thanks, the point you raised is valid and we'll definitely work on it. But my only question is, what's the point of using combined commission while you're not honoring both of the fields?

**Comment by imMrRAW** [comment]
> @imMrRAW Thanks, the point you raised is valid and we'll definitely work on it. But my only question is, what's the point of using combined commission while you're not honoring both of the fields?

The only reason here was to show the bahaviour - in a real world - you would, as you say - use both fields.
If not, then it's pointless to use combined.
However, if you use the "Combined" and only specify one field, it will work.
It's the two fields in combination that enables the bug.

**Comment by imMrRAW** [comment]
This hasn't been resolved yet.

I did the changes, but the calculation-issue is still in the "Edit Product"-view.
I set combined commission to 10% + 10SEK
In Edit Product, if you set to 1SEK, or up to 11SEK it says vendor will get all.

It should prevent the vendor to send a product that wont give the store owner it's commission.

![earning](https://user-images.githubusercontent.com/56786847/68527882-6b107700-02ec-11ea-8ffc-9ec4470f031f.png)

**Comment by saimonh3** [comment]
@imMrRAW It will be fixed once Dokan Pro is released. Meanwhile make the changes in *dokan-pro/includes/functions.php* line no: 662 and make it something like this. Thanks.
```php $earning  = (float) $product_price - $total_earning;```

![carbon](https://user-images.githubusercontent.com/13016829/68529572-49ce7b80-032a-11ea-8b65-8f422423c8a5.png)
