### ISSUE TITLE
Inventory issue when ordering from multiple vendors 

### ISSUE THREAD

**Issue by sfoulad** [weDevsOfficial/dokan#689]
Good day,
when customer buy product from multiple vendors its reducing the stock twice , one time from the parent order and another from the sub orders:

Main Order [111]
Stock levels reduced: Sweet Orkieda - Tamryia (#3172) 3→2
HEALTHY_ Nuts bar MED (#3781) 3→2

Suborder [112]
Stock levels reduced: HEALTHY_ Nuts bar MED (#3781) 2→1

Suborder [113]
Stock levels reduced: Sweet Orkieda - Tamryia (#3172) 2→1

**Comment by saimonh3** [comment]
@sfoulad Did you check with the latest version? I'm unable to reproduce the issue. Thanks
