### ISSUE TITLE
Custom attribute not saving is causing trouble

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#703]
If you save the attribute every time it works fine : 
https://www.loom.com/share/55036c50ff8b4419a2b67f4bb0a6388d

But if you delete one of the attributes and add the attribute again, skipping the save attribute is causing the issue mentioned on the next video : 
https://www.youtube.com/watch?v=FqC_wecfVQs&feature=youtu.be

**Comment by saimonh3** [comment]
@roshni07 Does it happen with the latest version of Dokan? Please check again. Found no such issue.
