### ISSUE TITLE
The $300 Million Button.

### ISSUE THREAD

**Issue by emazharulislam** [weDevsOfficial/dokan#705]
Sometimes big changes are not able to impact even in a small way but sometimes a small change can make a huge difference. Without thinking about the impact we should always try to make changes for good.

Dokan is getting bigger day by day. And it's quite close to impossible to remember or get the idea of why and how all the options works. Documentations and other resources can provide the answer to how, but why it is absent. So, it will be helpful if there is a help icon on every option like in this one: https://prnt.sc/q1le39 

For example, Enabling Single Seller Mode, this may confuse a marketplace owner, why this option is there when I have activated the multivendor marketplace.  The help icon like the screenshot on this option may be a very positive sign in a user experience way.

**Comment by MdAsifHossainNadim** [comment]
All ready done in #1390
