### ISSUE TITLE
Product adding is cumbersome when there are hundreds and thousands of tags

### ISSUE THREAD

**Issue by nayemDevs** [weDevsOfficial/dokan#720]
**How to reproduce?**
Kindly try to upload a product and click on the tag field. It will suggest a long list (If available). 

**Problem**
If it loads all the tag on the first click then it takes a long time if there are thousands of Tags. Which can make the product upload process slower. 

**Expected solution**  
We should not load all the tags at the same time. We can load 10 suggestions and then show more 10 upon scrolling. In this process, the speed will be optimized.

**Comment by saimonh3** [comment]
@nayemDevs will be addressed after dokan refactor.

**Comment by alamgircsebd** [comment]
Resolved already
