### ISSUE TITLE
New order email for vendor is showing admin URL 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#732]
Description of the issue: 

The new order email has the admin order URL.

How to reproduce: 

- Purchase a product from a vendor 

- Check the email the vendor receives for a new order

- Click on the order number and the vendor will be redirected to wp-admin

Expected behavior:
 
A new order email for a vendor should redirect them to the vendor dashboard. 
-

**Comment by royrakesh** [comment]
Any update ?

**Comment by saimonh3** [comment]
@royrakesh Yep it will be fixed in the upcoming release.

**Comment by royrakesh** [comment]
Thanks
