### ISSUE TITLE
Vendors are able to have Discount Price greater than the Original Price.

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#738]
Description :

WooCommerce changes the discount option to the sales price and does not allow it to set the price greater than the original price. However, Dokan allows the vendor to have Discount Prices greater than the Original Price.

How to reproduce the issue:

Create a product and set a price
You can set the discount price greater than the original price

Expected Behaviour

The discount price should say sales price as WooCommerce does
It should show an error while the vendor is setting the price greater than the original price

Screenshot :

https://prnt.sc/qq1ys0

https://prnt.sc/qq1yzf

‌

**Comment by alamgircsebd** [comment]
Issue Solved and merged
