### ISSUE TITLE
please fix problem

### ISSUE THREAD

**Issue by mehrshadmti** [weDevsOfficial/dokan#747]
Warning: file_exists(): open_basedir restriction in effect. File(/home/mysite/public_html/wp-content/plugins/dokan-lite/includes/upgrades/background-processes/class_dokan_update_2_9_16_store_settings.php) is not within the allowed path(s): (C:/Inetpub/vhosts/mysite.com\;C:\Windows\Temp\) in C:\inetpub\vhosts\mysite.com\httpdocs\wp-content\plugins\dokan-lite\includes\background-processes\class-dokan-background-processes.php on line 20

**Comment by saimonh3** [comment]
@mehrshadmti Hello, there is nothing to do with dokan. I suspect it's a hosting problem. Contact your hosting provider, they will be able to solve it. Also you might find these links helpful. Regards.

1. https://www.ipserverone.info/cms-content-management-system/wordpress-applications/wordpress-solving-file_exists-function-file-exists-open_basedir-restriction-in-effect/

2.  https://support.plesk.com/hc/en-us/articles/115000278993-A-website-hosted-in-Plesk-is-not-accessible-open-basedir-restriction-in-effect-File-is-not-within-the-allowed-path-s-
