### ISSUE TITLE
When there are no products, instead of showing empty table maybe we can mimic how WooCommerce does this

### ISSUE THREAD

**Issue by saimonh3** [weDevsOfficial/dokan#758]
![Screen Shot 2020-02-05 at 12 53 40 PM](https://user-images.githubusercontent.com/13016829/73820688-7e17e200-481c-11ea-8f50-7ad12b4af89a.png)

![Screen Shot 2020-02-05 at 12 55 43 PM](https://user-images.githubusercontent.com/13016829/73820726-8e2fc180-481c-11ea-9d5e-71db915a71d8.png)

**Comment by alamgircsebd** [comment]
![Screenshot_2020-02-10 Dashboard Fress WP Lab](https://user-images.githubusercontent.com/25417335/74121868-788f1300-4bf3-11ea-945e-c22362899fd0.png)

**Comment by sabbir1991** [comment]
We are working later with a new design.
