### ISSUE TITLE
Vendor email is not showing

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#766]
Description :

The vendor tab does not show the email  of the vendor

How to reproduce: 

- Register as a vendor 
-wp-admin-->Dokan-->Vendor 
-Email is missing for the vendor

Expected behavior: 

The email of the vendor should be available in the email section. 

Screenshot : 
https://prnt.sc/r0j29i

**Comment by alamgircsebd** [comment]
We solved this issue, hope next release will get this updates.

**Comment by saimonh3** [comment]
https://github.com/weDevsOfficial/dokan/commit/6bc5d78442b895e8f2059448e93b18a12772cc9f
