### ISSUE TITLE
[Dokan Rest API v1] How to upload and add local image in a single product via rest API

### ISSUE THREAD

**Issue by itsgauravjain22** [weDevsOfficial/dokan#768]
I referred Update a Product endpoint documented as [here](https://wedevsofficial.github.io/dokan/#update-a-product)

But I couldn't find a way to upload and add Product image using this endpoint. Kindly suggest a way to upload and add (local image) and remove product image via Dokan Rest API.

**Comment by Mohaiminulislam1989** [comment]
We don't have this feature in our API right now.
