### ISSUE TITLE
Dokan vednor edit page does not save the email field

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#769]
**Description of the bug:**
When you edit a vendor profile from Dokan > Vendors > Edit vendor. The email field is unable to be saved - https://prnt.sc/r0zabv. It happened to one of the user and the issue they are expecting is -
"This is a serious problem because the Dokan vendors who have the empty field in ‘Email Address’ are not receiving any notifications, such as ‘New Order notifications- and that is having a devastating effect on sales and the confidence of both vendors on the website and their customers."

**How to reproduce:**
1. Register a vendor
2. Navigate to Dokan > Vendors > Edit the newly registered vendor
3. Check the email field, it is not saved.

Expected behavior:
The email should show in the email field.

**Comment by alamgircsebd** [comment]
We solved this issue, hope next release will get this updates.

**Comment by JoniNaeff** [comment]
This issue is not solved for me. I have the exact same problem as described. Can you help me please? My Dokan version is 3.0.2

**Comment by looknear** [comment]
It is related to very old report i gave about sync between "vendor" info and "user" info.
if the admin change something in the product of the vendor - the ownership is transferred to the admin, and then, the product owner get "author" as "shop manager" or any nickname your admin have.
when fixing it - and setting back the product to belong to the Vendor. then when the problems start...
the nickname of the vendor become the admin nickname.... "shop manager" or "admin" ...
and then you need manually find the vendor and change its info in the users management back-end.
