### ISSUE TITLE
"Pick-Up Location" in Orders

### ISSUE THREAD

**Issue by seanbaker74** [weDevsOfficial/dokan#782]
I'm building a small site for a farm co-op. It's a multi-vendor environment, with multiple farmers providing product. The customer will create one single order (from multiple vendors), and then choose their pick-up location (using the WC Pickup Plus extension).

My issue is that the order page for the vendor doesn't display the pick-up location. It shows the customer billing and shipping locations instead.

**Comment by Mohaiminulislam1989** [comment]
Hello @seanbaker74,
Thank you for creating this issue. We are working on this feature. But we don't have any plan to integrate WC Pickup Plus extension with dokan. We will do this in a better way. Hope you will get this soon.

Thanks
