### ISSUE TITLE
Do not display redundant shipping option in cart

### ISSUE THREAD

**Issue by jjvila** [weDevsOfficial/dokan#792]
When an order exceeds the minimum free shipping threshold as set by the vendor, the calculated/flat rate shipping still displays as an option in the cart. It is obvious that a customer will select the free shipping option and never the calculated price, so that calculated price should be hidden.

When the free shipping threshold has not been met, it would be nice to have a message like "add $10 more from this vendor to qualify for free shipping" like Amazon does.

**Comment by kapilpaul** [comment]
Hi @jjvila 

This is a normal behavior like woocommerce and this is expected.
