### ISSUE TITLE
Images are not attached to WooCommerce products

### ISSUE THREAD

**Issue by trajche** [weDevsOfficial/dokan#794]
When you visit the Media Library you can see that any products that are uploaded via the Dokan front-end are not actually attached to Product objects in WordPress as is the default WooCommerce functionality.

This conflicts with "image clean up" plugins and causes other issues with the WordPress/WooCommerce REST API when looking for related images to an object, in this case a WooCommerce product.

Please let me know if you need more explanation.

**Comment by Mohaiminulislam1989** [comment]
Can you please share some more details with video or screenshots?
