### ISSUE TITLE
Button style in vendor setup wizard conflicts with theme style

### ISSUE THREAD

**Issue by jjvila** [weDevsOfficial/dokan#797]
The button style for "Let's Go", "Continue", and "Go To Dashboard" of the vendor setup wizard are conflicting with the theme's style. The class **.button-primary** has a box and text shadow property that becomes exposed when the theme's style is placed over it. The "Not Right Now" button does not have this class assigned and therefore does not have this issue.

I am using OceanWP free version. Message me if you would like more info or screenshots.

**Comment by Mohaiminulislam1989** [comment]
Please share some screenshots.
