### ISSUE TITLE
Vendor is not receiving order email 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#799]
Description: 

If a product is purchased the vendor is not receiving email 

How to reproduce :

1. Purchase product from a vendor 
2. The email is sent to admin and customer 
3. The vendor is not receiving the order email 

Expected behaviours : 

Vendors should receive email

**Comment by alamgircsebd** [comment]
Fixed this issue, see here changes: https://github.com/weDevsOfficial/dokan/pull/800/files

**Comment by spitereu** [comment]
Thank you. That was fast :)

**Comment by royrakesh** [comment]
Please release an update, This is a major issue.
