### ISSUE TITLE
Vendor enable email send twice 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#806]
Description : 

The vendor disable email does not work and the vendor enables email is send twice

How to reproduce : 

1. Navigate to wp-admin-->Dokan-->Vendor
2. Disable the vendor 
3. No email is sent 
4. Enable the vendor 
5. The email is sent twice 

Expected behavior: 

The vendor should get an email for enabling or disable

**Comment by saimonh3** [comment]
It's been fixed on Dokan Pro
