### ISSUE TITLE
Vendor order email does not have the TAX details 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#809]
Description
Vendor order email does not have the TAX details 

How to reproduce:
Create a product with TAX 
Purchase the product 
Check the order email for vendor does not have the TAX details  

Expected behavior
The email should be same as the admin and show the TAX as well.

**Comment by saimonh3** [comment]
@alamgircsebd can you please take a look?

**Comment by alamgircsebd** [comment]
> 
> 
> @alamgircsebd can you please take a look?

Yes, next release will add this fix.
