### ISSUE TITLE
Vendor Contact Form widget issue.

### ISSUE THREAD

**Issue by sohanHossainNabil** [weDevsOfficial/dokan#817]
**Description:** The Contact Vendor form has a bug causing the form fields to jump every time you click on the fields. After looking closer the form validation always causes an extra field to be added also when the validation is successful. The following video demonstrate the issue.
https://www.loom.com/share/9bb6544837c543d2b2102102626665a4

**To Reproduce:**
1. Go to the store.
2. Now click on the Name field and then click on the next field.
3. You will notice that a new space is being created between the fields.

**Comment by zamandevs** [comment]
Did not produce on my end. everything is fine.
