### ISSUE TITLE
Order fetching issues with REST API

### ISSUE THREAD

**Issue by saimonh3** [weDevsOfficial/dokan#818]
**These doesn't work as expected:**

```
wp-json/dokan/v1/orders/?status=processing
wp-json/dokan/v1/orders/?order=asc&orderby=id
wp-json/dokan/v1/orders/?exclude=3589
```

**Comment by mehr800** [comment]
We have some app based on Dokan rest APIs. So, please hurry up to fix the problems.
We need APIs to get today's orders and also filtering by "status".
Thanks
