### ISSUE TITLE
8 digit number calculation issue

### ISSUE THREAD

**Issue by sohanHossainNabil** [weDevsOfficial/dokan#819]
**Description:**  When a product is purchased with a price of more than 10000000 (8digit). The calculation in some parts seems incorrect. 

**How to reproduce:**
1. Create a product and set a price which is higher than 10000000 (8digit). For example: 58,499,000.

2. Now complete an order.

3. Go to the Dashboard and notice that the sale value doesn't exceed 10000000 which is wrong.
![image](https://user-images.githubusercontent.com/51195851/79995526-2747ad80-84d9-11ea-8201-e89de369d75e.png)

4. Go to the vendor profile from the backend and notice that the gross sale value remains the same.
![image](https://user-images.githubusercontent.com/51195851/79995711-5eb65a00-84d9-11ea-9d46-3d3babf6d274.png)

5. Also, inside the 'al log report' tab notice that the order total and the earning are both stuck at 10000000 which is incorrect as well.
![image](https://user-images.githubusercontent.com/51195851/79996058-cf5d7680-84d9-11ea-80f0-e667e02732ed.png)

**Expected Behavior:** The sale value should be 58,499,000 and Earning should be 58,498,992.

**Comment by ceefour** [comment]
What version is this fixed ?

**Comment by yasqihafizhana** [comment]
@sabbir1991 this issue was closed, can you please tell me which version that fixed this issue?
