### ISSUE TITLE
Product Addons being deleted after editing and saving product.

### ISSUE THREAD

**Issue by fdeross** [weDevsOfficial/dokan#822]
Resaving an already active product causes all of the product addon's options to be deleted.

I am also getting this error on a radio button:
Warning: Invalid argument supplied for foreach() in /srv/bindings/2b32a258165744099757614d506b4eda/code/wp-content/plugins/woocommerce-product-addons/templates/addons/radiobutton.php on line 24

Click on an item to edit it from the Products tab on the Dokan vendor dashboard. Click Save Product. Check addons and all of the options will have been deleted.

Here is a recorded video of steps to reproduce the bug.
https://drive.google.com/a/frostingmarket.com/file/d/1QVszrXJmOpP-anmP0VqRY9O01JWbPa2B/view?usp=sharing

I am using
Dokan - 3.0.3
Dokan Pro - 3.0.2
Product Addons - 3.0.31
Woocommerce - 4.0.1

**Comment by zamandevs** [comment]
Couldn't produce on our end. seems something went modified/wrong on your end. if you still having this issue please contact support.
