### ISSUE TITLE
Dokan – Admin commission on shipping depending delivery method

### ISSUE THREAD

**Issue by bledman113** [weDevsOfficial/dokan#824]
I am a dokan user, in dokan you can set shipping to vendor or to admin. Mainly i want to offer the possibility to vendor to choose ( so all shipping cost goes to vendors )

Flat rate shipping
Collect
Free delivery
and i want to add : ( to add it is not a problem )

ADMIN delivery service —> fees must go to admin and not to vendor.
so any idea how to get Admin delivery service fees in my earning and not to vendors ?

‘name’ => ‘shipping_fee_recipient’,
‘label’ => __( ‘Shipping Fee Recipient’, ‘dokan-lite’ ),
‘desc’ => __( ‘Who will be receiving the Shipping fees’, ‘dokan-lite’ ),
‘type’ => ‘select’,
‘options’ => array( ‘seller’ => __( ‘Vendor’, ‘dokan-lite’ ), ‘admin’ => __( ‘Admin’, ‘dokan-lite’ ) ),
‘default’ => ‘seller’
), `
–> this is the function when i can choose admin or vendor “function file in dokan”

**Comment by sabbir1991** [comment]
Hello, Dokan doesn't have such types of functionality for a vendor. We have one setting for shipping fee distribution in the admin end. So from admin if you select "Shipping fee recipient" as `Vendor` then the shipping fee adds with vendor earning and if select `Admin` then the shipping fee adds with admin earning. 

And finally, if you need to add extra admin charges as you describe above `Delivery Service fee` then you can handle this fee using the WooCommerce custom fee. There are lots of free plugin on wp.org. You can use any of them.
