### ISSUE TITLE
Fatal error: Trait 'WeDevs\Dokan\Traits\ChainableContainer' not found 

### ISSUE THREAD

**Issue by ravijethvaaphp** [weDevsOfficial/dokan#828]
Fatal error: Trait 'WeDevs\Dokan\Traits\ChainableContainer' not found 
getting issue in docken-pro plugin here is the complete log

E_ERROR was caused in line 9 of the file /home/gxeb0nghc1kz/public_html/wp-content/plugins/dokan-pro/includes/Module.php. Error message: Trait 'WeDevs\Dokan\Traits\ChainableContainer' not found

again this is from admin side

Fatal error: Trait 'WeDevs\Dokan\Traits\ChainableContainer' not found in /home/gxeb0nghc1kz/public_html/wp-content/plugins/dokan-pro/includes/Module.php on line 9
same error while activating it

My Server PHP version is php7.2

**Comment by saimonh3** [comment]
@ravijethvaaphp Thanks for opening the issue. We've fixed it in Dokan Pro, meanwhile make sure, Dokan Lite is installed before installing Dokan Pro.
