### ISSUE TITLE
Store.php template can not be overridden

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#831]
**Description of the bug:**

If you override the store.php file via a child theme the store page runs an infinitive loop.

**How to reproduce:**

Copy the store.php file and save it in your-theme/dokan folder.

Now check the store page.

**Comment by alamgircsebd** [comment]
> 
> 
> **Description of the bug:**
> 
> If you override the store.php file via a child theme the store page runs an infinitive loop.
> 
> **How to reproduce:**
> 
> Copy the store.php file and save it in your-theme/dokan folder.
> 
> Now check the store page.

When you try to use store.php file in your theme/dokan folder then you must be copy also the store-sidebar.php file in same same location theme/dokan

Until fix this issue we you can follow the instructions.
