### ISSUE TITLE
New products does not added to wc_product_meta_lookup table

### ISSUE THREAD

**Issue by SabolchGreba** [weDevsOfficial/dokan#836]
**Description of the bug:**
When I create a new product (on front end, Dokan Dashborad) the product isn't added to wc_product_meta_lookup table therefore this newly added product can't be sorted by price properly until I edit the product.

Maybe **handle_product_update()** triggers a method which is hooked to some function and adds product to lookup table but **NOT** in **handle_product_add()**.

I solved this in my theme by adding this to functions.php:
```
class WC_Dokan_Lookup_Table_Fix extends WC_Product_Data_Store_CPT {
    public function dokan_add_product_to_lookup_table( $post_id ) {
        $this->update_lookup_table($post_id, 'wc_product_meta_lookup');
    }
}

function dokan_add_product_to_lookup_table( $post_id ) {
    $lookup = new WC_Dokan_Lookup_Table_Fix();
    $lookup->dokan_add_product_to_lookup_table( $post_id );
}
add_action( 'dokan_new_product_added', 'dokan_add_product_to_lookup_table', 11 );
```

Is there any other way to fix this?

**Comment by zamandevs** [comment]
Product added nicely on wc_product_meta_lookup without edit. did not produce our end as you stated.

**Comment by sabbir1991** [comment]
It's already working on our default scenario. So we think there is no need to add any extra actions or filters to do this functionality. :)
