### ISSUE TITLE
Dokan giving Error when creating order with wc rest Api

### ISSUE THREAD

**Issue by gramz1** [weDevsOfficial/dokan#840]
Hi i am developing a mobile app for android for my store and i am using Dokan and Woocommerce for the store. If i create an empty order  via the rest api without products its working perfect. But if i try to create an order with products i get a 500 error . And if i go to Woocommerce logs i see the error Dokan get Cart error . Help me please i dont know what to do

**Comment by zamandevs** [comment]
Not sure how you tried. Tested with WC REST order creation API. everything is fine.

**Comment by sabbir1991** [comment]
We already have tested. We didn't found such types of errors.

![rest_success](https://user-images.githubusercontent.com/2692939/92463384-8f2f3400-f1ed-11ea-8073-323a697bcf85.png)
