### ISSUE TITLE
Unable to add/upload product feature image in Dokan add new product form while using Internet Explorer.

### ISSUE THREAD

**Issue by sohanHossainNabil** [weDevsOfficial/dokan#843]
**Description:** While using Internet Explorer I have noticed that the seller is unable to add product feature image because the add image button is not responsive. This happened while using IE v11.

**How to reproduce:**

1. Open Internet Explorer.
2. Go to the 'Product' tab in the seller dashboard.
3. Click on the 'add new product' button.
4. Now, if you try to click on 'upload a product cover image' you will notice that the button is not responsive.

**Expected Behavior:** The media uploader should open when clicked on the mentioned button.

**Comment by sabbir1991** [comment]
We don't support IE 11 right now.
