### ISSUE TITLE
Bug: Random Double Charge of PayPal Payment Gateway Processing Fee

### ISSUE THREAD

**Issue by oudin** [weDevsOfficial/dokan#847]
Hi 

When **"PayPal Identity Token"** is enabled in PayPal Standard and **IPN** is disabled as shown below:

<a href="https://ibb.co/YjqJVq5"><img src="https://i.ibb.co/C0T4STj/Screenshot-2020-05-15-Woo-Commerce-settings-Payal-identity-error.png" alt="Screenshot-2020-05-15-Woo-Commerce-settings-Payal-identity-error" border="0" /></a>

At random times the **"Payment gateway processing fee"** (e.g. 0.71) is charged twice/double. Which results in providing wrong **"Earning From Order"** of ($11.97) which should be ($12.68). 

Dokan is deducting/subtracting too much from the Vendor. See image.

<a href="https://ibb.co/180rrGf"><img src="https://i.ibb.co/SR6ttwX/Opera-Snapshot-2020-05-15-170044-double-fee.png" alt="Opera-Snapshot-2020-05-15-170044-double-fee" border="0" /></a>

Additionally, in the image below you can see transitions are doubled and both the **PDT** and **IPN** are executed. 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/MG3wqwY/Opera-Snapshot-2020-05-15-170044-double-trasactions.png" alt="Opera-Snapshot-2020-05-15-170044-double-trasactions" border="0" /></a>

This is because even if **"IPN Email Notifications"** is disabled, Dokan is still firing/executing it. This happens in v3.0.4 . 

Note: If **"IPN Email Notifications"** only is enabled and **"PayPal Identity Token"** is disabled this bug/issue does not occur in PayPal Standard. However if **IPN** is disabled and **PDT** is enabled this bug occurs. 

Here is a video of me placing an order with the issue:

Link: https://youtu.be/XNwOwc4aZZE

**Note:** this bug/issue occurs at random times therefore you will have to place between 30-50 orders both including from single and multiple vendors to replicate.

How can this be fixed?

**Comment by oudin** [comment]
Hello,

Any update on this issue, please?

Thank you

**Comment by Mohaiminulislam1989** [comment]
We can't reproduce this issue. Can you please share a video on how to reproduce this issue?
