### ISSUE TITLE
Map missing in vendor dashboard

### ISSUE THREAD

**Issue by marine7494** [weDevsOfficial/dokan#849]
Hi,
It used to work fine, but since I deactivate and reactivate Dokan Pro, the map on the "setting" part of vendor dashboard is blank. I can see the name of the location, but not the map itself.
If I go on the "product" part of the vendor dashboard, the map is here.

Seems there has been an issue during my plugin reset.

I compared the sourcing code of the page (my local site working VS my online site not working), and when I inspect element, the difference is : "class=mapboxgl-map" missing
Maybe could me the origin of the bug.

Any idea ?
Thanks a lot

**Comment by zamandevs** [comment]
Did not produce on our end. tried to produce as you stated. if you face this problem do not hesitate to comments here with more details.
