### ISSUE TITLE
Order notes in vendor dashboard

### ISSUE THREAD

**Issue by Hussnain1** [weDevsOfficial/dokan#852]
Hello, I want to show order notes author in vendor orders page. For example, when a vendor admin or staff adds an order note, i want to show the name or email. I can show that by "$note->comment_author". But when a vendor adds a note, it is saving as "Woocommerce" author in the database. Please see the image in below link: http://www.circle-m-development.com/baaqah_final/wp-content/uploads/2020/06/Screen-Shot-2020-06-15-at-11.15.03-AM.png Please get back to me as soon as possible. Thanks in advance.

**Comment by Hussnain1** [comment]
Hello,

Any update on this issue, please?

Thank you

**Comment by Hussnain1** [comment]
Hello,

Any update on above please?

Your quick reply would be greatly appreciated. Thanks

**Comment by alamgircsebd** [comment]
Hello @Hussnain1 

Until our next release you can follow the commits changes https://github.com/alamgircsebd/dokan/commit/d5ad97e12585a27ecc801d39e97464c97c3c9f8c

With this changes now inserting note author email id and user name

Thanks!

**Comment by Hussnain1** [comment]
Hi, Thanks for this.

This is working for vendor admin but not for vendor staff. Vendor staff has the same problem. What should I update for vendor staff?

Thank you

**Comment by Hussnain1** [comment]
@alamgircsebd Any update on this please?

**Comment by Hussnain1** [comment]
@alamgircsebd Any update on this please?

**Comment by alamgircsebd** [comment]
> 
> 
> @alamgircsebd Any update on this please?

We find out one issue with WooCommerce, Please follow the below instruction

File location: wp-content/plugins/woocommerce/includes/class-wc-order.php
change one line 
`if ( is_user_logged_in() && current_user_can( 'edit_shop_order', $this->get_id() ) && $added_by_user ) {`
to 
`if ( is_user_logged_in() && current_user_can( 'edit_shop_orders', $this->get_id() ) && $added_by_user ) {`

Hope after this change order note author will save correctly, and hope woocommerce solve this issue soon.

**Comment by alamgircsebd** [comment]
Here the commit which already merged with WooCommerce, hope WooCommerce next release will get this change. 
https://github.com/woocommerce/woocommerce/pull/26920
