### ISSUE TITLE
When using Dokan Vendor Subscription module it is not possible to allow Vendors to sell Woocommerce Subscription Products

### ISSUE THREAD

**Issue by cmooki** [weDevsOfficial/dokan#853]
If Admin has Dokan Vendor Subscription Module activated, marketplace vendors cannot sell Woocommerce Subscription products because there is no option to activate 'Subscription products' within the Dokan Vendor Subscription Module. See screenshot.

![Screenshot 2020-06-22 at 08 47 08](https://user-images.githubusercontent.com/2536752/85262007-06fa8780-b465-11ea-846d-a53929e6f262.jpg)

**Comment by alamgircsebd** [comment]
Hello @cmooki 

Hope you have install WooCommerce Subscriptions plugin and active it. This is not a valid plugin issue as you see. Make sure you have configure all things with Vendor Subscribe Module. Follow this one - https://wedevs.com/docs/dokan/modules/dokan-vendor-subscription-product/

If you still getting this problem please submit a ticket to our support team.

Thanks!

**Comment by cmooki** [comment]
Hello, I submitted this issue via ticket on 25th May. One of the wedevs team replied and said; 

_"We are sorry for the inconvenience. We have already noticed the issue and assigned the tasks to our developers. It will be fixed and released in future update."_

It was not fixed in this latest update, so I thought I would add it here for more exposure.

**Comment by alamgircsebd** [comment]
> 
> 
> Hello,
> 
> Yes; Woocommerce Subscriptions plugin is active and Dokan documentation has been read.
> 
> I have already submitted this issue via ticket on 25th May. One of the wedevs team replied and said;
> 
> _"We are sorry for the inconvenience. We have already noticed the issue and assigned the tasks to our developers. It will be fixed and released in future update."_
> 
> It was not fixed in this latest update, so I thought I would add it here for more exposure.

is your using version Dokan Pro 3.0.3 and Lite 3.0.5?

**Comment by cmooki** [comment]
Yes; both of the recent updates have been applied. When the latest Pro/Business as released and I notice there was no fix to the issue, I updated my Dokan ticket and asked if there was any update on when i would be fixed.

Dokan support replied on 20th June and said;

_Hopefully, the developers will work on it soon. As I said it is hard for me to guarantee when an improvement will be added but it is in the work so we will see it soon._

So, as far as I can see, this is an issue that is already known to the Wedevs development team and is being worked on (or in pipeline to be worked on).

- Are you saying this is working as expected for you? 
- Do you see 'Woocommerce Subscription Product' as an 'Allowed Product Type' option (when Woocommerce Subscription plugin is active and Dokan Vendor Subscription Module activated)?

**Comment by alamgircsebd** [comment]
> 
> 
> Yes; both of the recent updates have been applied. When the latest Pro/Business as released and I notice there was no fix to the issue, I updated my Dokan ticket and asked if there was any update on when i would be fixed.
> 
> Dokan support replied on 20th June and said;
> 
> _Hopefully, the developers will work on it soon. As I said it is hard for me to guarantee when an improvement will be added but it is in the work so we will see it soon._
> 
> So, as far as I can see, this is an issue that is already known to the Wedevs development team and is being worked on (or in pipeline to be worked on).
> 
>     * Are you saying this is working as expected for you?
> 
>     * Do you see 'Woocommerce Subscription Product' as an 'Allowed Product Type' option (when Woocommerce Subscription plugin is active and Dokan Vendor Subscription Module activated)?

Yes we see as expected, okay i will talk with our support team about your issue. Thanks!

**Comment by cmooki** [comment]
OK, thanks. Ticket ID is #368805. 
Support agent has replied 3 times over the past month, each time "confirming" that the issue was known about.

**Comment by cmooki** [comment]
I haven't heard back here, so I will reply to Ticket ID is #368805 and ask the agent to check your reply here @alamgircsebd to clarify if this is a known issue or is not...because the replies are conflicting.

It leaves us in a position of not knowing if we should be troubleshooting at our end (as is suggested in this thread/reply) or not, because it is a known issue (as per ticket #368805).

**Comment by alamgircsebd** [comment]
> 
> 
> I haven't heard back here, so I will reply to Ticket ID is #368805 and ask the agent to check your reply here @alamgircsebd to clarify if this is a known issue or is not...because the replies are conflicting.
> 
> Now we do no know if we should be troubleshooting at our end (as is suggested in this thread/reply) or not, because it is a 'known issue' (as per ticket #368805).

Sorry for delay! I see this is a new features which one not implement yet. We are working on this point. So please wait until our next release for Dokan Pro version. 

Thanks

**Comment by zamandevs** [comment]
Fixed on pro version.

**Comment by ProRealCode** [comment]
@cmooki Hi, I was wondering if you manage to get recurring payment working for your website using this StripeConnect module from Dokan with WC Subscription? I would greatly appreciate your reply as I'm not able to get any other client confirming it is successfully working on their environment. Thanks in advance.

**Comment by nurul-umbhiya** [comment]
Hello @ProRealCode, we are working hard to fix this issue and we are really close to solving this issue. Kindly be patient for a few more days. I really apologize for this inconvenience.

**Comment by Mohaiminulislam1989** [comment]
Done. Fixed on dokan PRO
