### ISSUE TITLE
When product categories are restricted (via Dokan Vendor Subscription Module), a Vendor can create new categories using import feature (also product types, attributes etc)

### ISSUE THREAD

**Issue by cmooki** [weDevsOfficial/dokan#854]
The restrictions set using Dokan Vendor Subscription Module (eg restrict categories) only work on the Vendor dashboard 'front end' interface.

If a Vendor uses the import functionality, the restrictions set are ignored (eg vendor can add to any category &/or create categories).

**Comment by zamandevs** [comment]
Fixed on pro version.
