### ISSUE TITLE
Shipping template file: When we update the \dokan-pro\templates\settings\shipping.php it has zero effect

### ISSUE THREAD

**Issue by cmooki** [weDevsOfficial/dokan#857]
We wish to edit the Vendor Dashboard > Settings > Shipping (/dashboard/settings/shipping/#/) 

However, when we make updates to  \dokan-pro\templates\settings\shipping.php it has zero effect.

![Shipping screenshot 2020-06-23 at 20 13 22](https://user-images.githubusercontent.com/2536752/85450099-54bfde80-b590-11ea-9cb5-0e3c8452b8bd.jpg)

**Comment by Umar47** [comment]
Hi, I am also experiencing the same issue!

Can you anyone let me know how I can edit this file using child-theme?

**Comment by cmooki** [comment]
Dokan "support" replied to the ticket. As with most Dokan replies from from "support engineers" it was a poor quality reply, without adequate information and is patronizing — many Dokan support replies are patronizing 👎  :(

**SUPPORT REQUEST:**
We are trying to customize the Dokan vendor shipping settings page. Screenshot: https://ibb.co/fS9nmCV We already tried editing dokan-protemplatessettingsshipping.php but cannot see any changes. Please can you provide us with the location of the template files to edit the shipping setting pages? Thanks

**SUPPORT REPLY:**
Hello, 

Welcome to Dokan Support, 

The shipping template file is: plugins/dokan-pro/templates/settings/shipping.php ( the old shipping ) 
Most of the files that is related to shipping is on .js . So you may need some details customization on the coding end. 

I am so sorry to say that you are unable to achieve the requirement by default. You will need modification on the coding-end to achieve the requirement you have. It needs detailed coding in multiple file locations.  I am afraid a single line code cannot help you so it is out of our league.

We are unable to provide support for customizations under our Support Policy https://wedevs.com/support-policy. If you are unfamiliar with code/templates and resolving potential conflicts, contact a developer.

Thank you for your understanding.

**Comment by cmooki** [comment]
**Reply from Dokan (after I followed up on the poor quality reply above). It is not a great reply, but it is better than previous reply and at least it gives us some information. We will look into it more this week:**

The template file does not have the zone base shipping codes that is why it is not working.

The zone-based shipping is included in the js files these are not templates files. 
For example :

/dokan-plugin/assets/src/js/shipping.js
/dokan-plugin/includes/Admin/Views/whats-new.php
/dokan-plugin/includes/Shipping/Methods/ProductShipping.php
/dokan-plugin/includes/Shipping/Methods/VendorShipping.php
/dokan-plugin/includes/Shipping/ShippingZone.php
/dokan-plugin/assets/js/vue-pro-frontend-shipping.js:
And more.

So I could not mention a template that can help you modify the section you shared screenshot of. I am really sorry but as there are a lot of files for the shipping codes I could not mention all of them. But there is no single template file that i could mention to help.

**Comment by Umar47** [comment]
Can you please ask them how we can specifically move these below boxes
under the shipping zone table list? and after that how we can customize
this table layout? I mean from where/which file this "shipping zone table"
is generating?


Zone NameRegion(s)Shipping Method
Locations not covered by your other zones
<https://loko.li/dashboard/settings/shipping/#/zone/0>
<https://loko.li/dashboard/settings/shipping/#/zone/0>
Everywhere

Flat Rate
Local Delivery <https://loko.li/dashboard/settings/shipping/#/zone/3>
<https://loko.li/dashboard/settings/shipping/#/zone/3>
United Kingdom (UK)

Local Pickup
Local Delivery (Zone 2)
<https://loko.li/dashboard/settings/shipping/#/zone/4>
Edit <https://loko.li/dashboard/settings/shipping/#/zone/4>
United Kingdom (UK)

Flat Rate, Flat Rate



Processing Time
1 business day1-2 business days1-3 business days3-5 business days1-2 weeks2-3
weeks3-4 weeks4-6 weeks6-8 weeksReady to ship in...
Shipping Policy
Refund Policy

**Comment by Umar47** [comment]
Hi, this is a test email (just for checking)

**Comment by cmooki** [comment]
Update incase anybody else is trying to edit shipping:

The shipping template provided is only for the 'old' shipping method. There is no shipping template provided for Zone Based shipping.

Hopefully a template option is provided soon so shipping page(s) can be edited - we want to improve the UX.
