### ISSUE TITLE
Dokan Stripe Connect does not support recurring payments (Woocommerce Subscription Product)

### ISSUE THREAD

**Issue by cmooki** [weDevsOfficial/dokan#858]
From what we can see, Dokan Stripe Connect does not support automatic recurring payments (ie. Woocommerce Subscription Products). We have followed https://wedevs.com/docs/dokan/modules/dokan-vendor-subscription-product/ and there is no mention about payment gateways.

**How to test:**

- Activate Dokan Stripe Connect as your payment method and configure. 
- Install Woocommerce Subscriptions plugin. 
- Activate Dokan Vendor Subscription Module. 
- Create a Subscription product. 
- Attempt to purchase the subscription product. 

You will see a message when trying to check out saying _"Sorry, it seems there are no available payment methods which support subscriptions. Please see Enabling Payment Gateways for Subscriptions if you require assistance."_ 

* View WooCommerce > Settings > Payments: you will see there is no recurring 'check/tick" beside "Dokan Stripe Connect" method to indicates that it supports automatic recurring payments (as stated here: https://docs.woocommerce.com/document/subscriptions/enabling-payment-gateways-for-subscriptions/ )

Note that otherwise, Dokan Stripe Connect is working correctly (Vendors can connect, non-subscription products can be purchased). This problem is only re. subscription products.

![Enabling-Payment-Gateways-for-Subscriptions-Woo-Commerce-Dokan-Stripe-Connect](https://user-images.githubusercontent.com/2536752/85465351-9b1d3980-b5a0-11ea-8148-3b0437f5e769.png)

**Comment by cmooki** [comment]
Update: I have noticed in documentation https://wedevs.com/docs/dokan/modules/how-to-install-and-configure-dokan-stripe-connect/  there are 2 "conflicting" screenshots.

**The 3rd screenshot shows Settings**
This is the same/similar as what we see in Dokan Stripe Connect settings: an "Enable Stripe" checkbox and NO other text at top of screen.

**The 8th screenshot shows Settings**
However it is different to the 3rd screenshot and has additional text/information, "Recurring subscription requires webhooks to be configured...etc". This does NOT exist in our Settings - ours are the same as 3rd screenshot in documentation.

The 3rd & 8th screenshots do not correlate / match. Something is missing from the documentation. Is there another plugin that needs added? ie. Is the 8th screenshot from a different plugin (not from Dokan Stripe Connect)?

![Dokan Stripe Connect Docs and Screenshots](https://user-images.githubusercontent.com/2536752/85520833-57a3e900-b5fb-11ea-92f7-1f24ed2217c0.png)

**Comment by cmooki** [comment]
Status /Tests:

* Dokan Stripe Connect = Vendors can connect and normal products can be purchased. :)
* Dokan Stripe Connect = subscription products cannot be purchased. :( 
* Any other Stripe plugin = subscription products process correctly.

From the above, it looks like Dokan Stripe Connect has a problem with recurring payments (Dokan Vendor Subscription Module).

![Screenshot 2020-06-29 at 13 24 57](https://user-images.githubusercontent.com/2536752/86005409-87445e00-ba0c-11ea-86a0-10da4fb8abc8.jpg)

**Comment by cmooki** [comment]
It has been confirmed there is a bug and they are working on it as a priority fix / update.

**Comment by sabbir1991** [comment]
It's fixed on the pro version.

**Comment by ProRealCode** [comment]
Sorry but recurring payment is not functional since the initial release of the feature. Been in discussion for months now (since April?) about the issue with the Support and still no improvements have been made. 
First initial payment is working. But the payment failed on the first recurrence, seems that the POST message sent to Stripe is not well formatted (ressource_missing)? I would be pleased if someone with a successful recurring payment with this module could answer.  
<img width="1920" alt="dokan error _ ressource missing" src="https://user-images.githubusercontent.com/23722067/99950976-a659d880-2d7d-11eb-961c-49ea795c52a7.png">
