### ISSUE TITLE
Multiple email to admin for sub-orders

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#866]
**Description of the issue:**

When an order is made from multiple vendors the admin gets email notification for each sub-order. - https://prnt.sc/tdbgg8

**Expected behavior:**

The admin should only get the parent order notification email.

Possible function which can be related - **dokan_stop_sending_multiple_email()**

**Comment by gerbz** [comment]
Same goes for customer order confirmation emails.  The customer receives an email confirmation for the parent order AND each sub order.
