### ISSUE TITLE
Product reducing twice if purchase from two vendor 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan#868]
Description : 

If you purchase a product from two vendors ( 1 from each) the analytics show double ( 2 from each ) 

How to reproduce: 
Details video 
https://www.loom.com/share/2de7fa5c78d548f497bdc72992bbec94

**Comment by yward** [comment]
Sadly the pull request (which was approved and merged) doesn't work on old analytics, old order still shows double order for values (i.e. if you buy 2 items, one for 4$ from vendor A and the other for 5$ from vendor B, analytics will show 3 orders, one for 9$, one for 4$ and one for 5$ doubling the original order amount in your analytics.)

**Comment by yward** [comment]
Update: the issues seems to be resolved when you use the filter "Refunds: none" in order view.

So it seems that dokan is telling woocommerce that the duplicate orders are refunded rather than competely hiding/deleting them.
