### ISSUE TITLE
Simple Q.A. Not exactly an issue. 

### ISSUE THREAD

**Issue by kabirbd89** [weDevsOfficial/dokan#880]
I am going to open a multivendor website as a test beside my physical store. And trying with dokan as everyone recommended it. This is a simple plugin but I can't found an option on it both in the admin area and vendor dashboard.

1. How can a vendor add/edit attributes for there products? I didn't see it yet anywhere in the vendor dashboard. In Free Version. 
2. There is no way to add a product it demo and also edits option is not working in demo. So I am not sure yet about this.

Can anyone help me out of this?

**Comment by kapilpaul** [comment]
Hello @kabirbd89 

Thanks for your query. Here is the answer:

1. You can add/edit attributes for products in dokan pro version.
2. You can add/edit products from vendor dashboard in dokan-lite version. Please check the screenshot for reference: https://prnt.sc/ude2kw

** if you are not able to go to product edit then resave your permalink from wp admin backend > Settings > Permalinks.
