### ISSUE TITLE
Single Product Multiple Vendor: "Top Rated Vendor" option is missing from the Show SPMV Products dropdown

### ISSUE THREAD

**Issue by dariodev** [weDevsOfficial/dokan#899]
The [documentation ](https://wedevs.com/docs/dokan/modules/single-product-multiple-vendor/) of the Dokan Single Product Multiple Vendor module says we should have four options in the "Show SPMV products" dropdown (Show all products, Min price, Max price, Top-rated vendor).

In our test installations, we do not have a fourth option - "Top rated vendor". 
Multiple vendors were entered, and some received a rating.
Is there anything else to do to get this option?

![image](https://user-images.githubusercontent.com/1420451/91457507-b5b3ad80-e884-11ea-97d1-ac46d0dbf5d6.png)

**Comment by ediamin** [comment]
Hi @dariodev you need [Store Reviews](https://wedevs.com/docs/dokan/modules/vendor-review/) module for that. Once you activate the `Store Reviews` module, you should see the `Top-rated vendor` option in your dropdown.

Closing this issue now. Feel free to reopen if you still get an error.
