### ISSUE TITLE
Downloadable product "Grant Access" JS error

### ISSUE THREAD

**Issue by rashedripon** [weDevsOfficial/dokan#901]
**Description of the bug:**
When a vendor tries to add a downloadable product permission from the order, the "Grant Access" button gives the admin-ajax.php 500 (Internal Server Error) message.
The file gets added if checked by reloading the page but initially it shows error - https://prnt.sc/u87z3u

**How to reproduce:**
* Make sure to have at least one downloadable product
* Edit any of the order of the vendor
* Scroll down and try to add a product for download permission

**Comment by alamgircsebd** [comment]
> **Description of the bug:**
> When a vendor tries to add a downloadable product permission from the order, the "Grant Access" button gives the admin-ajax.php 500 (Internal Server Error) message.
> The file gets added if checked by reloading the page but initially it shows error - https://prnt.sc/u87z3u
> 
> **How to reproduce:**
> 
> * Make sure to have at least one downloadable product
> * Edit any of the order of the vendor
> * Scroll down and try to add a product for download permission

@rashedripon this not a valid issue, we did reproduced the issue, can you confirm it with another environment or you can on our dev test location

**Comment by sabbir1991** [comment]
Invalid issue. This issue produces for a specific client for file permissions. This is not our plugin core issue

**Comment by sohanHossainNabil** [comment]
@alamgircsebd @sabbir1991 this issue does exist. I just tested this on my local environment and one of the client's sites as well.

**Comment by ecottles** [comment]
Hello,
I am the source of this issue that started this thread. The issue is indeed a core issue. And still persists. 
You need to include he following in dokan-lite/includes/Ajax.php the following:
 use WC_Customer_Download;

Good Day
