### ISSUE TITLE
Dokan compatibility with multi-currency solutions

### ISSUE THREAD

**Issue by fabiomail** [weDevsOfficial/dokan#902]
Hello, this is not a bug, more like a missing feature for Dokan. 

Right now, Dokan is missing compatibility with any multi-currency solution, creating major issues for International Multi-vendor Marketplaces. 

Can somebody start looking into this?

**Comment by Sk-Shaikat** [comment]
Hello @fabiomail, thank you for your suggestion. We have already a plan to make dokan compatible with multi-currency. Please stay tuned with us. Dokan will have this feature very soon.

Thank you

**Comment by fabiomail** [comment]
@Sk-Shaikat that's great, thank you for the update. May I ask if you plan to integrate this feature internally or via integration with third-party solutions? If the latter, which third-party solution are you considering?
