### ISSUE TITLE
Vendor balance remain same after refund

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#905]
**Description:** 
When the admin refunded an order from the backend, after a successful refund the admin commission turned 0 but the vendor earning remains the same.
Refunded Orders - https://prnt.sc/u9943i
Vendor Current Balance - https://prnt.sc/u994im

**How to reproduce the bug:**
- Make an order completed and check vendor balance
- Then refund the order from the backend
- The vendor balance remains the same on the vendor dashboard

**Expected Behaviour:**
- The vendor balance should reduce after a successful refund.

**Comment by fabiomail** [comment]
What about if you initiate a refund from the vendor dashboard?

**Comment by alamgircsebd** [comment]
> **Description:**
> When the admin refunded an order from the backend, after a successful refund the admin commission turned 0 but the vendor earning remains the same.
> Refunded Orders - https://prnt.sc/u9943i
> Vendor Current Balance - https://prnt.sc/u994im
> 
> **How to reproduce the bug:**
> 
> * Make an order completed and check vendor balance
> * Then refund the order from the backend
> * The vendor balance remains the same on the vendor dashboard
> 
> **Expected Behaviour:**
> 
> * The vendor balance should reduce after a successful refund.

@tanjiralmamun please check this commit https://github.com/alamgircsebd/dokan/commit/b8a8e9a0b0e33cedf70fe763dfd7224df92372b5

**Comment by tanjiralmamun** [comment]
@alamgircsebd It is working well now
