### ISSUE TITLE
global commission setup for vendors 

### ISSUE THREAD

**Issue by ssathamenterprises** [weDevsOfficial/dokan#915]
hello i use  DOKAN pro   when i set global commission for vendors its not set automatic to all vendors please check and help this thanks

**Comment by sabbir1991** [comment]
Hello, Can you please specify the issue whats the actual problem. Let me clear something, If you set global commission for all vendors then those commissions not showing in vendor single edit or user profile edit page. But it automatically works after the customer place an order.

If you have still confusion then please send me a video or screenshot.

Thanks :)

**Comment by ssathamenterprises** [comment]
![Screenshot (25)](https://user-images.githubusercontent.com/68118999/92556244-04594280-f29c-11ea-85d9-cb106d96c66b.png)


newly register vendor ( but the admin commission not shows here )

**Comment by ssathamenterprises** [comment]
and also user profile section not shows the admin cost

**Comment by alamgircsebd** [comment]
hello @ssathamenterprises 

Thanks for share screenshot, this is only vendor overview reports area, here you see commissions after add product and when some one place order. 

Actually global commission not showing any where but it will effected automatically for all vendor until set vendor wise commission

Also Dokan have 4 types commission, see details here - https://wedevs.com/docs/dokan/tutorials/how-to-setup-dokan-vendor-commission/

But i agree with you one thing here showing Admin commission 0 here we getting one issue. Thanks for point out this point, we will solve this issue soon and make sure this updates will have on  next release. 

Thanks

**Comment by ssathamenterprises** [comment]
thanks

**Comment by ssathamenterprises** [comment]
When you will fix this bug ?

**Comment by alamgircsebd** [comment]
> 
> 
> When you will fix this bug ?

This bug not resolve yet, we trying to fix this before our next release.

**Comment by ssathamenterprises** [comment]
thank you so much waiting for that

**Comment by alamgircsebd** [comment]
For now we changed admin commission label to Admin Commission Rate [ screenshot https://prnt.sc/wkvb8p ]

**Comment by alamgircsebd** [comment]
Resolved on dokan pro
