### ISSUE TITLE
Suggestion related to "Update Settings" button 

### ISSUE THREAD

**Issue by shawon786** [weDevsOfficial/dokan#93]
Vendors usually forget to click on "Update Settings" button after uploading Banner and Profile Image.
Since the Button is at the bottom they miss this.

Solutions: Can we have this button 'above as well'?
Or We can provide a popup error message.
Or Simply Add a Message box at the top stating: "Please Click 'Update Settings' Button below after making changes."

**Comment by alamgircsebd** [comment]
Resolved here https://github.com/weDevsOfficial/dokan/pull/1053
