### ISSUE TITLE
Email sending issue with bulk order status change

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#937]
**Description of the Bug:**
If try to manually change the order status of more orders, only the one order sends an email with an invoice. The rest do not send emails and do not generate invoices even if the status changes. 

Here are also examples of other behavior when it comes to handling suborders (orders from multiple vendors): If select just the suborders and change status, the above-mentioned situation happens.

**_Video URL:_** https://youtu.be/VMqC0pk4QMo

**How to reproduce:**
- Create 2/more orders
- Change the status bulk from the admin panel
- Only the 1st order's email will send

- Again create 2/more orders
- Change the order status from the vendor panel
- Only the last order's email will send

- Create a suborder
- Toggle Suborder
- Select only sub-orders and change the status
- Only the 1st sub-orders email will send

**Expected Behavior:**
Emails should be sent if bulk order status change

**System Status:**
WordPress: 5.5.1
Dokan Lite: 3.0.9
Dokan Pro: 3.0.8
WooCommerce: 4.6.0

**Comment by rajankarmakar** [comment]
Already fixed.

**Comment by nurul-umbhiya** [comment]
@tanjiralmamun bhai kindly check this issue and take necessary steps

**Comment by tanjiralmamun** [comment]
@nurul-umbhiya Bhai, you can close this one as the multiple email has been disabled for not to send sub-orders emails to customers. So, this cannot be merged.
