### ISSUE TITLE
Store Category Widget Bug

### ISSUE THREAD

**Issue by NenadObradovic** [weDevsOfficial/dokan#957]
Hi guys,

In your Dokan Store Category Menu Widget not all terms of product are added to category list. If product has multiple categories set, only the first one will be added to the list.

For example, if you have Accessorize and Children category, and you DON'T have them separately set on items, Children category will not be be shown.

In template-tags.php on line 541 is array_push($all_terms, $terms[0]);
We are sending you the example of the fix (add code in blue square and delete the one in red square).

https://imgur.com/a/W8I3Eou

Best regards,
Nenad

**Comment by alamgircsebd** [comment]
Resolved this issue already https://github.com/weDevsOfficial/dokan/pull/1019
