### ISSUE TITLE
Store Search: Can't search store by the store name

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/dokan#958]
**Description of the Bug:**
In the **_Dokan > Vendors_** panel, Stores cannot be searched by the Store Name. The search result display by the store owner's first name, last name, or nice name.

**_Video URL:_** https://youtu.be/B3Hz471HgxY

**How to reproduce:**
- Navigate to the **_Dokan > Vendors_** panel
- Search a store by the Store Name.
- Store will not appear in the search result
- Search with the store author name (Firstname, Lastname, nickname, nice_name)
- Now the Store will appear in the search result

Please make sure that the store name shouldn't match along with the store author name.

**Expected Behaviour:**
The store should be searchable with the store name.

**Comment by alamgircsebd** [comment]
@kapilpaul vai this issue did not fixed properly, this issue still have on backend area Dokan=>Vendor List i have checked the issue and this one valid issue. Please review it properly with issue descriptions.

**Comment by alamgircsebd** [comment]
It not working only when try to search with spacial character like this https://www.awesomescreenshot.com/video/1912454?key=3101e7d9d33268d8778a4be93845b35d

**Comment by kapilpaul** [comment]
@alamgircsebd thank you for mentioning the above problems. I will check it.
