### ISSUE TITLE
Dokan Stripe connect failed with recurring payment with Subscription products

### ISSUE THREAD

**Issue by ProRealCode** [weDevsOfficial/dokan#961]
I'm posting this problem here since it's always in default since my first support service calls in April.
Recurring payments with your Stripe Connect module do not work.
The first payment works correctly, but as soon as the first payment is due, the payment is "failed".
I attach below the logs and Stripe error reports.

I specify that the settings are correct (API/secret keys in test mode) + URL webhook. The problem persists on 3 different websites.

To date, it has never been confirmed to me that you know the problem internally. There have been several revamps of your connection to Stripe (seen in the logs), but nothing has been successful for my problem. I would be extremely grateful if you could keep me informed about the evolution of the correction of your Stripe payment module for recurring payments via WC Subscription. 
<img width="1920" alt="dokan error _ ressource missing" src="https://user-images.githubusercontent.com/23722067/99952303-b70b4e00-2d7f-11eb-8818-aea074751f67.png">

**Comment by ProRealCode** [comment]
**A few tips about the issue:**

1. Manual renewal is working, under the customer /my-account/subscriptions tab.

2. I found that the problem for automatic renewal is located in this function (**StripeConnect.php**): **create_intent_for_renewal_order**
$request['source'] doesn't get any value with $prepared_source->source , that's why we get an invalid source error in Stripe Response body.

I'm sure there is no big problem there? The Request POST body seems to be not well formatted with the source query.

**Comment by nurul-umbhiya** [comment]
we are handling this error and then the charge is also made with PaymentIntent status: requires_action. you'll be able to find this charge info under Stripe Dashboard --> Payments --> All section,  what we need to do is authorized that payment. Hopefully, we'll be able to solve this issue real soon, and after we get the confirmation from the testing team, hopefully, we can add this fix to the next release InshaAllah.

**Comment by ProRealCode** [comment]
Thanks for your swift reply, it is a pleasure to get real technical infos on this issue (been discussing this for months with the support). 
Are you planning to add the SCA compatibility for the recurring payment? by using the saved cards and without the client authorization. As far as I know the recurring payment with your StripeConnect module are not yet compatible?

**Comment by nurul-umbhiya** [comment]
Stripe non3d isn't SCA compatible but stripe3d is. We are using Payment Intents API (which is SCA-ready API) for collecting both one time and recurring payments using stripe3d.

**Comment by ProRealCode** [comment]
ok, so since European regulation mandates that full enforcement of Strong Customer Authentication (SCA) begins on 31 Dec 2020, after this date we will be forced to use the "3D Secure and SCA" option in the settings (picture attached).
<img width="322" alt="3d secure" src="https://user-images.githubusercontent.com/23722067/100888503-7bc2fa80-34b6-11eb-817c-79c7a44c9ec3.png">.
It is nice to know that recurring payments are working with it because client support tells me many times it doesn't!? Thank you again.

**Comment by ProRealCode** [comment]
Another question regarding the SCA regulation:
Is the SCA/3D payments made through the module are still made with "direct charge" like without SCA?

**Comment by ProRealCode** [comment]
Hi, is there any progress please? Do you need something? Thanks.

**Comment by nurul-umbhiya** [comment]
We already fixed this issue and is on the testing phase now, hopefully, we can ship this in the next release inshaAllah.

**Comment by Mohaiminulislam1989** [comment]
Fixed in PRO
