### ISSUE TITLE
Dokan Order Discount issue when recalculate order from Woocommerce Backend. 

### ISSUE THREAD

**Issue by royrakesh** [weDevsOfficial/dokan#962]
Hi.
When sub order created by Dokan it adds order discount properly but when order recalculates from Backend the order saved without considering the order discount. http://prntscr.com/voxv0b

**Comment by Mohaiminulislam1989** [comment]
Hello @royrakesh, Thank you for informing us about the issue. We are checking the issue. Hope you will get the fix soon.

**Comment by royrakesh** [comment]
```
add_action( 'woocommerce_order_after_calculate_totals', 'dokan_fix_order_discount' , 99998 , 2);

function dokan_fix_order_discount($and_taxes, $order){
    $order_discount          = 0;
    $quantity_discount       = 0;
    $order_total             = $order->get_total();
    $order_id                = $order->get_id();
    $discounts = dokan_get_discount_by_order( $order_id );
    if ( empty( $discounts['order_discount'] ) && empty( $discounts['quantity_discount'] ) ) {
        return;
    }
    if ( ! empty( $discounts['order_discount'] ) ) {
        $order_discount  = $discounts['order_discount'];
    }
    if ( ! empty( $discounts['quantity_discount'] ) ) {
        $quantity_discount = $discounts['quantity_discount'];
    }
    $new_total = ($order_total -  $order_discount - $quantity_discount);
    $order->set_total( $new_total );
}
```

I am able to fix this with the above code.
Add this code into your `functions.php`
You just need to recalculate the order if your order has wrong value.
Others can use the code until @weDevsOfficial release a fix.

**Comment by alamgircsebd** [comment]
Hello @royrakesh 

Thanks for given the fix, our QA team will test this changes if every things fine then will have this changes on our next release

**Comment by royrakesh** [comment]
```
add_action( 'woocommerce_order_after_calculate_totals', 'fix_order_discount' , 99998 , 2);

function fix_order_discount($and_taxes, $order){


        
            $order_discount          = 0;
            $quantity_discount       = 0;
            $order_total             = $order->get_total();
            $order_id                = $order->get_id();
            
            
            $discounts = dokan_get_discount_by_order( $order_id );

            if ( empty( $discounts['order_discount'] ) && empty( $discounts['quantity_discount'] ) ) {
                return;
            }
        
        
            if ( ! empty( $discounts['order_discount'] ) ) {
                $order_discount  = $discounts['order_discount'];
            }
        
            if ( ! empty( $discounts['quantity_discount'] ) ) {
                $quantity_discount = $discounts['quantity_discount'];
            }
  
            $new_total = ($order_total -  $order_discount - $quantity_discount);
            $order->set_total( $new_total );


}
```

Quick Fix

**Comment by royrakesh** [comment]
@alamgircsebd Hi Any update when you are going to push the code to release?

**Comment by kapilpaul** [comment]
@royrakesh Hi, can you please tell us how to reproduce the issue? because I am trying to reproduce this, did not find anything in here. recalculates the value and exactly the same amount remains in the main order and sub-order also. reports are also fine.

**Comment by codehaveli** [comment]
Step to reproduce
1. First place an order which has order discount from the vendor. `(let's assume Subtotal 200, Order Discount: 20, Order Total: 180).`
2. Then you will see Order total as `180` from the backend.  
3. Now if you update/recalculate the order from backend admin panel then you will see Order total became `200` from `180`.

**Comment by royrakesh** [comment]
Step to reproduce

1. First place an order which has order discount from the vendor. (`let's assume Subtotal 200, Order Discount: 20, Order Total: 180`).
2. Then you will see Order total as `180` from the backend.
3. Now if you update/recalculate the order from backend admin panel then you will see Order total became `200` from `180`.

**Comment by kapilpaul** [comment]
@royrakesh Thanks for explaining this. This is a pro feature. Hopefully, this will solve in the next release.

**Comment by royrakesh** [comment]
Yes, This is a Pro feature I should have mentioned this earlier.
