### ISSUE TITLE
SetupWizard: To make a withdrawal , bank transfer toggle is not working  from admin setup wizard

### ISSUE THREAD

**Issue by shanjidah** [weDevsOfficial/dokan#971]
Title: When admin want to add Bank transfer to make a withdrawal then toggle is not working
How to reproduce:
1.Install wocommerce
2.Activate dokan lite
3.Setup admin wizard
Actual Scenario: Toggle is not working
version: WooCommerce 4.7.1
Dokan lite & pro latest version
Here is the video link:
https://www.awesomescreenshot.com/video/1874418?key=029c1bb759e7378aa24a174c5eb55a03

**Comment by FaraziF** [comment]
fix from #989 Pull Request
