### ISSUE TITLE
Maps shows wrong count 

### ISSUE THREAD

**Issue by ssathamenterprises** [weDevsOfficial/dokan#973]
My website have 72 stores but in maps shows 9 only 
![D595CDBF-4859-467B-85BE-8D26A1CB3ECC](https://user-images.githubusercontent.com/68118999/100756188-f2fd7d80-3427-11eb-97b3-1cb6e215ca7e.jpeg)
![0C45300E-382C-408A-9FD4-50178D995F49](https://user-images.githubusercontent.com/68118999/100756205-f85ac800-3427-11eb-9d65-dc2bb39e3531.jpeg)

**Comment by hasinur1997** [comment]
@ssathamenterprises Couldn't find the issue.
![Screenshot 2021-01-07 at 2 58 21 PM](https://user-images.githubusercontent.com/9369061/103873422-f5738700-50f9-11eb-85ee-37a265331be5.png)

**Comment by Mohaiminulislam1989** [comment]
Fixed already

**Comment by ssathamenterprises** [comment]
Still the same

**Comment by ssathamenterprises** [comment]
![CEABD352-2C6A-455C-A6FB-8A67F40B849C](https://user-images.githubusercontent.com/68118999/108319378-48158800-71fc-11eb-8cd3-045c23331e3f.png)

https://tamizhashop.in/store-listing-3/  

Check my link

**Comment by ssathamenterprises** [comment]
Yes works

**Comment by Mohaiminulislam1989** [comment]
We are showing the count based on pagination. We show the map count based on your current page store count.

**Comment by ssathamenterprises** [comment]
Yes I got it , page by page it’s shows the count
