### ISSUE TITLE
Erroneous order note about reducing stock

### ISSUE THREAD

**Issue by kvasbo** [weDevsOfficial/dokan#978]
When creating an order with two or more vendors, an order note is added both to the main order and the suborders saying that the stock of the product has been reduced. This note is wrong for one of the orders, as the reduction is calculated twice (e.g. 2->1, 1->0 for a product with two in stock). The actual stock reduction is performed correctly.

**Comment by kvasbo** [comment]
Have been recreated today on a fresh install of the latest WP, WC and Dokan.

**Comment by kvasbo** [comment]
Just noticed PR#974 fixing this!

**Comment by kapilpaul** [comment]
Hi thanks for mention this issue. Already fixed and a  PR ia waiting to merge. Hopefully this will solved in the next release.

https://github.com/weDevsOfficial/dokan/pull/974
