### ISSUE TITLE
wrong store name show in product detail

### ISSUE THREAD

**Issue by bayufahmiaji** [weDevsOfficial/dokan#981]
# Description

- on the product information page, the page show the owner name instate of showing the shop/merchant name.

# Steps to reproduce

1. Go to product list page
2. choose an item
3. look at the bottom left of the screen, there should be a vendor shop name but it shows the owner name.

# Screenshots/Video

![Untitled](https://user-images.githubusercontent.com/46392719/101132677-f8caad00-3639-11eb-9e47-3c148a372517.png)
![Untitled(1)](https://user-images.githubusercontent.com/46392719/101132715-097b2300-363a-11eb-84fe-5620c4c2a813.png)

**Comment by kapilpaul** [comment]
Hi, can you provide some more details? if possible please attach some screenshots.

**Comment by kapilpaul** [comment]
Thank you for the detailed info.

**Comment by bayufahmiaji** [comment]
> 
> 
> Thank you for the detailed info.

can you proceed this issue? cause another contributor have closed my PR, this is detailed video https://youtu.be/OLmYzd3vigg
