### ISSUE TITLE
The vendor can't change the display name

### ISSUE THREAD

**Issue by FaraziF** [weDevsOfficial/dokan#997]
**Scenario:** When vendor change display name then display name automatically switches to store name. Please review the [video](https://www.loom.com/share/ac9647935d204f46ba7af324442c2db0)

**Comment by alamgircsebd** [comment]
Did not reproduce this issue correctly. check it https://www.loom.com/share/dfbf5aa98cb8450ebb104d84adbe0d45

**Comment by FaraziF** [comment]
Please try to reproduce as a vendor, not admin

**Comment by nurul-umbhiya** [comment]
@alamgircsebd first change store name of a vendor. then try to change the display name from My Account page for that vendor.
